api_platform:
    defaults:
        pagination_items_per_page: 60
        pagination_maximum_items_per_page: 60
    show_webby: false
    title: 'KLS'
    description: 'Backend API of KLS'
    version: '1.0.0'
    enable_entrypoint: '%kernel.debug%'
    enable_docs: true
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
        file: [ 'application/octet-stream' ]
    mapping:
        paths:
            - '%kernel.project_dir%/src/Core/Entity'
            - '%kernel.project_dir%/src/CreditGuaranty/Entity'
            - '%kernel.project_dir%/src/Syndication/Agency/Entity'
            - '%kernel.project_dir%/src/Syndication/Arrangement/Entity'
    patch_formats:
        json:     ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: 400
        ApiPlatform\Core\Exception\FilterValidationException: 400
        ApiPlatform\Core\Validator\Exception\ValidationException: 400 # Revert change introduced with api-platform/core:2.6.*
        Doctrine\ORM\OptimisticLockException: 409
        # Convert not found exception to 403 for security reason
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 403
    path_segment_name_generator: 'KLS\Core\ApiPlatform\Operation\PathSegmentNameWithDomainGenerator'
