api_platform:
    title: 'KLS'
    description: 'Backend API of KLS'
    version: '1.0.0'
    enable_entrypoint: true
    enable_docs: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
