api_platform:
    show_webby: false
    title: 'KLS'
    description: 'Backend API of KLS'
    version: '1.0.0'
    enable_entrypoint: '%kernel.debug%'
    enable_docs: '%kernel.debug%'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json:     ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: 400
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409
        # Convert not found exception to 403 for security reason
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 403
