framework:
    assets:
        base_urls:
            - "%router.request_context.scheme%://%env(HOST_CDN_URL)%"
        packages:
            gulp:
                base_path: /assets
            user_upload:
                base_path: /shared/upload
        json_manifest_path: '%kernel.project_dir%/public/default/assets/rev-manifest.json'
