framework:
    assets:
        base_urls:
            - "%router.request_context.scheme%://%env(HOST_APP_URL)%"
        packages:
            gulp:
                base_path: /assets
            project:
                base_path: /var/upload
        json_manifest_path: '%kernel.project_dir%/public/default/assets/rev-manifest.json'
