parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. You should not need to change this value.
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options:
                authMechanism:  SCRAM-SHA-1
                authSource:     "%mongodb_auth_source%"
                connect:        true
                ssl:            "%mongodb_ssl_connect%"
                password:       "%mongodb_password%"
                username:       "%mongodb_username%"
                readPreference: primaryPreferred
                replicaSet:     "%mongodb_replica_set_name%"
    default_database: "%mongodb_default_database%"
    document_managers:
        default:
            auto_mapping: true
            retry_connect: 4
            retry_query:   4
