ekino_new_relic:
    enabled: false
#    application_name: "%new_relic.front_app_name%"
#    api_key: "%env(NEWRELIC_API_KEY)%"
#    instrument: true
#    deprecations: false
#    http:
#        using_symfony_cache: true
#    monolog:
#        enabled: true
#        channels: ~
