httplug:
    plugins:
        logger: ~
    clients:
        nexy_slack:
            factory: 'httplug.factory.symfony'
            plugins: ['httplug.plugin.logger']
            config:
                timeout: 2
