framework:
    http_client:
        max_host_connections: 10
        scoped_clients:
            psn.client:
                base_uri: '%psn.base_uri%'
            hubspot.client:
                base_uri: '%hubspot.base_uri%'
