framework:
    http_client:
        max_host_connections: 10
        scoped_clients:
            psn.client:
                base_uri: '%psn.base_uri%'
            hubspot.crm.client:
                base_uri: '%hubspot.base_crm_uri%'
                query:
                    hapikey: '%hubspot.api.key%'
            hubspot.integration.client:
                base_uri: '%hubspot.base_integration_uri%'
                query:
                    hapikey: '%hubspot.api.key%'
            insee.client:
                base_uri: '%insee.base_uri%'
                auth_bearer: '50afb10f-39b3-3f75-8660-764884f834bb' #This token does not work anymore
                headers:
                    Accept: 'application/json'
