framework:
    messenger:
        failure_transport: failed

        transports:
            async: '%env(MESSENGER_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'KLS\Core\Message\AsyncMessageInterface': async
            # If a message doesn't match any routing rules, it won't be sent to any transport and will be handled immediately.
            # In some cases (like when binding handlers to different transports), it's easier or more flexible to handle this explicitly:
            # by creating a sync transport and "sending" messages there to be handled immediately.
            'KLS\Core\Entity\Request\ResetPassword': sync
