services:
    cals.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: latest
                region: '%env(AWS_S3_REGION)%'
                credentials:
                    key: '%env(AWS_API_KEY)%'
                    secret: '%env(AWS_API_SECRET)%'

oneup_flysystem:
    adapters:
        user_attachment_adapter:
            local:
                directory: '%directory.protected%attachment'
        generated_document_adapter:
            local:
                directory: '%directory.protected%generated_document'
        public_user_upload_adapter:
            local:
                directory: '%directory.shared_public%upload'
        # AWS S3 adapters
        user_attachment_adapter_s3:
            awss3v3:
                client: cals.s3_client
                bucket: '%env(AWS_S3_BUCKET_USER_ATTACHMENT)%'
                prefix: ~
        generated_document_adapter_s3:
            awss3v3:
                client: cals.s3_client
                bucket: '%env(AWS_S3_BUCKET_GENERATED_DOCUMENT)%'
                prefix: ~
    filesystems:
        user_attachment:
            adapter: user_attachment_adapter
            alias: League\Flysystem\UserAttachmentFilesystem
        generated_document:
            adapter: generated_document_adapter
            alias: League\Flysystem\GeneratedDocumentFilesystem
        public_user_upload:
            adapter: public_user_upload_adapter
            alias: League\Flysystem\PublicUserUploadFilesystem
