services:
    kls.s3_client:
        class: Aws\S3\S3Client
        arguments:
            # On AWS, credentials are managed using an EC2 instance profile
            - version: latest
              region: '%env(AWS_S3_REGION)%'

oneup_flysystem:
    adapters:
        user_attachment_adapter:
            local:
                location: '%directory.protected%attachment'
        generated_document_adapter:
            local:
                location: '%directory.protected%generated_document'
        # AWS S3 adapters
        user_attachment_adapter_s3:
            awss3v3:
                client: kls.s3_client
                bucket: '%env(AWS_S3_BUCKET_USER_ATTACHMENT)%'
                prefix: ''
                streamReads: false
        generated_document_adapter_s3:
            awss3v3:
                client: kls.s3_client
                bucket: '%env(AWS_S3_BUCKET_GENERATED_DOCUMENT)%'
                prefix: ''
                streamReads: false
    filesystems:
        user_attachment:
            adapter: user_attachment_adapter_s3
            alias: user_attachment_filesystem
        generated_document:
            adapter: generated_document_adapter_s3
            alias: generated_document_filesystem
