security:
    encoders:
        Unilend\Entity\Clients:
            id: Unilend\Security\BCryptPasswordEncoder
        md5:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

    providers:
        database_users:
            entity: { class: Unilend\Entity\Clients, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            pattern: ^/
            anonymous: ~
            guard:
                authenticators:
                    - Unilend\Security\LoginAuthenticator
            user_checker: Unilend\Security\User\UserChecker
            logout:
                path: logout
                target: /
                success_handler: Unilend\Security\LogoutSuccessHandler

    access_denied_url: /login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
