security:
    encoders:
        KLS\Core\Entity\User:
            algorithm: 'auto'

    providers:
        database_users:
            entity: { class: KLS\Core\Entity\User, property: email }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        api:
            stateless: true
            anonymous: true
            user_checker: KLS\Core\Security\UserChecker
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
                    - KLS\Core\Security\TemporaryTokenAuthenticator
                    - KLS\Core\Security\UsernamePasswordRecaptchaAuthenticator
                entry_point: lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: '^/captcha_checks', allow_if: "is_anonymous()" }
        - { path: '^/core/authentication_token', allow_if: "is_anonymous()" }
        - { path: '^/core/legal_documents', allow_if: "is_authenticated() or is_anonymous()" }
        - { path: '^/core/pulse$', allow_if: "is_anonymous()" }
        - { path: '^/core/reset_passwords$', allow_if: "is_anonymous()" }
        - { path: '^/core/temporary_tokens', allow_if: "is_anonymous()" }
        - { path: '^/core/token/refresh', allow_if: "is_authenticated() or is_anonymous()" }
        - { path: '^/docs', allow_if: "is_authenticated() or is_anonymous()" }
        - { path: '^/.+', allow_if: 'is_authenticated()' }
