security:
    encoders:
        Unilend\Entity\Clients:
            algorithm: 'auto'

    providers:
        database_users:
            entity: { class: Unilend\Entity\Clients, property: email }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            pattern: ^/
            anonymous: ~
            guard:
                authenticators:
                    - Unilend\Security\LoginAuthenticator
            user_checker: Unilend\Security\UserChecker
            logout:
                path: logout
                target: /
            switch_user: true

    access_denied_url: /login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/compte/initialisation/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sonata/cache, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/conditions-service, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/projet/invitation/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
