#sonata_seo:
#    encoding: UTF-8
#    page:
#        title: 'Unilend : les particuliers prêtent aux entreprises françaises'
#        default: sonata.seo.page.default
#        metas:
#            name:
#                keywords: 'Prêter Emprunter'
#                description: 'Sur Unilend, tout le monde peut prêter aux entreprises françaises et recevoir des intérêts.'
#                robots: 'index, follow'
#                viewport: 'width=device-width, initial-scale=1'
#
#            http-equiv:
#                'Content-Type': 'text/html; charset=utf-8'
#                'X-UA-Compatible': 'IE=edge,chrome=1;'
