swiftmailer:
    transport: 'smtp'
    url: '%env(MAILER_URL)%'
    #spool:
    #    type: service
    #    id: 'Unilend\SwiftMailer\DatabaseSpool'

services:
    _defaults:
        autowire: true

    Mailjet\Client:
        arguments:
            $key: '%env(MAILJET_API_KEY)%'
            $secret: '%env(MAILJET_API_SECRET)%'
            $call: true
            $settings:
                version: 'v3.1'

    mailjet:
        alias: 'Unilend\SwiftMailer\MailjetTransport'
        public: true

    swiftmailer.mailer.transport.mailjet:
        alias: 'Unilend\SwiftMailer\MailjetTransport'
        public: true

    Unilend\SwiftMailer\MailjetTransport:
        shared: false

    Swift_Events_EventDispatcher:
        class: Swift_Events_SimpleEventDispatcher
        shared: false
