swiftmailer:
    default_mailer: normal
    mailers:
        normal:
            transport: 'mailjet'
            spool:
                type: service
                id: 'Unilend\SwiftMailer\DatabaseSpool'
        fast:
            transport: 'mailjet'

services:
    Mailjet\Client:
        arguments:
            $key: '%env(MAILJET_API_KEY)%'
            $secret: '%env(MAILJET_API_SECRET)%'
            $call: true
            $settings:
                version: 'v3.1'

    mailjet: '@Unilend\SwiftMailer\MailjetTransport'
    swiftmailer.mailer.transport.mailjet: '@mailjet'
