swiftmailer:
  transport: 'smtp'
  username: '%env(MAILJET_API_KEY)%'
  password: '%env(MAILJET_API_SECRET)%'
  host: 'in-v3.mailjet.com'
  port: '25'
  sender_address: 'support@kls-platfrom.com'
  delivery_addresses:
    - test@kls-platform.com
