services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    #Twig\Extensions\IntlExtension: ~   # needed for the 'localizeddate' filter but it's extended by Unilend\Twig\IntlExtension
    Twig\Extensions\TextExtension: ~
