oneup_flysystem:
    filesystems:
        user_attachment:
            adapter: user_attachment_adapter_s3
            alias: League\Flysystem\UserAttachmentFilesystem
        generated_document_adapter:
            adapter: generated_document_adapter_s3
            alias: League\Flysystem\GeneratedDocumentFilesystem
