# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-hostsupdater")
  puts "--- WARNING ---"
  puts "vagrant-hostsupdater is not installed"
  puts "Type : "
  puts "vagrant plugin install vagrant-hostsupdater"
  puts "to install it"
end

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.name = 'unilend_php56_nginx14_percona56'
  end
  config.hostsupdater.aliases = ["dev.www.unilend.fr", "dev.admin.unilend.fr", "dev.pma.unilend.fr", "dev.mailcatcher.unilend.fr"]

  config.vm.synced_folder "../", "/srv/sites/unilend", type: "nfs"

  config.vm.provision "shell", path: "increase_swap.sh"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision "shell", inline: "service nginx restart", run: "always"
end