# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/precise64"

  config.vm.network "private_network", ip: "172.28.128.3"
  config.vm.hostname = "dev.www.unilend.fr"
  config.hostsupdater.aliases = ["dev.admin.unilend.fr", "dev.pma.unilend.fr"]

  config.vm.synced_folder "../", "/srv/sites/unilend",
    owner: "vagrant",
    group: "vagrant",
    mount_options: ["dmode=777,fmode=777"]

  config.vm.provision :shell, path: "bootstrap.sh"

end
