# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-hostsupdater")
  puts "--- WARNING ---"
  puts "vagrant-hostsupdater is not installed"
  puts "Type : "
  puts "vagrant plugin install vagrant-hostsupdater"
  puts "to install it"
end

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/precise64"

  config.vm.network "private_network", ip: "172.28.128.3"
  config.vm.hostname = "dev.unilend"
  config.hostsupdater.aliases = ["dev.www.unilend.fr", "dev.admin.unilend.fr", "dev.pma.unilend.fr", "dev.mailcatcher.unilend.fr"]

  config.vm.synced_folder "../", "/srv/sites/unilend", type: "nfs"

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision "shell", inline: "service apache2 restart", run: "always"
  config.vm.provision "shell", inline: "mailcatcher", run: "always"

end
