doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        result_cache_driver:
            type: service
            id: doctrine.result_cache_provider
    dbal:
        connections:
            default:
                options:
                    !php/const PDO::MYSQL_ATTR_SSL_CA: '%env(DATABASE_SSL_CA)%'
            migration:
                options:
                    !php/const PDO::MYSQL_ATTR_SSL_CA: '%env(DATABASE_SSL_CA)%'
