<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version00000000000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The migration that contains the whole schema';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf('mysql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $dump = <<<'SCHEMA_CREATION'
                        CREATE TABLE syndication_project_participation_member (id INT AUTO_INCREMENT NOT NULL, id_project_participation INT NOT NULL, id_staff INT NOT NULL, id_accepted_nda_version INT DEFAULT NULL, added_by INT NOT NULL, archived_by INT DEFAULT NULL, nda_accepted DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', accepted_nda_term TEXT DEFAULT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, archived DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_4CEF2D05B5B48B91 (public_id), INDEX IDX_4CEF2D05AE73E249 (id_project_participation), INDEX IDX_4CEF2D05ACEBB2A2 (id_staff), INDEX IDX_4CEF2D05EFC7EA74 (id_accepted_nda_version), INDEX IDX_4CEF2D05699B6BAF (added_by), INDEX IDX_4CEF2D0551B07D6D (archived_by), UNIQUE INDEX UNIQ_4CEF2D05ACEBB2A2AE73E249 (id_staff, id_project_participation), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project_participation_status (id INT AUTO_INCREMENT NOT NULL, id_project_participation INT NOT NULL, added_by INT NOT NULL, status SMALLINT NOT NULL, public_id VARCHAR(36) NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_470BB261B5B48B91 (public_id), INDEX IDX_470BB261AE73E249 (id_project_participation), INDEX IDX_470BB261699B6BAF (added_by), INDEX IDX_470BB2617B00651CAE73E249 (status, id_project_participation), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project_message (id INT AUTO_INCREMENT NOT NULL, id_participation INT NOT NULL, added_by INT NOT NULL, content LONGTEXT NOT NULL, archived DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_FA8F31D5B5B48B91 (public_id), INDEX IDX_FA8F31D5157D332A (id_participation), INDEX IDX_FA8F31D5699B6BAF (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_tag (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_tranche (id INT AUTO_INCREMENT NOT NULL, id_project INT NOT NULL, name VARCHAR(191) NOT NULL, loan_type VARCHAR(30) NOT NULL, repayment_type VARCHAR(30) NOT NULL, duration SMALLINT NOT NULL, capital_periodicity SMALLINT DEFAULT NULL, interest_periodicity SMALLINT DEFAULT NULL, expected_releasing_date DATE DEFAULT NULL COMMENT '(DC2Type:date_immutable)', expected_starting_date DATE DEFAULT NULL COMMENT '(DC2Type:date_immutable)', commission_type VARCHAR(30) DEFAULT NULL, commission_rate NUMERIC(5, 4) DEFAULT NULL, comment LONGTEXT DEFAULT NULL, syndicated TINYINT(1) NOT NULL, unsyndicated_funder_type VARCHAR(255) DEFAULT NULL, third_party_funder VARCHAR(255) DEFAULT NULL, color VARCHAR(255) NOT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, money_amount NUMERIC(15, 2) NOT NULL, money_currency VARCHAR(3) NOT NULL, rate_index_type VARCHAR(20) DEFAULT NULL, rate_margin NUMERIC(4, 4) DEFAULT NULL, rate_floor NUMERIC(4, 4) DEFAULT NULL, rate_floor_type VARCHAR(20) DEFAULT NULL, UNIQUE INDEX UNIQ_374A86C1B5B48B91 (public_id), INDEX IDX_374A86C1F12E799E (id_project), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project_participation_tranche (id INT AUTO_INCREMENT NOT NULL, id_tranche INT NOT NULL, id_project_participation INT NOT NULL, added_by INT NOT NULL, public_id VARCHAR(36) NOT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', invitation_reply_added DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', invitation_reply_money_amount NUMERIC(15, 2) DEFAULT NULL, invitation_reply_money_currency VARCHAR(3) DEFAULT NULL, allocation_added DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', allocation_money_amount NUMERIC(15, 2) DEFAULT NULL, allocation_money_currency VARCHAR(3) DEFAULT NULL, UNIQUE INDEX UNIQ_48EF5E16B5B48B91 (public_id), INDEX IDX_48EF5E16B8FAF130 (id_tranche), INDEX IDX_48EF5E16AE73E249 (id_project_participation), INDEX IDX_48EF5E16699B6BAF (added_by), UNIQUE INDEX UNIQ_48EF5E16B8FAF130AE73E249 (id_tranche, id_project_participation), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project_file (id INT AUTO_INCREMENT NOT NULL, id_file INT NOT NULL, id_project INT NOT NULL, added_by INT NOT NULL, type VARCHAR(60) NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_6C361026B5B48B91 (public_id), UNIQUE INDEX UNIQ_6C3610267BF2A12 (id_file), INDEX IDX_6C361026F12E799E (id_project), INDEX IDX_6C361026699B6BAF (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project_participation (id INT AUTO_INCREMENT NOT NULL, id_project INT NOT NULL, id_company INT NOT NULL, id_current_status INT DEFAULT NULL, id_nda INT DEFAULT NULL, added_by INT NOT NULL, committee_deadline DATE DEFAULT NULL COMMENT '(DC2Type:date_immutable)', committee_comment LONGTEXT DEFAULT NULL, invitation_reply_mode VARCHAR(10) DEFAULT NULL, allocation_fee_rate NUMERIC(5, 4) DEFAULT NULL, participant_last_consulted DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, interest_request_fee_rate NUMERIC(5, 4) DEFAULT NULL, interest_request_added DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', interest_request_max_money_amount NUMERIC(15, 2) DEFAULT NULL, interest_request_max_money_currency VARCHAR(3) DEFAULT NULL, interest_request_money_amount NUMERIC(15, 2) DEFAULT NULL, interest_request_money_currency VARCHAR(3) DEFAULT NULL, interest_reply_added DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', interest_reply_money_amount NUMERIC(15, 2) DEFAULT NULL, interest_reply_money_currency VARCHAR(3) DEFAULT NULL, invitation_request_fee_rate NUMERIC(5, 4) DEFAULT NULL, invitation_request_added DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', invitation_request_money_amount NUMERIC(15, 2) DEFAULT NULL, invitation_request_money_currency VARCHAR(3) DEFAULT NULL, UNIQUE INDEX UNIQ_D10BDF9B5B48B91 (public_id), INDEX IDX_D10BDF9F12E799E (id_project), INDEX IDX_D10BDF99122A03F (id_company), UNIQUE INDEX UNIQ_D10BDF941AF0274 (id_current_status), UNIQUE INDEX UNIQ_D10BDF91888280F (id_nda), INDEX IDX_D10BDF9699B6BAF (added_by), UNIQUE INDEX UNIQ_D10BDF9F12E799E9122A03F (id_project, id_company), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project (id INT AUTO_INCREMENT NOT NULL, id_company_submitter INT NOT NULL, id_user_submitter INT NOT NULL, id_market_segment INT NOT NULL, id_description_document INT DEFAULT NULL, id_nda INT DEFAULT NULL, id_current_status INT DEFAULT NULL, risk_group_name VARCHAR(255) NOT NULL, title VARCHAR(191) NOT NULL, description MEDIUMTEXT DEFAULT NULL, signing_deadline DATE DEFAULT NULL COMMENT '(DC2Type:date_immutable)', allocation_deadline DATE DEFAULT NULL COMMENT '(DC2Type:date_immutable)', participant_reply_deadline DATE DEFAULT NULL COMMENT '(DC2Type:date_immutable)', interest_expression_deadline DATE DEFAULT NULL COMMENT '(DC2Type:date_immutable)', contractualization_deadline DATE DEFAULT NULL COMMENT '(DC2Type:date_immutable)', internal_rating_score VARCHAR(8) DEFAULT NULL, offer_visibility VARCHAR(25) NOT NULL, syndication_type VARCHAR(80) DEFAULT NULL, participation_type VARCHAR(80) DEFAULT NULL, risk_type VARCHAR(80) DEFAULT NULL, interest_expression_enabled TINYINT(1) DEFAULT NULL, funding_specificity VARCHAR(10) DEFAULT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, global_funding_money_amount NUMERIC(15, 2) NOT NULL, global_funding_money_currency VARCHAR(3) NOT NULL, arrangement_commission_money_amount NUMERIC(15, 2) DEFAULT NULL, arrangement_commission_money_currency VARCHAR(3) DEFAULT NULL, privileged_contact_first_name VARCHAR(255) DEFAULT NULL, privileged_contact_last_name VARCHAR(255) DEFAULT NULL, privileged_contact_parent_unit VARCHAR(255) DEFAULT NULL, privileged_contact_occupation VARCHAR(255) DEFAULT NULL, privileged_contact_email VARCHAR(255) DEFAULT NULL, privileged_contact_phone VARCHAR(35) DEFAULT NULL, UNIQUE INDEX UNIQ_7E9E0E6FB5B48B91 (public_id), INDEX IDX_7E9E0E6F24FEBA6C (id_company_submitter), INDEX IDX_7E9E0E6FDB546869 (id_user_submitter), INDEX IDX_7E9E0E6F2C71A0E3 (id_market_segment), UNIQUE INDEX UNIQ_7E9E0E6F61AA99F6 (id_description_document), UNIQUE INDEX UNIQ_7E9E0E6F1888280F (id_nda), UNIQUE INDEX UNIQ_7E9E0E6F41AF0274 (id_current_status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project_tag (project_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_7F469F89166D1F9C (project_id), INDEX IDX_7F469F89BAD26311 (tag_id), PRIMARY KEY(project_id, tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project_status (id INT AUTO_INCREMENT NOT NULL, id_project INT NOT NULL, added_by INT NOT NULL, status SMALLINT NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX idx_project_status_status (status), INDEX idx_project_status_id_project (id_project), INDEX idx_project_status_added_by (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_zz_versioned_project_comment (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', username VARCHAR(255) DEFAULT NULL, INDEX IDX_C6AE5C1CA78D87A7 (logged_at), INDEX IDX_C6AE5C1CF85E0677 (username), INDEX IDX_C6AE5C1C232D562B69684D7DBF1CD3C3 (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_zz_versioned_project_participation_tranche (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', username VARCHAR(255) DEFAULT NULL, INDEX IDX_ABC9EF1CA78D87A7 (logged_at), INDEX IDX_ABC9EF1CF85E0677 (username), INDEX IDX_ABC9EF1C232D562B69684D7DBF1CD3C3 (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_zz_versioned_tranche (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', username VARCHAR(255) DEFAULT NULL, INDEX IDX_B25546FA78D87A7 (logged_at), INDEX IDX_B25546FF85E0677 (username), INDEX IDX_B25546F232D562B69684D7DBF1CD3C3 (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_zz_versioned_project (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', username VARCHAR(255) DEFAULT NULL, INDEX IDX_42F1DCC1A78D87A7 (logged_at), INDEX IDX_42F1DCC1F85E0677 (username), INDEX IDX_42F1DCC1232D562B69684D7DBF1CD3C3 (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_zz_versioned_project_participation (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', username VARCHAR(255) DEFAULT NULL, INDEX IDX_3996F2CCA78D87A7 (logged_at), INDEX IDX_3996F2CCF85E0677 (username), INDEX IDX_3996F2CC232D562B69684D7DBF1CD3C3 (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project_comment (id INT AUTO_INCREMENT NOT NULL, id_parent INT DEFAULT NULL, id_project INT NOT NULL, id_user INT NOT NULL, content MEDIUMTEXT NOT NULL, visibility INT NOT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_D84653C61BB9D5A2 (id_parent), INDEX IDX_D84653C6F12E799E (id_project), INDEX IDX_D84653C66B3CA4B (id_user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_interest_reply_version (id INT AUTO_INCREMENT NOT NULL, id_project_participation INT NOT NULL, added_by INT NOT NULL, interest_reply_added DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', interest_reply_money_amount NUMERIC(15, 2) DEFAULT NULL, interest_reply_money_currency VARCHAR(3) DEFAULT NULL, INDEX IDX_67F999BAE73E249 (id_project_participation), INDEX IDX_67F999B699B6BAF (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_invitation_reply_version (id INT AUTO_INCREMENT NOT NULL, id_project_participation_tranche INT NOT NULL, id_project_participation_status INT NOT NULL, added_by INT NOT NULL, invitation_reply_added DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', invitation_reply_money_amount NUMERIC(15, 2) DEFAULT NULL, invitation_reply_money_currency VARCHAR(3) DEFAULT NULL, INDEX IDX_ECD74B34F263895D (id_project_participation_tranche), INDEX IDX_ECD74B341BEAFC95 (id_project_participation_status), INDEX IDX_ECD74B34699B6BAF (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE syndication_project_organizer (id INT AUTO_INCREMENT NOT NULL, id_project INT NOT NULL, id_company INT NOT NULL, added_by INT NOT NULL, roles JSON NOT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_BA3B59B4F12E799E (id_project), INDEX IDX_BA3B59B49122A03F (id_company), INDEX IDX_BA3B59B4699B6BAF (added_by), UNIQUE INDEX UNIQ_BA3B59B4F12E799E9122A03F (id_project, id_company), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_mail_queue (id_queue INT AUTO_INCREMENT NOT NULL, status VARCHAR(255) NOT NULL, sent_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', scheduled_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', recipients JSON NOT NULL, serialized LONGTEXT NOT NULL, hash VARCHAR(255) NOT NULL, mailjet_template_id INT DEFAULT NULL, error_message TEXT DEFAULT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX status (status), INDEX idx_mail_queue_sent_at (sent_at), PRIMARY KEY(id_queue)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_user (id INT AUTO_INCREMENT NOT NULL, id_current_status INT DEFAULT NULL, last_name VARCHAR(191) DEFAULT NULL, first_name VARCHAR(191) DEFAULT NULL, phone VARCHAR(35) DEFAULT NULL, email VARCHAR(191) NOT NULL, password VARCHAR(191) DEFAULT NULL, job_function VARCHAR(255) DEFAULT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', roles JSON NOT NULL, public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_BF76157CE7927C74 (email), UNIQUE INDEX UNIQ_BF76157CB5B48B91 (public_id), UNIQUE INDEX UNIQ_BF76157C41AF0274 (id_current_status), INDEX IDX_BF76157CC808BA5A (last_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_staff (id INT AUTO_INCREMENT NOT NULL, id_company INT NOT NULL, id_user INT NOT NULL, id_current_status INT DEFAULT NULL, roles JSON NOT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_14EFD272B5B48B91 (public_id), INDEX IDX_14EFD2729122A03F (id_company), INDEX IDX_14EFD2726B3CA4B (id_user), UNIQUE INDEX UNIQ_14EFD27241AF0274 (id_current_status), UNIQUE INDEX UNIQ_14EFD2726B3CA4B9122A03F (id_user, id_company), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_staff_market_segment (staff_id INT NOT NULL, market_segment_id INT NOT NULL, INDEX IDX_A055377AD4D57CD (staff_id), INDEX IDX_A055377AB5D73EB1 (market_segment_id), PRIMARY KEY(staff_id, market_segment_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_acceptations_legal_docs (id INT AUTO_INCREMENT NOT NULL, id_legal_doc INT NOT NULL, accepted_by INT NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_4F817FFFB5B48B91 (public_id), INDEX IDX_4F817FFF7F757BBC (id_legal_doc), INDEX IDX_4F817FFFBD57FA7C (accepted_by), UNIQUE INDEX UNIQ_4F817FFF7F757BBCBD57FA7C (id_legal_doc, accepted_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_legal_document (id INT AUTO_INCREMENT NOT NULL, type SMALLINT NOT NULL, title VARCHAR(191) NOT NULL, content LONGTEXT NOT NULL, public_id VARCHAR(36) NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_89F81438B5B48B91 (public_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_file (id INT AUTO_INCREMENT NOT NULL, id_current_file_version INT DEFAULT NULL, archived_by INT DEFAULT NULL, public_id VARCHAR(36) NOT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', archived DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_BE7AF525B5B48B91 (public_id), UNIQUE INDEX UNIQ_BE7AF525173B2587 (id_current_file_version), INDEX IDX_BE7AF52551B07D6D (archived_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_market_segment (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(30) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_user_successful_login (id INT AUTO_INCREMENT NOT NULL, id_user INT NOT NULL, id_user_agent INT DEFAULT NULL, action VARCHAR(20) NOT NULL, ip VARCHAR(45) DEFAULT NULL, country_iso_code VARCHAR(2) DEFAULT NULL, city VARCHAR(64) DEFAULT NULL, recaptcha_score DOUBLE PRECISION DEFAULT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_2EADC30E6B3CA4B (id_user), INDEX IDX_2EADC30E61C3E712 (id_user_agent), INDEX idx_user_successful_login_ip (ip), INDEX idx_user_successful_login_added (added), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_user_status (id INT AUTO_INCREMENT NOT NULL, id_user INT NOT NULL, status SMALLINT NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX idx_user_status_id_user (id_user), INDEX idx_user_status_status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_file_version_signature (id INT AUTO_INCREMENT NOT NULL, id_file_version INT NOT NULL, id_signatory INT NOT NULL, added_by INT NOT NULL, status SMALLINT NOT NULL, transaction_number VARCHAR(100) DEFAULT NULL, signature_url VARCHAR(255) DEFAULT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_BB36B525B5B48B91 (public_id), INDEX IDX_BB36B525C7BB1F8A (id_file_version), INDEX IDX_BB36B5252B0DC78F (id_signatory), INDEX IDX_BB36B525699B6BAF (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_message_file (id INT AUTO_INCREMENT NOT NULL, id_file INT NOT NULL, id_message INT NOT NULL, public_id VARCHAR(36) NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_88BA1411B5B48B91 (public_id), INDEX IDX_88BA14117BF2A12 (id_file), INDEX IDX_88BA14116820990F (id_message), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_company_status (id INT AUTO_INCREMENT NOT NULL, id_company INT NOT NULL, status SMALLINT NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_BDC3E8E6B5B48B91 (public_id), INDEX IDX_BDC3E8E69122A03F (id_company), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_user_failed_login (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(191) DEFAULT NULL, ip VARCHAR(191) DEFAULT NULL, error VARCHAR(191) DEFAULT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', recaptcha_score DOUBLE PRECISION DEFAULT NULL, INDEX idx_user_failed_login_username (username), INDEX idx_user_failed_login_ip (ip), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_file_download (id INT AUTO_INCREMENT NOT NULL, id_file_version INT NOT NULL, added_by INT NOT NULL, type VARCHAR(150) NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_41EFE7B2C7BB1F8A (id_file_version), INDEX IDX_41EFE7B2699B6BAF (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_temporary_token (id INT AUTO_INCREMENT NOT NULL, id_user INT NOT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', token VARCHAR(150) NOT NULL, expires DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', accessed DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX fk_temporary_token_id_user (id_user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_zz_versioned_user (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', username VARCHAR(255) DEFAULT NULL, INDEX IDX_F04DD111A78D87A7 (logged_at), INDEX IDX_F04DD111F85E0677 (username), INDEX IDX_F04DD111232D562B69684D7DBF1CD3C3 (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_message (id INT AUTO_INCREMENT NOT NULL, id_message_thread INT NOT NULL, id_sender INT NOT NULL, body MEDIUMTEXT NOT NULL, broadcast VARCHAR(36) DEFAULT NULL, public_id VARCHAR(36) NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_A4AA854CB5B48B91 (public_id), INDEX IDX_A4AA854C3B616C8A (id_message_thread), INDEX IDX_A4AA854C7937FF22 (id_sender), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_staff_log (id INT AUTO_INCREMENT NOT NULL, added_by INT NOT NULL, staff_id INT NOT NULL, previous_roles JSON NOT NULL, previous_market_segment JSON NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_4E53C328699B6BAF (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_user_agent (id INT AUTO_INCREMENT NOT NULL, id_user INT NOT NULL, browser_name VARCHAR(48) DEFAULT NULL, browser_version VARCHAR(32) DEFAULT NULL, device_model VARCHAR(48) DEFAULT NULL, device_brand VARCHAR(48) DEFAULT NULL, device_type VARCHAR(32) DEFAULT NULL, user_agent_string VARCHAR(256) NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_F805E3246B3CA4B (id_user), INDEX IDX_F805E3246B3CA4BD5438ED0111092BEDAD7193F5E78213 (id_user, browser_name, device_model, device_brand, device_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_message_status (id INT AUTO_INCREMENT NOT NULL, id_message INT DEFAULT NULL, id_recipient INT NOT NULL, status SMALLINT NOT NULL, unread_notified DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_B77B119C6820990F (id_message), INDEX IDX_B77B119CE831476E (id_recipient), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_company (id INT AUTO_INCREMENT NOT NULL, id_current_status INT DEFAULT NULL, display_name VARCHAR(300) NOT NULL, company_name VARCHAR(300) NOT NULL, siren VARCHAR(9) DEFAULT NULL, bank_code VARCHAR(10) NOT NULL, group_name VARCHAR(50) DEFAULT NULL, vat_number VARCHAR(16) DEFAULT NULL, applicable_vat VARCHAR(20) NOT NULL, email_domain VARCHAR(255) DEFAULT NULL, short_code VARCHAR(10) NOT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_5DA8BC7CDB8BBA08 (siren), UNIQUE INDEX UNIQ_5DA8BC7CDD756216 (bank_code), UNIQUE INDEX UNIQ_5DA8BC7C8910B08D (vat_number), UNIQUE INDEX UNIQ_5DA8BC7CDA33CDFB (email_domain), UNIQUE INDEX UNIQ_5DA8BC7C17D2FE0D (short_code), UNIQUE INDEX UNIQ_5DA8BC7CB5B48B91 (public_id), UNIQUE INDEX UNIQ_5DA8BC7C41AF0274 (id_current_status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_message_thread (id INT AUTO_INCREMENT NOT NULL, id_project_participation INT DEFAULT NULL, public_id VARCHAR(36) NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_FD5B3803B5B48B91 (public_id), UNIQUE INDEX UNIQ_FD5B3803AE73E249 (id_project_participation), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_company_module (id INT AUTO_INCREMENT NOT NULL, id_company INT NOT NULL, updated_by INT DEFAULT NULL, code VARCHAR(255) NOT NULL, activated TINYINT(1) NOT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, arrangement_annual_license_money_amount NUMERIC(15, 2) DEFAULT NULL, arrangement_annual_license_money_currency VARCHAR(3) DEFAULT NULL, UNIQUE INDEX UNIQ_CAE7ABD2B5B48B91 (public_id), INDEX IDX_CAE7ABD29122A03F (id_company), INDEX IDX_CAE7ABD216FE72E1 (updated_by), UNIQUE INDEX UNIQ_CAE7ABD29122A03F77153098 (id_company, code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_company_module_log (id INT AUTO_INCREMENT NOT NULL, id_module INT NOT NULL, added_by INT NOT NULL, activated TINYINT(1) NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_F1AAFC292A1393C5 (id_module), INDEX IDX_F1AAFC29699B6BAF (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_staff_status (id INT AUTO_INCREMENT NOT NULL, id_staff INT NOT NULL, added_by INT NOT NULL, status SMALLINT NOT NULL, added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_D3CD6E7FB5B48B91 (public_id), INDEX IDX_D3CD6E7FACEBB2A2 (id_staff), INDEX IDX_D3CD6E7F699B6BAF (added_by), INDEX idx_staff_status_status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE core_file_version (id INT AUTO_INCREMENT NOT NULL, id_file INT NOT NULL, added_by INT NOT NULL, path VARCHAR(191) NOT NULL, original_name VARCHAR(191) DEFAULT NULL, size INT DEFAULT NULL, file_system VARCHAR(255) NOT NULL, encryption_key VARCHAR(512) DEFAULT NULL, mime_type VARCHAR(150) DEFAULT NULL, updated DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', added DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', public_id VARCHAR(36) NOT NULL, UNIQUE INDEX UNIQ_49CAD320B5B48B91 (public_id), INDEX IDX_49CAD3207BF2A12 (id_file), INDEX IDX_49CAD320699B6BAF (added_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
                        ALTER TABLE syndication_project_participation_member ADD CONSTRAINT FK_4CEF2D05AE73E249 FOREIGN KEY (id_project_participation) REFERENCES syndication_project_participation (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_participation_member ADD CONSTRAINT FK_4CEF2D05ACEBB2A2 FOREIGN KEY (id_staff) REFERENCES core_staff (id);
                        ALTER TABLE syndication_project_participation_member ADD CONSTRAINT FK_4CEF2D05EFC7EA74 FOREIGN KEY (id_accepted_nda_version) REFERENCES core_file_version (id);
                        ALTER TABLE syndication_project_participation_member ADD CONSTRAINT FK_4CEF2D05699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_project_participation_member ADD CONSTRAINT FK_4CEF2D0551B07D6D FOREIGN KEY (archived_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_project_participation_status ADD CONSTRAINT FK_470BB261AE73E249 FOREIGN KEY (id_project_participation) REFERENCES syndication_project_participation (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_participation_status ADD CONSTRAINT FK_470BB261699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_project_message ADD CONSTRAINT FK_FA8F31D5157D332A FOREIGN KEY (id_participation) REFERENCES syndication_project_participation (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_message ADD CONSTRAINT FK_FA8F31D5699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_tranche ADD CONSTRAINT FK_374A86C1F12E799E FOREIGN KEY (id_project) REFERENCES syndication_project (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_participation_tranche ADD CONSTRAINT FK_48EF5E16B8FAF130 FOREIGN KEY (id_tranche) REFERENCES syndication_tranche (id);
                        ALTER TABLE syndication_project_participation_tranche ADD CONSTRAINT FK_48EF5E16AE73E249 FOREIGN KEY (id_project_participation) REFERENCES syndication_project_participation (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_participation_tranche ADD CONSTRAINT FK_48EF5E16699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_project_file ADD CONSTRAINT FK_6C3610267BF2A12 FOREIGN KEY (id_file) REFERENCES core_file (id);
                        ALTER TABLE syndication_project_file ADD CONSTRAINT FK_6C361026F12E799E FOREIGN KEY (id_project) REFERENCES syndication_project (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_file ADD CONSTRAINT FK_6C361026699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_project_participation ADD CONSTRAINT FK_D10BDF9F12E799E FOREIGN KEY (id_project) REFERENCES syndication_project (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_participation ADD CONSTRAINT FK_D10BDF99122A03F FOREIGN KEY (id_company) REFERENCES core_company (id);
                        ALTER TABLE syndication_project_participation ADD CONSTRAINT FK_D10BDF941AF0274 FOREIGN KEY (id_current_status) REFERENCES syndication_project_participation_status (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_participation ADD CONSTRAINT FK_D10BDF91888280F FOREIGN KEY (id_nda) REFERENCES core_file (id);
                        ALTER TABLE syndication_project_participation ADD CONSTRAINT FK_D10BDF9699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_project ADD CONSTRAINT FK_7E9E0E6F24FEBA6C FOREIGN KEY (id_company_submitter) REFERENCES core_company (id);
                        ALTER TABLE syndication_project ADD CONSTRAINT FK_7E9E0E6FDB546869 FOREIGN KEY (id_user_submitter) REFERENCES core_user (id);
                        ALTER TABLE syndication_project ADD CONSTRAINT FK_7E9E0E6F2C71A0E3 FOREIGN KEY (id_market_segment) REFERENCES core_market_segment (id);
                        ALTER TABLE syndication_project ADD CONSTRAINT FK_7E9E0E6F61AA99F6 FOREIGN KEY (id_description_document) REFERENCES core_file (id);
                        ALTER TABLE syndication_project ADD CONSTRAINT FK_7E9E0E6F1888280F FOREIGN KEY (id_nda) REFERENCES core_file (id);
                        ALTER TABLE syndication_project ADD CONSTRAINT FK_7E9E0E6F41AF0274 FOREIGN KEY (id_current_status) REFERENCES syndication_project_status (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_tag ADD CONSTRAINT FK_7F469F89166D1F9C FOREIGN KEY (project_id) REFERENCES syndication_project (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_tag ADD CONSTRAINT FK_7F469F89BAD26311 FOREIGN KEY (tag_id) REFERENCES syndication_tag (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_status ADD CONSTRAINT FK_2011913DF12E799E FOREIGN KEY (id_project) REFERENCES syndication_project (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_status ADD CONSTRAINT FK_2011913D699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_project_comment ADD CONSTRAINT FK_D84653C61BB9D5A2 FOREIGN KEY (id_parent) REFERENCES syndication_project_comment (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_comment ADD CONSTRAINT FK_D84653C6F12E799E FOREIGN KEY (id_project) REFERENCES syndication_project (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_comment ADD CONSTRAINT FK_D84653C66B3CA4B FOREIGN KEY (id_user) REFERENCES core_user (id);
                        ALTER TABLE syndication_interest_reply_version ADD CONSTRAINT FK_67F999BAE73E249 FOREIGN KEY (id_project_participation) REFERENCES syndication_project_participation (id);
                        ALTER TABLE syndication_interest_reply_version ADD CONSTRAINT FK_67F999B699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_invitation_reply_version ADD CONSTRAINT FK_ECD74B34F263895D FOREIGN KEY (id_project_participation_tranche) REFERENCES syndication_project_participation_tranche (id);
                        ALTER TABLE syndication_invitation_reply_version ADD CONSTRAINT FK_ECD74B341BEAFC95 FOREIGN KEY (id_project_participation_status) REFERENCES syndication_project_participation_status (id);
                        ALTER TABLE syndication_invitation_reply_version ADD CONSTRAINT FK_ECD74B34699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE syndication_project_organizer ADD CONSTRAINT FK_BA3B59B4F12E799E FOREIGN KEY (id_project) REFERENCES syndication_project (id) ON DELETE CASCADE;
                        ALTER TABLE syndication_project_organizer ADD CONSTRAINT FK_BA3B59B49122A03F FOREIGN KEY (id_company) REFERENCES core_company (id);
                        ALTER TABLE syndication_project_organizer ADD CONSTRAINT FK_BA3B59B4699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE core_user ADD CONSTRAINT FK_BF76157C41AF0274 FOREIGN KEY (id_current_status) REFERENCES core_user_status (id);
                        ALTER TABLE core_staff ADD CONSTRAINT FK_14EFD2729122A03F FOREIGN KEY (id_company) REFERENCES core_company (id);
                        ALTER TABLE core_staff ADD CONSTRAINT FK_14EFD2726B3CA4B FOREIGN KEY (id_user) REFERENCES core_user (id);
                        ALTER TABLE core_staff ADD CONSTRAINT FK_14EFD27241AF0274 FOREIGN KEY (id_current_status) REFERENCES core_staff_status (id) ON DELETE CASCADE;
                        ALTER TABLE core_staff_market_segment ADD CONSTRAINT FK_A055377AD4D57CD FOREIGN KEY (staff_id) REFERENCES core_staff (id) ON DELETE CASCADE;
                        ALTER TABLE core_staff_market_segment ADD CONSTRAINT FK_A055377AB5D73EB1 FOREIGN KEY (market_segment_id) REFERENCES core_market_segment (id) ON DELETE CASCADE;
                        ALTER TABLE core_acceptations_legal_docs ADD CONSTRAINT FK_4F817FFF7F757BBC FOREIGN KEY (id_legal_doc) REFERENCES core_legal_document (id);
                        ALTER TABLE core_acceptations_legal_docs ADD CONSTRAINT FK_4F817FFFBD57FA7C FOREIGN KEY (accepted_by) REFERENCES core_user (id);
                        ALTER TABLE core_file ADD CONSTRAINT FK_BE7AF525173B2587 FOREIGN KEY (id_current_file_version) REFERENCES core_file_version (id);
                        ALTER TABLE core_file ADD CONSTRAINT FK_BE7AF52551B07D6D FOREIGN KEY (archived_by) REFERENCES core_staff (id);
                        ALTER TABLE core_user_successful_login ADD CONSTRAINT FK_2EADC30E6B3CA4B FOREIGN KEY (id_user) REFERENCES core_user (id);
                        ALTER TABLE core_user_successful_login ADD CONSTRAINT FK_2EADC30E61C3E712 FOREIGN KEY (id_user_agent) REFERENCES core_user_agent (id);
                        ALTER TABLE core_user_status ADD CONSTRAINT FK_C963E04B6B3CA4B FOREIGN KEY (id_user) REFERENCES core_user (id);
                        ALTER TABLE core_file_version_signature ADD CONSTRAINT FK_BB36B525C7BB1F8A FOREIGN KEY (id_file_version) REFERENCES core_file_version (id);
                        ALTER TABLE core_file_version_signature ADD CONSTRAINT FK_BB36B5252B0DC78F FOREIGN KEY (id_signatory) REFERENCES core_staff (id);
                        ALTER TABLE core_file_version_signature ADD CONSTRAINT FK_BB36B525699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE core_message_file ADD CONSTRAINT FK_88BA14117BF2A12 FOREIGN KEY (id_file) REFERENCES core_file (id);
                        ALTER TABLE core_message_file ADD CONSTRAINT FK_88BA14116820990F FOREIGN KEY (id_message) REFERENCES core_message (id) ON DELETE CASCADE;
                        ALTER TABLE core_company_status ADD CONSTRAINT FK_BDC3E8E69122A03F FOREIGN KEY (id_company) REFERENCES core_company (id);
                        ALTER TABLE core_file_download ADD CONSTRAINT FK_41EFE7B2C7BB1F8A FOREIGN KEY (id_file_version) REFERENCES core_file_version (id);
                        ALTER TABLE core_file_download ADD CONSTRAINT FK_41EFE7B2699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE core_temporary_token ADD CONSTRAINT FK_CA24E94D6B3CA4B FOREIGN KEY (id_user) REFERENCES core_user (id);
                        ALTER TABLE core_message ADD CONSTRAINT FK_A4AA854C3B616C8A FOREIGN KEY (id_message_thread) REFERENCES core_message_thread (id);
                        ALTER TABLE core_message ADD CONSTRAINT FK_A4AA854C7937FF22 FOREIGN KEY (id_sender) REFERENCES core_staff (id);
                        ALTER TABLE core_staff_log ADD CONSTRAINT FK_4E53C328699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE core_user_agent ADD CONSTRAINT FK_F805E3246B3CA4B FOREIGN KEY (id_user) REFERENCES core_user (id);
                        ALTER TABLE core_message_status ADD CONSTRAINT FK_B77B119C6820990F FOREIGN KEY (id_message) REFERENCES core_message (id);
                        ALTER TABLE core_message_status ADD CONSTRAINT FK_B77B119CE831476E FOREIGN KEY (id_recipient) REFERENCES core_staff (id);
                        ALTER TABLE core_company ADD CONSTRAINT FK_5DA8BC7C41AF0274 FOREIGN KEY (id_current_status) REFERENCES core_company_status (id);
                        ALTER TABLE core_message_thread ADD CONSTRAINT FK_FD5B3803AE73E249 FOREIGN KEY (id_project_participation) REFERENCES syndication_project_participation (id);
                        ALTER TABLE core_company_module ADD CONSTRAINT FK_CAE7ABD29122A03F FOREIGN KEY (id_company) REFERENCES core_company (id);
                        ALTER TABLE core_company_module ADD CONSTRAINT FK_CAE7ABD216FE72E1 FOREIGN KEY (updated_by) REFERENCES core_staff (id);
                        ALTER TABLE core_company_module_log ADD CONSTRAINT FK_F1AAFC292A1393C5 FOREIGN KEY (id_module) REFERENCES core_company_module (id);
                        ALTER TABLE core_company_module_log ADD CONSTRAINT FK_F1AAFC29699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE core_staff_status ADD CONSTRAINT FK_D3CD6E7FACEBB2A2 FOREIGN KEY (id_staff) REFERENCES core_staff (id);
                        ALTER TABLE core_staff_status ADD CONSTRAINT FK_D3CD6E7F699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
                        ALTER TABLE core_file_version ADD CONSTRAINT FK_49CAD3207BF2A12 FOREIGN KEY (id_file) REFERENCES core_file (id);
                        ALTER TABLE core_file_version ADD CONSTRAINT FK_49CAD320699B6BAF FOREIGN KEY (added_by) REFERENCES core_staff (id);
            SCHEMA_CREATION;

        $this->addSql($dump);
    }

    public function down(Schema $schema): void
    {
        //nothing to do.
    }
}
