imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: parameters_extended.yml, ignore_errors: true }
    - { resource: dql_mysql_functions.yml, ignore_errors: true }

framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    default_locale:  "%locale%"
    templating:
        engines: ['twig']
    assets:
        base_urls:
            - "%router.request_context.scheme%://%url.host_default%"
        packages:
            gulp:
                base_path: /assets
        version_strategy: unilend.frontbundle.gulp_rev_version_strategy
    translator:
        enabled: true
        fallbacks: ["fr_FR"]
        paths:
            - "%kernel.root_dir%/../src/Unilend/Bundle/TranslationBundle/Resources/translations"
        logging: true
    session:
        handler_id: null
        gc_maxlifetime: 3600
    csrf_protection: true
    form:
        csrf_protection:
            field_name: _csrf
    serializer:
        enabled: true
    validation:
        enabled: true

cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true
        default_controller: UnilendFrontBundle:Main:cms
        route_provider_service_id: "unilend.frontbundle.provider.route_provider"

twig:
    strict_variables: "%kernel.debug%"
    exception_controller:  UnilendFrontBundle:Exception:show
    paths:
        - "%kernel.root_dir%/Resources/views/frontbundle/"
    form_themes:
        - 'frontbundle/layouts/form_layout.html.twig'

doctrine:
    dbal:
        connections:
            default:
                driver:        "%database_driver%"
                host:          "%database_host%"
                port:          "%database_port%"
                dbname:        "%database_name%"
                user:          "%database_user%"
                password:      "%database_password%"
                charset:       utf8mb4
                wrapper_class: "%dbal_wrapper_class%"
                driver_class:  "%dbal_driver_class%"
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    enum: string
                options:
                    x_reconnect_attempts: 3
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        result_cache_driver:
            type: memcache
            host: "%server1.memcache_host%"
            port: "%server1.memcache_port%"
            instance_class: Memcache
        query_cache_driver:
            type: memcache
            host: "%server1.memcache_host%"
            port: "%server1.memcache_port%"
            instance_class: Memcache
        metadata_cache_driver:
            type: memcache
            host: "%server1.memcache_host%"
            port: "%server1.memcache_port%"
            instance_class: Memcache

doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options:
                authMechanism: SCRAM-SHA-1
                connect:       true
                ssl:           true
                password:      "%mongodb_password%"
                username:      "%mongodb_username%"
                readPreference:   secondaryPreferred
    default_database: 'ws_call_%kernel.environment%'
    document_managers:
        default:
            auto_mapping: true
            retry_connect: 4
            retry_query:   4

cache_adapter:
    providers:
        default_memcache_adapter:
            factory: 'cache.factory.memcache'
            options:
                host: "%server1.memcache_host%"
                port: "%server1.memcache_port%"
            aliases: ['memcache.default']

monolog:
    channels: [console, mongodb, wsclient]
    handlers:
        error:
            type: fingers_crossed
            action_level: error
            handler: error_handler
            channels: ['!translation']
        error_handler:
            type: group
            members: [error_file]
#            members: [file_error, slack_error]
        error_file:
            type: rotating_file
            level: info
            path: "%kernel.logs_dir%/error.%kernel.environment%.log"
            max_files: 90
            date_format: 'Y-m-d'
            file_permission: 0664
#        slack_error:
#            type: slack
#            level: error
#            token: xoxb-54621264262-6EXEn7g59rpWe7vDxzHht5z5
#            channel: '#it-releases'
#            bot_name: 'Symfony Bot'

        console_filter:
            type: filter
            handler: console_handler
            max_level: warning
            channels: console
        console_handler:
            type: group
            members: [console_file, console_console]
        console_file:
            type: rotating_file
            path: "%kernel.logs_dir%/console.%kernel.environment%.log"
            level: info
            max_files: 90
            file_permission: 0664
            date_format: 'Y-m-d'
        console_console:
            type: console

        site_filter:
            type: filter
            handler: site_handler
            max_level: warning
            channels: ['!console', '!translation', '!mongodb', '!wsclient']
        site_handler:
            type: rotating_file
            level: warning
            path: "%kernel.logs_dir%/site.%kernel.environment%.log"
            max_files: 90
            file_permission: 0664
            date_format: 'Y-m-d'

        mongodb:
            type: fingers_crossed
            action_level: warning
            handler: mongodb_handler
            channels: mongodb
        mongodb_handler:
            type: rotating_file
            level: debug
            path: "%kernel.logs_dir%/mongodb.%kernel.environment%.log"
            max_files: 90
            file_permission: 0664
            date_format: 'Y-m-d'

        wsclient:
            type: fingers_crossed
            action_level: warning
            handler: wsclient_handler
            channels : wsclient
        wsclient_handler:
            type: rotating_file
            level: debug
            path: "%kernel.logs_dir%/wsclient.%kernel.environment%.log"
            max_files: 90
            file_permission: 0664
            date_format : 'Y-m-d'

swiftmailer:
    transport: '%mailer_transport%'

unilend_translation:
    parameters:
        cache:
            path: "%kernel.cache_dir%/translations"

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Unilend\Bundle\FrontBundle\Twig\IntlExtension
        tags:
            - { name: twig.extension }

google_tag_manager:
    enabled: true
    id: "%gtm_token%"
    autoAppend: false

sonata_seo:
    encoding: UTF-8
    page:
        title: 'Unilend : les particuliers prêtent aux entreprises françaises'
        default: sonata.seo.page.default
        metas:
            name:
                keywords: 'Prêter Emprunter'
                description: 'Sur Unilend, tout le monde peut prêter aux entreprises françaises et recevoir des intérêts.'
                robots: 'index, follow'
                viewport: 'width=device-width, initial-scale=1'

            http-equiv:
                'Content-Type': 'text/html; charset=utf-8'
                'X-UA-Compatible': 'IE=edge,chrome=1;'

knp_snappy:
    pdf:
        enabled: true
        binary: /usr/local/bin/wkhtmltopdf
        options:
            - { name: 'page-size', value: 'A4' }
            - { name: 'encoding', value : 'UTF-8'}

ekino_new_relic:
    enabled: false

sonata_cache:
    caches:
        symfony:
            token: ddb80e7065db6ecee2f3768704d
            php_cache_enabled: true
            types: [translations]
            servers: "%sonata_cache.servers%"

knp_mailjet:
    api_key:    "%mailjet.api_key%"
    secret_key: "%mailjet.api_secret%"
    event_endpoint_token: yclrcchxk0p3lujy82

guzzle:
    clients:
        euler:
            base_url: "%euler.url%"
            options:
                timeout: 16
                http_errors: false

        codinf:
            base_url: "%codinf.url%"
            options:
                http_errors: false

        infolegale:
            base_url: "%infolegale.url%"
            options:
                http_errors: false
        ellisphere:
            base_url: "%ellisphere.url%"
            options:
                http_errors: false

jms_serializer:
    enable_short_alias: false

cl_slack:
    api_token: "%slack.token%"
    test:      false
