imports:
    - { resource: config.yml }

swiftmailer:
    spool:
        type: db

ekino_new_relic:
    enabled: true
    application_name: "%new_relic.front_app_name%"
    deployment_names: ~
    api_key: edc37da0a36bfd74eded96d4d454c8f7b4b0ab8d4bce97e
    xmit: false
    logging: false
    instrument: true
    log_exceptions: false
    log_commands: true
    using_symfony_cache: true
    transaction_naming: route
    transaction_naming_service: ~
    ignored_routes: []
    ignored_paths: []
    ignored_commands: []

doctrine:
    dbal:
        connections:
            default:
                options:
                    !php/const:PDO::MYSQL_ATTR_SSL_KEY: %database_ssl_key%
                    !php/const:PDO::MYSQL_ATTR_SSL_CERT: %database_ssl_cert%
                    !php/const:PDO::MYSQL_ATTR_SSL_CA: %database_ssl_ca%
            console:
                options:
                    !php/const:PDO::MYSQL_ATTR_SSL_KEY: %database_ssl_key%
                    !php/const:PDO::MYSQL_ATTR_SSL_CERT: %database_ssl_cert%
                    !php/const:PDO::MYSQL_ATTR_SSL_CA: %database_ssl_ca%
