imports:
    - { resource: parameters.yml }

framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    default_locale:  "%locale%"
    templating:
        engines: ['twig']
    assets:
        base_urls:
            - "https://%router.request_context.host%"
    translator:
        enabled: true
        fallbacks: ["fr_FR"]
        paths:
            - "%kernel.root_dir%/../src/Unilend/Bundle/TranslationBundle/Resources/translations"
        logging : true

# Twig Configuration
twig:
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../src/Unilend/Bundle/FrontBundle/Resources/views" : UnilendFrontBundle
    exception_controller:  UnilendFrontBundle:Compatibility:dispatch

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles: [UnilendFrontBundle]
    write_to: '%kernel.root_dir%/../public'
    read_from : '%kernel.root_dir%/../public/bundles/unilendfront'
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  "UTF8"
                wrapper_class: Unilend\Bridge\Doctrine\DBAL\Connection
    orm:
        result_cache_driver:
            type: memcache
            host: "%server1.memcache_host%"
            port: "%server1.memcache_port%"
            instance_class: Memcache
        query_cache_driver:
            type: memcache
            host: "%server1.memcache_host%"
            port: "%server1.memcache_port%"
            instance_class: Memcache

cache_adapter:
    providers:
        default_memcache_adapter:
            factory: 'cache.factory.memcache'
            options:
                host: "%server1.memcache_host%"
                port: "%server1.memcache_port%"
            aliases: ['memcache.default']

monolog:
    channels: [console]
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            max_files: 10
            channels: ['!console']
        console:
            type: stream
            path: "%kernel.logs_dir%/console-%kernel.environment%.log"
            path: info
            max_files: 10
            channels: [console]

swiftmailer:
    transport: '%mailer_transport%'