unilend_front:
    resource: '../../src/Controller/'
    type:     annotation

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

_knp_mailjet:
    path:  /ws/mailjet/notify/{token}
    defaults: { _controller: knp_mailjet.event.controller:handleEventAction, token: null }
