services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $consoleLogger: '@monolog.logger.console'
            $wsClientCallLogger: '@monolog.logger.wsclient'
            $defaultLocale: '%locale%'
            $sharedTemporaryPath: '%path.shared_tmp%'
            $templateMessageFQCN: 'Unilend\SwiftMailer\TemplateMessage'
            $frontUrl: '%router.request_context.scheme%://%url.host_default%'
            $adminUrl: '%router.request_context.scheme%://%url.host_admin%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Unilend\:
        resource: '%kernel.project_dir%/src/*'
        # The directory Unilend contains the legacy bundles. The services are managed by their own configurations.
        exclude: '%kernel.project_dir%/src/{Console,Entity,Migrations,Tests,Unilend,Kernel.php}'

    # Define the memcache adaptor as the application default cache globally in order to have the right adaptor when autowiring Psr\Cache\CacheItemPoolInterface
    # Since we use the cache/adapter-bundle as the cache system, the configuration framework.cache.app won't work.
    # It can be removed once TECH-333 will be done.
    cache.app: '@memcache.default'
    # Define the logger service as public so we can continue to have access to it via $container->get().
    # But $container->get('logger') is deprecated, do not use it any more.
    logger:
        alias: 'monolog.logger'
        public: true

    Mailjet\Client:
        $key: '%mailjet.api_key%'
        $secret: '%mailjet.api_secret%'
        $call: true
        $settings:
            version: '%mailjet.api_version%'

    # Swift Mailer and its bridges
    swiftmailer.spool.db: '@Unilend\SwiftMailer\DatabaseSpool'
    swiftmailer.mailer.default.spool.db: '@Unilend\SwiftMailer\DatabaseSpool'
    swiftmailer.mailer.transport.mailjet: '@Unilend\SwiftMailer\MailjetTransport'
    mailjet: '@Unilend\SwiftMailer\MailjetTransport'

    Unilend\Service\Translation\TranslationLoader:
        tags:
            - { name: translation.loader, alias: db }

    Unilend\Service\WebServiceClient\CallHistoryManager:
        arguments:
            $alertChannel: '%slack.default_channel%'
            $mongoDBLogger: '@monolog.logger.mongodb'
            $mongoLogEnabled: "%mongodb.log.enable%"

    soap_client.altares_identity:
        class: \SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_identity%'
            $options:
                exception: 1
                trace: 1

    soap_client.altares_risque:
        class: \SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_risk%'
            $options:
                exception: 1
                trace: 1

    soap_client.altares_risk_monitoring:
        class: \SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_risk_monitoring%'
            $options:
                exception: 1
                trace: 1

    Unilend\Service\WebServiceClient\EulerHermesManager:
        $client: '@eight_points_guzzle.client.euler'
        $gradingApiKey: '%euler.grading_key%'
        $accountApiKey: '%euler.account_key%'
        $accountPassword: '%euler.password%'
        $accountEmail: '%euler.email%'

    Unilend\Service\WebServiceClient\CodinfManager:
        $client: '@eight_points_guzzle.client.codinf'
        $user: '%codinf.user%'
        $password: '%codinf.password%'

    Unilend\Service\WebServiceClient\InfolegaleManager:
        $client: '@eight_points_guzzle.client.infolegale'
        $token: '%infolegale.token%'

    Unilend\Service\WebServiceClient\InfogreffeManager:
        $login: '%infogreffe.login%'
        $password: '%infogreffe.password%'
        $wsdl: '%infogreffe.wsdl_url%'
        $url: '%infogreffe.url%'

    Unilend\Service\WebServiceClient\AltaresManager:
        $login: '%altares.login%'
        $password: '%altares.password%'
        $identityClient: '@soap_client.altares_identity'
        $riskClient: '@soap_client.altares_risque'
        $riskMonitoringClient: '@soap_client.altares_risk_monitoring'

    Unilend\Service\WebServiceClient\EllisphereManager:
        $client: '@eight_points_guzzle.client.ellisphere'
        $contractId: '%ellisphere.contract_id%'
        $userPrefix: '%ellisphere.user_prefix%'
        $userId: '%ellisphere.user_id%'
        $password: '%ellisphere.password%'

    Unilend\Service\WebServiceClient\GreenPointManager:
        $client: '@eight_points_guzzle.client.greenpoint'
        $login: '%greenpoint.login%'
        $password: '%greenpoint.password%'

    Unilend\Service\WebServiceClient\InseeManager:
        $client: '@eight_points_guzzle.client.insee'
