services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # aliases so that the old service ids can still be accessed
    # remove these if/when you are not fetching these directly
    # from the container via $container->get()
    Unilend\Bundle\FrontBundle\Service\LenderLoansDisplayManager:
        public: true

    Unilend\Bundle\FrontBundle\Service\LenderProfileFormsHandler:
        public: true
