services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $rootDir: '%kernel.root_dir%'

    # makes classes in the bundle available to be used as services
    # nothing to exclude for front bundle
    # this creates a service per class whose id is the fully-qualified class name (FQCN)
    Unilend\Bundle\FrontBundle\:
        resource: '%kernel.project_dir%/src/Unilend/Bundle/FrontBundle/*'

    Unilend\Bundle\FrontBundle\Security\BCryptPasswordEncoder:
        $cost: '%security.bcrypt.cost%'

    Unilend\Bundle\FrontBundle\Service\UniversignManager:
        $universignURL: '%url.universign%'

    Twig\Extensions\TextExtension: ~
