monolog:
    handlers:
        site_handler:
            type: stream
            level: info
            path: "%kernel.logs_dir%/site.%kernel.environment%.log"

        null_support:
            type: 'null'
            level: debug
            priority: 50
            channels: ['support']
