monolog:
    handlers:
        site_handler:
            type: stream
            level: info
            path: "%kernel.logs_dir%/site.%kernel.environment%.log"

        wsclient:
            type: fingers_crossed
            action_level: info
            handler: wsclient_handler
            channels: wsclient
        wsclient_handler:
            type: stream
            level: info
            path: "%kernel.logs_dir%/wsclient.%kernel.environment%.log"
