swiftmailer:
    default_mailer: normal
    mailers:
        normal:
            transport: 'smtp'
            url: '%env(MAILER_URL)%'
        fast:
            transport: 'smtp'
            url: '%env(MAILER_URL)%'
