<?php

declare(strict_types=1);

namespace Unilend\Security\Voter;

use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Unilend\Entity\Clients;
use Unilend\Entity\ProjectOrganizer;

class ProjectOrganizerVoter extends AbstractEntityVoter
{
    public const ATTRIBUTE_DELETE = 'delete';
    public const ATTRIBUTE_CREATE = 'create';
    public const ATTRIBUTE_EDIT   = 'edit';

    /** @var AuthorizationCheckerInterface */
    private $authorizationChecker;

    /**
     * @param AuthorizationCheckerInterface $authorizationChecker
     */
    public function __construct(AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }

    /**
     * @param ProjectOrganizer $subject
     * @param Clients          $user
     *
     * @return bool
     */
    protected function fulfillPreconditions($subject, Clients $user): bool
    {
        return $this->authorizationChecker->isGranted(ProjectVoter::ATTRIBUTE_EDIT, $subject->getProject()); // TODO: Change the autogenerated stub
    }

    /**
     * @param ProjectOrganizer $subject
     *
     * @return bool
     */
    protected function canCreate(ProjectOrganizer $subject)
    {
        return true;
    }

    /**
     * @param ProjectOrganizer $subject
     *
     * @return bool
     */
    protected function canDelete(ProjectOrganizer $subject): bool
    {
        return $subject->hasRole(ProjectOrganizer::DUTY_PROJECT_ORGANIZER_ARRANGER);
    }

    /**
     * @param ProjectOrganizer $subject
     *
     * @return bool
     */
    protected function canEdit(ProjectOrganizer $subject): bool
    {
        return $subject->hasRole(ProjectOrganizer::DUTY_PROJECT_ORGANIZER_ARRANGER);
    }
}
