#!/bin/bash

#we deloy when we push somthing only in branch develop
branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $branch == 'develop' ]
then
	current_time=$(date "+%Y.%m.%d-%H.%M.%S")
	logFileName='deployment'.$current_time.'log'
	/usr/bin/phploy.phar -s dev > log/$logFileName
fi