<?php

declare(strict_types=1);

namespace KLS\Test\CreditGuaranty\FEI\DataFixtures;

use Doctrine\Persistence\ObjectManager;
use KLS\Core\Entity\Company;
use KLS\CreditGuaranty\FEI\Entity\Borrower;
use KLS\CreditGuaranty\FEI\Entity\Field;
use KLS\CreditGuaranty\FEI\Entity\FinancingObject;
use KLS\CreditGuaranty\FEI\Entity\Program;
use KLS\CreditGuaranty\FEI\Entity\Project;
use KLS\Test\Core\DataFixtures\AbstractFixtures;

class FieldFixtures extends AbstractFixtures
{
    public function load(ObjectManager $manager): void
    {
        foreach ($this->loadData() as $reference => $fieldData) {
            $field = new Field(
                $fieldData['fieldAlias'],
                $fieldData['tag'],
                $fieldData['category'],
                $fieldData['type'],
                $fieldData['reservationPropertyName'],
                $fieldData['propertyPath'],
                $fieldData['propertyType'],
                $fieldData['objectClass'],
                $fieldData['comparable'],
                $fieldData['unit'],
                $fieldData['predefinedItems']
            );

            $this->setPublicId($field, $reference);
            $this->addReference($reference, $field);

            $manager->persist($field);
        }

        $manager->flush();
    }

    private function loadData(): iterable
    {
        yield 'field-beneficiary_name' => [
            'fieldAlias'              => 'beneficiary_name',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'beneficiaryName',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-borrower_type' => [
            'fieldAlias'              => 'borrower_type',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'list',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'borrowerType',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-young_farmer' => [
            'fieldAlias'              => 'young_farmer',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'youngFarmer',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-creation_in_progress' => [
            'fieldAlias'              => 'creation_in_progress',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'creationInProgress',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-subsidiary' => [
            'fieldAlias'              => 'subsidiary',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'subsidiary',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-company_name' => [
            'fieldAlias'              => 'company_name',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'companyName',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-activity_street' => [
            'fieldAlias'              => 'activity_street',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressStreet',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-activity_post_code' => [
            'fieldAlias'              => 'activity_post_code',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressPostCode',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-activity_city' => [
            'fieldAlias'              => 'activity_city',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressCity',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-activity_department' => [
            'fieldAlias'              => 'activity_department',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'list',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressDepartment',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-activity_country' => [
            'fieldAlias'              => 'activity_country',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'list',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressCountry',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-activity_start_date' => [
            'fieldAlias'              => 'activity_start_date',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'activityStartDate',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-siret' => [
            'fieldAlias'              => 'siret',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'siret',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-tax_number' => [
            'fieldAlias'              => 'tax_number',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'taxNumber',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-legal_form' => [
            'fieldAlias'              => 'legal_form',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'list',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'legalForm',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => ['SARL', 'SAS', 'SASU', 'EURL', 'SA', 'SELAS'],
        ];
        yield 'field-company_naf_code' => [
            'fieldAlias'              => 'company_naf_code',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'companyNafCode',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-employees_number' => [
            'fieldAlias'              => 'employees_number',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'employeesNumber',
            'propertyType'            => 'int',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => 'person',
            'predefinedItems'         => null,
        ];
        yield 'field-exploitation_size' => [
            'fieldAlias'              => 'exploitation_size',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'exploitationSize',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-turnover' => [
            'fieldAlias'              => 'turnover',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'turnover',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-total_assets' => [
            'fieldAlias'              => 'total_assets',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'totalAssets',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-receiving_grant' => [
            'fieldAlias'              => 'receiving_grant',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'bool',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'receivingGrant',
            'propertyType'            => 'bool',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-investment_street' => [
            'fieldAlias'              => 'investment_street',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressStreet',
            'propertyType'            => 'string',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-investment_post_code' => [
            'fieldAlias'              => 'investment_post_code',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressPostCode',
            'propertyType'            => 'string',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-investment_city' => [
            'fieldAlias'              => 'investment_city',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressCity',
            'propertyType'            => 'string',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-investment_department' => [
            'fieldAlias'              => 'investment_department',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressDepartment',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-investment_country' => [
            'fieldAlias'              => 'investment_country',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressCountry',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-investment_thematic' => [
            'fieldAlias'              => 'investment_thematic',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'investmentThematic',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-investment_type' => [
            'fieldAlias'              => 'investment_type',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'investmentType',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-aid_intensity' => [
            'fieldAlias'              => 'aid_intensity',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'aidIntensity',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'percentage',
            'predefinedItems'         => null,
        ];
        yield 'field-additional_guaranty' => [
            'fieldAlias'              => 'additional_guaranty',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'additionalGuaranty',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-agricultural_branch' => [
            'fieldAlias'              => 'agricultural_branch',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'agriculturalBranch',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-project_total_amount' => [
            'fieldAlias'              => 'project_total_amount',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'fundingMoney',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-project_contribution' => [
            'fieldAlias'              => 'project_contribution',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'contribution',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-eligible_fei_credit' => [
            'fieldAlias'              => 'eligible_fei_credit',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'eligibleFeiCredit',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-total_fei_credit' => [
            'fieldAlias'              => 'total_fei_credit',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'totalFeiCredit',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-tangible_fei_credit' => [
            'fieldAlias'              => 'tangible_fei_credit',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'tangibleFeiCredit',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-intangible_fei_credit' => [
            'fieldAlias'              => 'intangible_fei_credit',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'intangibleFeiCredit',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-credit_excluding_fei' => [
            'fieldAlias'              => 'credit_excluding_fei',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'creditExcludingFei',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-project_grant' => [
            'fieldAlias'              => 'project_grant',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'grant',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-land_value' => [
            'fieldAlias'              => 'land_value',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'landValue',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-supporting_generations_renewal' => [
            'fieldAlias'              => 'supporting_generations_renewal',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'bool',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'supportingGenerationsRenewal',
            'propertyType'            => 'bool',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-financing_object_type' => [
            'fieldAlias'              => 'financing_object_type',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'list',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'financingObjectType',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-loan_naf_code' => [
            'fieldAlias'              => 'loan_naf_code',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'list',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanNafCode',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-bfr_value' => [
            'fieldAlias'              => 'bfr_value',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'bfrValue',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-loan_type' => [
            'fieldAlias'              => 'loan_type',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'list',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanType',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => ['term_loan', 'short_term', 'revolving_credit', 'stand_by', 'signature_commitment'],
        ];
        yield 'field-loan_money' => [
            'fieldAlias'              => 'loan_money',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanMoney',
            'propertyType'            => 'Money',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield 'field-loan_duration' => [
            'fieldAlias'              => 'loan_duration',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanDuration',
            'propertyType'            => 'int',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'month',
            'predefinedItems'         => null,
        ];
        yield 'field-loan_deferral' => [
            'fieldAlias'              => 'loan_deferral',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanDeferral',
            'propertyType'            => 'int',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'month',
            'predefinedItems'         => null,
        ];
        yield 'field-loan_periodicity' => [
            'fieldAlias'              => 'loan_periodicity',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'list',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanPeriodicity',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'month',
            'predefinedItems'         => ['monthly', 'quarterly', 'semi_annually', 'annually'],
        ];
        yield 'field-investment_location' => [
            'fieldAlias'              => 'investment_location',
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'investmentLocation',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-program_currency' => [
            'fieldAlias'              => 'program_currency',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'other',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'funds.currency',
            'propertyType'            => 'string',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-guaranty_duration' => [
            'fieldAlias'              => 'guaranty_duration',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'other',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'guarantyDuration',
            'propertyType'            => 'int',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-esb_calculation_activated' => [
            'fieldAlias'              => 'esb_calculation_activated',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'bool',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'esbCalculationActivated',
            'propertyType'            => 'bool',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-loan_released_on_invoice' => [
            'fieldAlias'              => 'loan_released_on_invoice',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'bool',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'loanReleasedOnInvoice',
            'propertyType'            => 'bool',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-max_fei_credit' => [
            'fieldAlias'              => 'max_fei_credit',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'other',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'maxFeiCredit',
            'propertyType'            => 'NullableMoney',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-rating_model' => [
            'fieldAlias'              => 'rating_model',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'other',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'ratingModel',
            'propertyType'            => 'string',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-reservation_name' => [
            'fieldAlias'              => 'reservation_name',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'name',
            'propertyPath'            => '',
            'propertyType'            => 'string',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-reservation_status' => [
            'fieldAlias'              => 'reservation_status',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'currentStatus',
            'propertyPath'            => '',
            'propertyType'            => 'int',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-reservation_creation_date' => [
            'fieldAlias'              => 'reservation_creation_date',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'added',
            'propertyPath'            => '',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-reservation_refusal_date' => [
            'fieldAlias'              => 'reservation_refusal_date',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'refusedByManagingCompanyDate',
            'propertyPath'            => '',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-reservation_signing_date' => [
            'fieldAlias'              => 'reservation_signing_date',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'signingDate',
            'propertyPath'            => '',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-reservation_managing_company' => [
            'fieldAlias'              => 'reservation_managing_company',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'managingCompany',
            'propertyPath'            => 'displayName',
            'propertyType'            => 'string',
            'objectClass'             => Company::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-borrower_type_grade' => [
            'fieldAlias'              => 'borrower_type_grade',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'grade',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-project_detail' => [
            'fieldAlias'              => 'project_detail',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'detail',
            'propertyType'            => 'string',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-financing_object_name' => [
            'fieldAlias'              => 'financing_object_name',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'name',
            'propertyType'            => 'string',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-loan_money_after_contract' => [ // need the reference to be shorter because reference is set as publicId and publicId has limit
            'fieldAlias'              => 'loan_money_after_contractualisation',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanMoneyAfterContractualisation',
            'propertyType'            => 'Money',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-main_loan' => [
            'fieldAlias'              => 'main_loan',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'bool',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'mainLoan',
            'propertyType'            => 'bool',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-loan_number' => [
            'fieldAlias'              => 'loan_number',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanNumber',
            'propertyType'            => 'string',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-loan_operation_number' => [
            'fieldAlias'              => 'loan_operation_number',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'operationNumber',
            'propertyType'            => 'string',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-first_release_date' => [
            'fieldAlias'              => 'first_release_date',
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'firstReleaseDate',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-loan_new_maturity' => [
            'fieldAlias'              => 'loan_new_maturity',
            'tag'                     => Field::TAG_IMPORTED,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'newMaturity',
            'propertyType'            => 'int',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-loan_remaining_capital' => [
            'fieldAlias'              => 'loan_remaining_capital',
            'tag'                     => Field::TAG_IMPORTED,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'remainingCapital',
            'propertyType'            => 'NullableMoney',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield 'field-total_gross_subsidy_equivalent' => [
            'fieldAlias'              => 'total_gross_subsidy_equivalent',
            'tag'                     => Field::TAG_CALCUL,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'totalGrossSubsidyEquivalent',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
    }
}
