<?php

declare(strict_types=1);

namespace KLS\Test\CreditGuaranty\FEI\DataFixtures;

use Doctrine\Persistence\ObjectManager;
use KLS\Core\Entity\Company;
use KLS\CreditGuaranty\FEI\Entity\Borrower;
use KLS\CreditGuaranty\FEI\Entity\Constant\FieldAlias;
use KLS\CreditGuaranty\FEI\Entity\Field;
use KLS\CreditGuaranty\FEI\Entity\FinancingObject;
use KLS\CreditGuaranty\FEI\Entity\Program;
use KLS\CreditGuaranty\FEI\Entity\Project;
use KLS\Test\Core\DataFixtures\AbstractFixtures;

class FieldFixtures extends AbstractFixtures
{
    public function load(ObjectManager $manager): void
    {
        foreach ($this->loadData() as $fieldAlias => $fieldData) {
            $field = new Field(
                $fieldData['fieldAlias'],
                $fieldData['tag'],
                $fieldData['category'],
                $fieldData['type'],
                $fieldData['reservationPropertyName'],
                $fieldData['propertyPath'],
                $fieldData['propertyType'],
                $fieldData['objectClass'],
                $fieldData['comparable'],
                $fieldData['unit'],
                $fieldData['predefinedItems']
            );

            $this->setPublicId($field, $fieldAlias);
            $this->addReference($fieldAlias, $field);

            $manager->persist($field);
        }

        $manager->flush();
    }

    private function loadData(): iterable
    {
        yield FieldAlias::BENEFICIARY_NAME => [
            'fieldAlias'              => FieldAlias::BENEFICIARY_NAME,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'beneficiaryName',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::BORROWER_TYPE => [
            'fieldAlias'              => FieldAlias::BORROWER_TYPE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'list',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'borrowerType',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::YOUNG_FARMER => [
            'fieldAlias'              => FieldAlias::YOUNG_FARMER,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'youngFarmer',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::CREATION_IN_PROGRESS => [
            'fieldAlias'              => FieldAlias::CREATION_IN_PROGRESS,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'creationInProgress',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::SUBSIDIARY => [
            'fieldAlias'              => FieldAlias::SUBSIDIARY,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'subsidiary',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ECONOMICALLY_VIABLE => [
            'fieldAlias'              => FIEldAlias::ECONOMICALLY_VIABLE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'economicallyViable',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        // this reference needs to be shorter because reference is set as publicId and publicId has a character limit
        yield 'loan_dates_after_application_date' => [
            'fieldAlias'              => FieldAlias::LOAN_SUPPORTING_DOCUMENTS_DATES_AFTER_APPLICATION,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'loanSupportingDocumentsDatesAfterApplication',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::BENEFITING_PROFIT_TRANSFER => [
            'fieldAlias'              => FieldAlias::BENEFITING_PROFIT_TRANSFER,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'benefitingProfitTransfer',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_ALLOWED_REFINANCE_RESTRUCTURE => [
            'fieldAlias'              => FieldAlias::LOAN_ALLOWED_REFINANCE_RESTRUCTURE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'loanAllowedRefinanceRestructure',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::PROJECT_RECEIVED_FEAGA_OCM_FUNDING => [
            'fieldAlias'              => FieldAlias::PROJECT_RECEIVED_FEAGA_OCM_FUNDING,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'projectReceivedFeagaOcmFunding',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LISTED_ON_STOCK_MARKET => [
            'fieldAlias'              => FIELDAlias::LISTED_ON_STOCK_MARKET,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'listedOnStockMarket',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        // this reference needs to be shorter because reference is set as publicId and publicId has a character limit
        yield 'subject_unperformed_recovery_order' => [
            'fieldAlias'              => FieldAlias::SUBJECT_OF_UNPERFORMED_RECOVERY_ORDER,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'subjectOfUnperformedRecoveryOrder',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::SUBJECT_OF_RESTRUCTURING_PLAN => [
            'fieldAlias'              => FieldAlias::SUBJECT_OF_RESTRUCTURING_PLAN,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'subjectOfRestructuringPlan',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::IN_NON_COOPERATIVE_JURISDICTION => [
            'fieldAlias'              => FieldAlias::IN_NON_COOPERATIVE_JURISDICTION,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'inNonCooperativeJurisdiction',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::TRANSACTION_AFFECTED => [
            'fieldAlias'              => FieldAlias::TRANSACTION_AFFECTED,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'bool',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'transactionAffected',
            'propertyType'            => 'bool',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::COMPANY_NAME => [
            'fieldAlias'              => FieldAlias::COMPANY_NAME,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'companyName',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ACTIVITY_STREET => [
            'fieldAlias'              => FieldAlias::ACTIVITY_STREET,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressStreet',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ACTIVITY_POST_CODE => [
            'fieldAlias'              => FieldAlias::ACTIVITY_POST_CODE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressPostCode',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ACTIVITY_CITY => [
            'fieldAlias'              => FieldAlias::ACTIVITY_CITY,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressCity',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ACTIVITY_DEPARTMENT => [
            'fieldAlias'              => FieldAlias::ACTIVITY_DEPARTMENT,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'list',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressDepartment',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ACTIVITY_COUNTRY => [
            'fieldAlias'              => FieldAlias::ACTIVITY_COUNTRY,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'list',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'addressCountry',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ACTIVITY_START_DATE => [
            'fieldAlias'              => FieldAlias::ACTIVITY_START_DATE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'activityStartDate',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::REGISTRATION_NUMBER => [
            'fieldAlias'              => FieldAlias::REGISTRATION_NUMBER,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'registrationNumber',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LEGAL_FORM => [
            'fieldAlias'              => FieldAlias::LEGAL_FORM,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'list',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'legalForm',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::COMPANY_NAF_CODE => [
            'fieldAlias'              => FieldAlias::COMPANY_NAF_CODE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'companyNafCode',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::EMPLOYEES_NUMBER => [
            'fieldAlias'              => FieldAlias::EMPLOYEES_NUMBER,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'employeesNumber',
            'propertyType'            => 'int',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => 'person',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::EXPLOITATION_SIZE => [
            'fieldAlias'              => FieldAlias::EXPLOITATION_SIZE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'exploitationSize',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::TURNOVER => [
            'fieldAlias'              => FieldAlias::TURNOVER,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'turnover',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::TOTAL_ASSETS => [
            'fieldAlias'              => FieldAlias::TOTAL_ASSETS,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'totalAssets',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::TARGET_TYPE => [
            'fieldAlias'              => FieldAlias::TARGET_TYPE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'profile',
            'type'                    => 'list',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'targetType',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Borrower::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::RECEIVING_GRANT => [
            'fieldAlias'              => FieldAlias::RECEIVING_GRANT,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'bool',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'receivingGrant',
            'propertyType'            => 'bool',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::INVESTMENT_STREET => [
            'fieldAlias'              => FieldAlias::INVESTMENT_STREET,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressStreet',
            'propertyType'            => 'string',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::INVESTMENT_POST_CODE => [
            'fieldAlias'              => FieldAlias::INVESTMENT_POST_CODE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressPostCode',
            'propertyType'            => 'string',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::INVESTMENT_CITY => [
            'fieldAlias'              => FieldAlias::INVESTMENT_CITY,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressCity',
            'propertyType'            => 'string',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::INVESTMENT_DEPARTMENT => [
            'fieldAlias'              => FieldAlias::INVESTMENT_DEPARTMENT,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressDepartment',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::INVESTMENT_COUNTRY => [
            'fieldAlias'              => FieldAlias::INVESTMENT_COUNTRY,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'addressCountry',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::INVESTMENT_THEMATIC => [
            'fieldAlias'              => FieldAlias::INVESTMENT_THEMATIC,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'investmentThematics',
            'propertyType'            => 'Collection',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::INVESTMENT_TYPE => [
            'fieldAlias'              => FieldAlias::INVESTMENT_TYPE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'investmentType',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::AID_INTENSITY => [
            'fieldAlias'              => FieldAlias::AID_INTENSITY,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'aidIntensity',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'percentage',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ADDITIONAL_GUARANTY => [
            'fieldAlias'              => FieldAlias::ADDITIONAL_GUARANTY,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'additionalGuaranty',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::AGRICULTURAL_BRANCH => [
            'fieldAlias'              => FieldAlias::AGRICULTURAL_BRANCH,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'list',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'agriculturalBranch',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::PROJECT_TOTAL_AMOUNT => [
            'fieldAlias'              => FieldAlias::PROJECT_TOTAL_AMOUNT,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'fundingMoney',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::PROJECT_CONTRIBUTION => [
            'fieldAlias'              => FieldAlias::PROJECT_CONTRIBUTION,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'contribution',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ELIGIBLE_FEI_CREDIT => [
            'fieldAlias'              => FieldAlias::ELIGIBLE_FEI_CREDIT,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'eligibleFeiCredit',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::TOTAL_FEI_CREDIT => [
            'fieldAlias'              => FieldAlias::TOTAL_FEI_CREDIT,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'totalFeiCredit',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::TANGIBLE_FEI_CREDIT => [
            'fieldAlias'              => FieldAlias::TANGIBLE_FEI_CREDIT,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'tangibleFeiCredit',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::INTANGIBLE_FEI_CREDIT => [
            'fieldAlias'              => FieldAlias::INTANGIBLE_FEI_CREDIT,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'intangibleFeiCredit',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::CREDIT_EXCLUDING_FEI => [
            'fieldAlias'              => FieldAlias::CREDIT_EXCLUDING_FEI,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'creditExcludingFei',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::PROJECT_GRANT => [
            'fieldAlias'              => FieldAlias::PROJECT_GRANT,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'grant',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LAND_VALUE => [
            'fieldAlias'              => FieldAlias::LAND_VALUE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'landValue',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::SUPPORTING_GENERATIONS_RENEWAL => [
            'fieldAlias'              => FieldAlias::SUPPORTING_GENERATIONS_RENEWAL,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'bool',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'supportingGenerationsRenewal',
            'propertyType'            => 'bool',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::FINANCING_OBJECT_TYPE => [
            'fieldAlias'              => FieldAlias::FINANCING_OBJECT_TYPE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'list',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'financingObjectType',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_NAF_CODE => [
            'fieldAlias'              => FieldAlias::LOAN_NAF_CODE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'list',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanNafCode',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::BFR_VALUE => [
            'fieldAlias'              => FieldAlias::BFR_VALUE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'bfrValue',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_TYPE => [
            'fieldAlias'              => FieldAlias::LOAN_TYPE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'list',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanType',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_MONEY => [
            'fieldAlias'              => FieldAlias::LOAN_MONEY,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanMoney',
            'propertyType'            => 'Money',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'money',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_DURATION => [
            'fieldAlias'              => FieldAlias::LOAN_DURATION,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanDuration',
            'propertyType'            => 'int',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'month',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_DEFERRAL => [
            'fieldAlias'              => FieldAlias::LOAN_DEFERRAL,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanDeferral',
            'propertyType'            => 'int',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'month',
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_PERIODICITY => [
            'fieldAlias'              => FieldAlias::LOAN_PERIODICITY,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'list',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanPeriodicity',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => 'month',
            'predefinedItems'         => ['monthly', 'quarterly', 'semi_annually', 'annually'],
        ];
        yield FieldAlias::INVESTMENT_LOCATION => [
            'fieldAlias'              => FieldAlias::INVESTMENT_LOCATION,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'investmentLocation',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::PRODUCT_CATEGORY_CODE => [
            'fieldAlias'              => FieldAlias::PRODUCT_CATEGORY_CODE,
            'tag'                     => Field::TAG_ELIGIBILITY,
            'category'                => 'loan',
            'type'                    => 'list',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'productCategoryCode',
            'propertyType'            => 'ProgramChoiceOption',
            'objectClass'             => FinancingObject::class,
            'comparable'              => true,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::PROGRAM_CURRENCY => [
            'fieldAlias'              => FieldAlias::PROGRAM_CURRENCY,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'other',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'funds.currency',
            'propertyType'            => 'string',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::PROGRAM_DURATION => [
            'fieldAlias'              => FieldAlias::PROGRAM_DURATION,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'other',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'guarantyDuration',
            'propertyType'            => 'int',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::ESB_CALCULATION_ACTIVATED => [
            'fieldAlias'              => FieldAlias::ESB_CALCULATION_ACTIVATED,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'bool',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'esbCalculationActivated',
            'propertyType'            => 'bool',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_RELEASED_ON_INVOICE => [
            'fieldAlias'              => FieldAlias::LOAN_RELEASED_ON_INVOICE,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'bool',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'loanReleasedOnInvoice',
            'propertyType'            => 'bool',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::MAX_FEI_CREDIT => [
            'fieldAlias'              => FieldAlias::MAX_FEI_CREDIT,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'other',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'maxFeiCredit',
            'propertyType'            => 'NullableMoney',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::RATING_MODEL => [
            'fieldAlias'              => FieldAlias::RATING_MODEL,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'program',
            'type'                    => 'other',
            'reservationPropertyName' => 'program',
            'propertyPath'            => 'ratingModel',
            'propertyType'            => 'string',
            'objectClass'             => Program::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::RESERVATION_NAME => [
            'fieldAlias'              => FieldAlias::RESERVATION_NAME,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'name',
            'propertyPath'            => '',
            'propertyType'            => 'string',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::RESERVATION_STATUS => [
            'fieldAlias'              => FieldAlias::RESERVATION_STATUS,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'currentStatus',
            'propertyPath'            => '',
            'propertyType'            => 'int',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::RESERVATION_CREATION_DATE => [
            'fieldAlias'              => FieldAlias::RESERVATION_CREATION_DATE,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'added',
            'propertyPath'            => '',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::RESERVATION_EXCLUSION_DATE => [
            'fieldAlias'              => FieldAlias::RESERVATION_EXCLUSION_DATE,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'refusedByManagingCompanyDate',
            'propertyPath'            => '',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::RESERVATION_SIGNING_DATE => [
            'fieldAlias'              => FieldAlias::RESERVATION_SIGNING_DATE,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'signingDate',
            'propertyPath'            => '',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => '',
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::RESERVATION_MANAGING_COMPANY => [
            'fieldAlias'              => FieldAlias::RESERVATION_MANAGING_COMPANY,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'reservation',
            'type'                    => 'other',
            'reservationPropertyName' => 'managingCompany',
            'propertyPath'            => 'displayName',
            'propertyType'            => 'string',
            'objectClass'             => Company::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::BORROWER_TYPE_GRADE => [
            'fieldAlias'              => FieldAlias::BORROWER_TYPE_GRADE,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'profile',
            'type'                    => 'other',
            'reservationPropertyName' => 'borrower',
            'propertyPath'            => 'grade',
            'propertyType'            => 'string',
            'objectClass'             => Borrower::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::PROJECT_DETAIL => [
            'fieldAlias'              => FieldAlias::PROJECT_DETAIL,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'detail',
            'propertyType'            => 'string',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::FINANCING_OBJECT_NAME => [
            'fieldAlias'              => FieldAlias::FINANCING_OBJECT_NAME,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'name',
            'propertyType'            => 'string',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        // this reference needs to be shorter because reference is set as publicId and publicId has a character limit
        yield 'loan_money_after_contract' => [
            'fieldAlias'              => FieldAlias::LOAN_MONEY_AFTER_CONTRACTUALISATION,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanMoneyAfterContractualisation',
            'propertyType'            => 'Money',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::MAIN_LOAN => [
            'fieldAlias'              => FieldAlias::MAIN_LOAN,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'bool',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'mainLoan',
            'propertyType'            => 'bool',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_NUMBER => [
            'fieldAlias'              => FieldAlias::LOAN_NUMBER,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'loanNumber',
            'propertyType'            => 'string',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_OPERATION_NUMBER => [
            'fieldAlias'              => FieldAlias::LOAN_OPERATION_NUMBER,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'operationNumber',
            'propertyType'            => 'string',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::FIRST_RELEASE_DATE => [
            'fieldAlias'              => FieldAlias::FIRST_RELEASE_DATE,
            'tag'                     => Field::TAG_INFO,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'firstReleaseDate',
            'propertyType'            => 'DateTimeImmutable',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_NEW_MATURITY => [
            'fieldAlias'              => FieldAlias::LOAN_NEW_MATURITY,
            'tag'                     => Field::TAG_IMPORTED,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'newMaturity',
            'propertyType'            => 'int',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::LOAN_REMAINING_CAPITAL => [
            'fieldAlias'              => FieldAlias::LOAN_REMAINING_CAPITAL,
            'tag'                     => Field::TAG_IMPORTED,
            'category'                => 'loan',
            'type'                    => 'other',
            'reservationPropertyName' => 'financingObjects',
            'propertyPath'            => 'remainingCapital',
            'propertyType'            => 'NullableMoney',
            'objectClass'             => FinancingObject::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
        yield FieldAlias::TOTAL_GROSS_SUBSIDY_EQUIVALENT => [
            'fieldAlias'              => FieldAlias::TOTAL_GROSS_SUBSIDY_EQUIVALENT,
            'tag'                     => Field::TAG_CALCUL,
            'category'                => 'project',
            'type'                    => 'other',
            'reservationPropertyName' => 'project',
            'propertyPath'            => 'totalGrossSubsidyEquivalent',
            'propertyType'            => 'MoneyInterface',
            'objectClass'             => Project::class,
            'comparable'              => false,
            'unit'                    => null,
            'predefinedItems'         => null,
        ];
    }
}
