services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Unilend\Bundle\CommandBundle\Command\:
        resource:  '../../Command'

    ekino.new_relic.console:
        class: Ekino\Bundle\NewRelicBundle\NewRelic\NewRelic
        arguments:
            -
            -
            -
            -
            - []
        public: true
