services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $logger: '@monolog.logger.console'

    Unilend\Bundle\CommandBundle\:
        resource: '%kernel.project_dir%/src/Unilend/Bundle/CommandBundle/*'
