services:
    Unilend\Bundle\CommandBundle\Command\:
        resource:  '../../Command'
        tags: ['console.command']
        public: true

    ekino.new_relic.console:
        class: Ekino\Bundle\NewRelicBundle\NewRelic\NewRelic
        arguments:
            -
            -
            -
            -
            - []
        public: true
