doctrine:
    orm:
        result_cache_driver:
            type: memcache
            host: "%server1.memcache_host%"
            port: "%server1.memcache_port%"
            instance_class: Memcache
        query_cache_driver:
            type: memcache
            host: "%server1.memcache_host%"
            port: "%server1.memcache_port%"
            instance_class: Memcache
        metadata_cache_driver:
            type: memcache
            host: "%server1.memcache_host%"
            port: "%server1.memcache_port%"
            instance_class: Memcache
#    dbal:
#        connections:
#            default:
#                options:
#                    !php/const:PDO::MYSQL_ATTR_SSL_KEY: %env(DATABASE_SSL_KEY)%
#                    !php/const:PDO::MYSQL_ATTR_SSL_CERT: %env(DATABASE_SSL_CER)T%
#                    !php/const:PDO::MYSQL_ATTR_SSL_CA: %env(DATABASE_SSL_CA)%
#            migration:
#                options:
#                    !php/const:PDO::MYSQL_ATTR_SSL_KEY: %env(DATABASE_SSL_KEY)%
#                    !php/const:PDO::MYSQL_ATTR_SSL_CERT: %env(DATABASE_SSL_CERT)%
#                    !php/const:PDO::MYSQL_ATTR_SSL_CA: %env(DATABASE_SSL_CA)%
