imports:
    - { resource: parameters.yml }
    - { resource: services.xml }
    - { resource: events.xml }
    - { resource: commands.xml }

framework:
    secret: "%secret%"
    default_locale:  "%locale%"
    assets:
        base_urls:
            - "https://%router.request_context.host%"

doctrine:
    dbal:
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  "UTF8"
                wrapper_class: Unilend\Library\Bridge\Doctrine\DBAL\Connection

cache_adapter:
    providers:
        default_memcache_adapter:
            factory: 'cache.factory.memcache'
            options:
                host: "%server1.memcache_host%"
                port: "%server1.memcache_port%"
            aliases: ['memcache.default']

monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            max_files: 10

swiftmailer:
    spool:
        type: db
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'