imports:
    - { resource: parameters.yml }
    - { resource: services.xml }
    - { resource: events.xml }

doctrine:
    dbal:
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  "UTF8"
            admin:
                driver:   "%admin.database_driver%"
                host:     "%admin.database_host%"
                port:     "%admin.database_port%"
                dbname:   "%admin.database_name%"
                user:     "%admin.database_user%"
                password: "%admin.database_password%"
                charset:  "UTF8"
            cron:
                driver:   "%cron.database_driver%"
                host:     "%cron.database_host%"
                port:     "%cron.database_port%"
                dbname:   "%cron.database_name%"
                user:     "%cron.database_user%"
                password: "%cron.database_password%"
                charset:  "UTF8"

memcache:
    pools:
        default:
            servers:
                - { host: "%server1.memcache_host%", tcp_port: "%server1.memcache_port%", weight: 15 }
            options:
                allow_failover: true
                max_failover_attempts: 20
                default_port: 11211
                chunk_size: 32768
                protocol: ascii
                hash_strategy: consistent
                hash_function: crc32
                redundancy: true
                session_redundancy: 2
                compress_threshold: 20000
                lock_timeout: 15

monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            max_files: 10