imports:
    - { resource: parameters.yml }
    - { resource: services.xml }
    - { resource: events.xml }

doctrine:
    dbal:
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  "UTF8"
            admin:
                driver:   "%admin.database_driver%"
                host:     "%admin.database_host%"
                port:     "%admin.database_port%"
                dbname:   "%admin.database_name%"
                user:     "%admin.database_user%"
                password: "%admin.database_password%"
                charset:  "UTF8"
            cron:
                driver:   "%cron.database_driver%"
                host:     "%cron.database_host%"
                port:     "%cron.database_port%"
                dbname:   "%cron.database_name%"
                user:     "%cron.database_user%"
                password: "%cron.database_password%"
                charset:  "UTF8"
