imports:
    - { resource: parameters.yml }
    - { resource: services.xml }
    - { resource: events.xml }

doctrine:
    dbal:
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  "UTF8"
            admin:
                driver:   "%admin.database_driver%"
                host:     "%admin.database_host%"
                port:     "%admin.database_port%"
                dbname:   "%admin.database_name%"
                user:     "%admin.database_user%"
                password: "%admin.database_password%"
                charset:  "UTF8"
            cron:
                driver:   "%cron.database_driver%"
                host:     "%cron.database_host%"
                port:     "%cron.database_port%"
                dbname:   "%cron.database_name%"
                user:     "%cron.database_user%"
                password: "%cron.database_password%"
                charset:  "UTF8"

cache_adapter:
    providers:
        default_memcache_adapter:
            factory: 'cache.factory.memcache'
            options:
                host: "%server1.memcache_host%"
                port: "%server1.memcache_port%"
            aliases: ['memcache.default']

monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            max_files: 10

swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'