services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Doctrine Entity listeners
    # General
    KLS\Core\Listener\Doctrine\Entity\TemporaryTokenCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: KLS\Core\Entity\TemporaryToken, method: expireOldTemporaryToken }

    KLS\Core\Listener\Doctrine\Entity\UserPlainPasswordSubmittedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Core\Entity\User, method: encodePlainPassword }
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: KLS\Core\Entity\User, method: encodePlainPassword }

    KLS\Core\Listener\Doctrine\Entity\FileVersion\FileVersionCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: KLS\Core\Entity\FileVersion, method: encryptKey}

    KLS\Core\Listener\Doctrine\Entity\FileVersion\FileVersionLoadedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postLoad, entity: KLS\Core\Entity\FileVersion, method: decryptKey }

    KLS\Core\Listener\Doctrine\Entity\FileVersion\FileVersionUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Core\Entity\FileVersion, method: blockUpdating }

    KLS\Core\Listener\Doctrine\Entity\Folder\FolderDeletedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preRemove, entity: KLS\Core\Entity\Folder, method: cascadeDeletion }

    KLS\Syndication\Arrangement\Listener\Doctrine\Entity\Project\ProjectCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: KLS\Syndication\Arrangement\Entity\Project, method: purify }

    KLS\Syndication\Arrangement\Listener\Doctrine\Entity\Project\ProjectUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Syndication\Arrangement\Entity\Project, method: purify }

    KLS\Syndication\Arrangement\Listener\Doctrine\Entity\ProjectParticipationMember\ProjectParticipationMemberArchivedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Syndication\Arrangement\Entity\ProjectParticipationMember, method: setArchivedBy }

    KLS\CreditGuaranty\Listener\Doctrine\Entity\ProgramCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: KLS\CreditGuaranty\Entity\Program, method: createPredefinedChoiceOption }

    # Message Dispatcher
    KLS\Core\Listener\Doctrine\Entity\MessageDispatcher\User\UserUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Core\Entity\User }

    KLS\Core\Listener\Doctrine\Entity\MessageDispatcher\Staff\StaffCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: KLS\Core\Entity\Staff}

    KLS\Core\Listener\Doctrine\Entity\MessageDispatcher\CompanyModule\CompanyModuleUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postUpdate, entity: KLS\Core\Entity\CompanyModule }

    KLS\Core\Listener\Doctrine\Entity\MessageDispatcher\Message\MessageCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: KLS\Core\Entity\Message}

    KLS\Syndication\Arrangement\Listener\Doctrine\Entity\MessageDispatcher\Project\ProjectCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: KLS\Syndication\Arrangement\Entity\Project }

    KLS\Syndication\Arrangement\Listener\Doctrine\Entity\MessageDispatcher\ProjectParticipationMember\ProjectParticipationMemberCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: KLS\Syndication\Arrangement\Entity\ProjectParticipationMember }

    KLS\Syndication\Arrangement\Listener\Doctrine\Entity\MessageDispatcher\Project\ProjectUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Syndication\Arrangement\Entity\Project}

    KLS\Syndication\Arrangement\Listener\Doctrine\Entity\MessageDispatcher\ProjectParticipation\ProjectParticipationUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Syndication\Arrangement\Entity\ProjectParticipation}

    KLS\Agency\Listener\Doctrine\MessageDispatcher\ProjectMemberCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: KLS\Agency\Entity\BorrowerMember }
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: KLS\Agency\Entity\AgentMember }
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: KLS\Agency\Entity\ParticipationMember }

    KLS\Agency\Listener\Doctrine\MessageDispatcher\ProjectMemberUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Agency\Entity\BorrowerMember }
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Agency\Entity\AgentMember }
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Agency\Entity\ParticipationMember }

    KLS\Agency\Listener\Doctrine\MessageDispatcher\ProjectStatusUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: KLS\Agency\Entity\Project }

    # Doctrine Lifecycle Event Listener
    KLS\Core\Listener\Doctrine\Lifecycle\UuidListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    KLS\Core\Listener\Doctrine\Lifecycle\UpdatedByListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    KLS\Core\Listener\Doctrine\Lifecycle\ArchivedByListener:
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    KLS\Core\Listener\Doctrine\Lifecycle\StatusCreatedListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    KLS\Core\Listener\Doctrine\Lifecycle\CompanyModuleUpdatedListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    KLS\Syndication\Arrangement\Listener\Doctrine\Lifecycle\ProjectStatusUpdatedListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    KLS\Syndication\Arrangement\Listener\Doctrine\Lifecycle\ProjectParticipationUpdated:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    KLS\Syndication\Arrangement\Listener\Doctrine\Lifecycle\ProjectParticipationTrancheUpdatedListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    KLS\Agency\Listener\Doctrine\TermListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    KLS\Agency\Listener\Doctrine\CovenantListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postUpdate }

    KLS\Agency\Listener\Doctrine\ParticipationListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    KLS\Agency\Listener\Doctrine\ProjectListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    KLS\CreditGuaranty\Listener\Doctrine\ProgramDeleteListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    KLS\CreditGuaranty\Listener\Doctrine\ReservationDeleteListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    KLS\Agency\Listener\Doctrine\AgencyModuleActivatedListener:
        tags:
           - { name: doctrine.event_listener, event: onFlush }
