services:
    _defaults:
        autowire: true
        autoconfigure: true

    Unilend\Listener\Doctrine\Entity\ClientsListener:
        tags:
            -  name: doctrine.orm.entity_listener
               event: preUpdate
               entity: Unilend\Entity\Clients

    Unilend\Listener\Doctrine\Entity\TemporaryTokenListener:
        tags:
            - name: doctrine.orm.entity_listener
              event: prePersist
              entity: Unilend\Entity\TemporaryToken

    Unilend\Listener\Doctrine\Entity\ProjectParticipationListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: Unilend\Entity\ProjectParticipation }
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: Unilend\Entity\ProjectParticipation }

    Unilend\Listener\Doctrine\Lifecycle\ClientProfileCompletedListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }