services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Doctrine Entity listeners
    # General
    Unilend\Core\Listener\Doctrine\Entity\TemporaryTokenCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: Unilend\Core\Entity\TemporaryToken, method: expireOldTemporaryToken }

    Unilend\Core\Listener\Doctrine\Entity\UserPlainPasswordSubmittedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Core\Entity\User, method: encodePlainPassword }
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: Unilend\Core\Entity\User, method: encodePlainPassword }

    Unilend\Core\Listener\Doctrine\Entity\FileVersion\FileVersionCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: Unilend\Core\Entity\FileVersion, method: encryptKey}

    Unilend\Core\Listener\Doctrine\Entity\FileVersion\FileVersionLoadedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postLoad, entity: Unilend\Core\Entity\FileVersion, method: decryptKey }

    Unilend\Core\Listener\Doctrine\Entity\FileVersion\FileVersionUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Core\Entity\FileVersion, method: blockUpdating }

    Unilend\Syndication\Listener\Doctrine\Entity\Project\ProjectCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: Unilend\Syndication\Entity\Project, method: purify }

    Unilend\Syndication\Listener\Doctrine\Entity\Project\ProjectUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Syndication\Entity\Project, method: purify }

    Unilend\Syndication\Listener\Doctrine\Entity\ProjectParticipationMember\ProjectParticipationMemberArchivedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Syndication\Entity\ProjectParticipationMember, method: setArchivedBy }

    Unilend\Agency\Listener\Doctrine\ParticipationListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    Unilend\Agency\Listener\Doctrine\TermListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    Unilend\Agency\Listener\Doctrine\CovenantListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postUpdate }

    Unilend\Agency\Listener\Doctrine\ProjectListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    # Message Dispatcher
    Unilend\Core\Listener\Doctrine\Entity\MessageDispatcher\User\UserUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Core\Entity\User }

    Unilend\Core\Listener\Doctrine\Entity\MessageDispatcher\Staff\StaffCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: Unilend\Core\Entity\Staff}

    Unilend\Core\Listener\Doctrine\Entity\MessageDispatcher\CompanyModule\CompanyModuleUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postUpdate, entity: Unilend\Core\Entity\CompanyModule }

    Unilend\Core\Listener\Doctrine\Entity\MessageDispatcher\Message\MessageCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: Unilend\Core\Entity\Message}

    Unilend\Syndication\Listener\Doctrine\Entity\MessageDispatcher\Project\ProjectCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: Unilend\Syndication\Entity\Project }

    Unilend\Syndication\Listener\Doctrine\Entity\MessageDispatcher\ProjectParticipationMember\ProjectParticipationMemberCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: Unilend\Syndication\Entity\ProjectParticipationMember }

    Unilend\Syndication\Listener\Doctrine\Entity\MessageDispatcher\Project\ProjectUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Syndication\Entity\Project}

    Unilend\Syndication\Listener\Doctrine\Entity\MessageDispatcher\ProjectParticipation\ProjectParticipationUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Syndication\Entity\ProjectParticipation}


    # Doctrine Lifecycle Event Listener
    Unilend\Core\Listener\Doctrine\Lifecycle\UuidListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    Unilend\Core\Listener\Doctrine\Lifecycle\UpdatedByListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    Unilend\Core\Listener\Doctrine\Lifecycle\ArchivedByListener:
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    Unilend\Core\Listener\Doctrine\Lifecycle\StatusCreatedListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    Unilend\Core\Listener\Doctrine\Lifecycle\CompanyModuleUpdatedListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    Unilend\Syndication\Listener\Doctrine\Lifecycle\ProjectStatusUpdatedListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    Unilend\Syndication\Listener\Doctrine\Lifecycle\ProjectParticipationUpdated:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    Unilend\Syndication\Listener\Doctrine\Lifecycle\ProjectParticipationTrancheUpdatedListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    Unilend\CreditGuaranty\Listener\Doctrine\Lifecycle\ProgramCreatedListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
