services:
    _defaults:
        autowire: true
        autoconfigure: true

# Doctrine Entity listeners
    Unilend\Listener\Doctrine\Entity\MessageDispatcher\Client\ClientUpdatedListener:
        tags:
            -   name: doctrine.orm.entity_listener
                event: preUpdate
                entity: Unilend\Entity\Clients

    Unilend\Listener\Doctrine\Entity\MessageDispatcher\Attachment\AttachmentCreatedListener:
      tags:
        - name: doctrine.orm.entity_listener
          event: postPersist
          entity: Unilend\Entity\Attachment

    Unilend\Listener\Doctrine\Entity\MessageDispatcher\Project\ProjectCreatedListener:
        tags:
            -   name: doctrine.orm.entity_listener
                event: postPersist
                entity: Unilend\Entity\Project

    Unilend\Listener\Doctrine\Entity\MessageDispatcher\ProjectParticipationContact\ProjectParticipationContactCreatedListener:
        tags:
            -   name: doctrine.orm.entity_listener
                event: postPersist
                entity: Unilend\Entity\ProjectParticipationContact

    Unilend\Listener\Doctrine\Entity\MessageDispatcher\Staff\StaffCreatedListener:
        tags:
            -   name: doctrine.orm.entity_listener
                event: postPersist
                entity: Unilend\Entity\Staff

    Unilend\Listener\Doctrine\Entity\TemporaryTokenCreatedListener:
        tags:
            -   name: doctrine.orm.entity_listener
                event: prePersist
                entity: Unilend\Entity\TemporaryToken
                method: expireOldTemporaryToken

    Unilend\Listener\Doctrine\Entity\ClientPlainPasswordSubmittedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Entity\Clients, method: encodePlainPassword }
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: Unilend\Entity\Clients, method: encodePlainPassword }

    Unilend\Listener\Doctrine\Entity\StaffLogListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: Unilend\Entity\Staff, method: logStaff }
            - { name: doctrine.orm.entity_listener, event: postUpdate, entity: Unilend\Entity\Staff, method: logStaff }

    Unilend\Listener\Doctrine\Entity\FileVersion\FileVersionCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: Unilend\Entity\Attachment, method: encryptKey}

    Unilend\Listener\Doctrine\Entity\FileVersion\FileVersionLoadedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postLoad, entity: Unilend\Entity\Attachment, method: decryptKey }

    Unilend\Listener\Doctrine\Entity\FileVersion\FileVersionUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Entity\Attachment, method: blockUpdating }

    Unilend\Listener\Doctrine\Entity\ModuleLogListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postUpdate, entity: Unilend\Entity\Module, method: logModule }

    Unilend\Listener\Doctrine\Entity\Project\ProjectCreatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: Unilend\Entity\Project, method: purify}

    Unilend\Listener\Doctrine\Entity\Project\ProjectUpdatedListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: Unilend\Entity\Project, method: purify}

# Doctrine Lifecycle Event Listener
    Unilend\Listener\Doctrine\Lifecycle\UuidListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    Unilend\Listener\Doctrine\Lifecycle\UpdatedByListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    Unilend\Listener\Doctrine\Lifecycle\ArchivedByListener:
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    Unilend\Listener\Doctrine\Entity\MessageDispatcher\ProjectListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }