parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     unilend
    database_user:     front
    database_password: front

    admin.database_driver:   pdo_mysql
    admin.database_host:     localhost
    admin.database_port:          ~
    admin.database_name:     unilend
    admin.database_user:     back
    admin.database_password: back

    cron.database_driver:   pdo_mysql
    cron.database_host:     localhost
    cron.database_port:          ~
    cron.database_name:     unilend
    cron.database_user:     cron
    cron.database_password: cron

    server1.memcache_host:   127.0.0.1
    server1.memcache_port:   11211

    mailer_transport: unilend.swiftmailer.transport.mailjet
    mailer_host: ~
    mailer_user: ~
    mailer_password: ~

    mailjet.api_key:    9968d5b7419c2d4edf7c00f32f629f8a
    mailjet.api_secret: 579bc26d8656f837ca8dcdcc6739da95