parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     unilend
    database_user:     front
    database_password: front

    admin.database_driver:   pdo_mysql
    admin.database_host:     localhost
    admin.database_port:          ~
    admin.database_name:     unilend
    admin.database_user:     back
    admin.database_password: back

    cron.database_driver:   pdo_mysql
    cron.database_host:     localhost
    cron.database_port:          ~
    cron.database_name:     unilend
    cron.database_user:     cron
    cron.database_password: cron