parameters:
    front.database_driver:   pdo_mysql
    front.database_host:     localhost
    front.database_name:     unilend
    front.database_user:     front
    front.database_password: front

    back.database_driver:   pdo_mysql
    back.database_host:     localhost
    back.database_name:     unilend
    back.database_user:     back
    back.database_password: back

    cron.database_driver:   pdo_mysql
    cron.database_host:     localhost
    cron.database_name:     unilend
    cron.database_user:     cron
    cron.database_password: cron