front:
    resource: 'routes/front/routes.yaml'
    host: '%front.host%'
    methods: ['GET']
    schemes: ['https']
    name_prefix: 'front_'

health_check:
    path: /pulse
    controller: Unilend\Core\Controller\HealthCheck

# PSN callback URL
file-signature-result:
    path: /file_version_signatures/{fileSignatureId}/result
    controller: Unilend\Core\Controller\FileVersionSignature\Result

# Route created to return a 404 for pulse check
home:
    path: /
    defaults: { _controller: ApiPlatform\Core\Action\NotFoundAction }
