sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

_knp_mailjet:
    path:  /ws/mailjet/notify/{token}
    defaults: { _controller: knp_mailjet.event.controller:handleEventAction, token: null }

api_login_check:
    path: /authentication_token
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path:       /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

front:
    resource: 'front/routes.yaml'
    host: '%front.host%'
    methods: ['GET']
    schemes: ['https']
    name_prefix: 'front_'

health_check:
    path: /pulse
    controller: Unilend\Controller\HealthCheck
