front:
    resource: 'routes/front/routes.yaml'
    host: '%front.host%'
    methods: ['GET']
    schemes: ['https']
    name_prefix: 'front_'

health_check:
    path: /core/pulse
    controller: KLS\Core\Controller\HealthCheck

# PSN callback URL
file-signature-result:
    path: /core/file_version_signatures/{fileSignatureId}/result
    controller: KLS\Core\Controller\FileVersionSignature\Result
