sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

_knp_mailjet:
    path:  /ws/mailjet/notify/{token}
    defaults: { _controller: knp_mailjet.event.controller:handleEventAction, token: null }

api_login_check:
    path: /api/authentication_token
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
