parameters:
    sonata_cache.servers:
        - { domain: '%env(INTERNAL_SERVER_DOMAIN_HOST1)%', ip: '%env(INTERNAL_SERVER_IP_HOST1)%', port: '%env(int:INTERNAL_SERVER_PORT_HOST1)%' }
    dbal_driver_class: Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver
    locale: fr_FR
    router.request_context.scheme: https
    directory.public: /data/sites/unilend/public/default/
    directory.shared: /data/medias/nfs/
    directory.temporary: '%directory.shared%tmp/'
    directory.protected: '%directory.shared%protected/'
    directory.public_var: '%directory.public%var/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $consoleLogger: '@monolog.logger.console'
            $defaultLocale: '%locale%'
            $temporaryDirectory: '%directory.temporary%'
            $templateMessageFQCN: 'Unilend\SwiftMailer\TemplateMessage'
            $frontUrl: '%router.request_context.scheme%://%env(HOST_APP_URL)%'
            $adminUrl: '%router.request_context.scheme%://%env(HOST_ADMIN_URL)%'
            $numberFormatter: '@number_formatter'
            $currencyFormatter: '@currency_formatter'
            $percentageFormatter: '@percentage_formatter'
            $currencyFormatterNoDecimal: '@currency_formatter_no_decimal'
            $environment: '%kernel.environment%'
            $publicDirectory: '%directory.public%'
            $documentRootDirectory: '%directory.protected%/generated_document/'
            $projectDirectory: '%kernel.project_dir%'
            $userUploadDirectory: '%directory.public%var/upload/'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Unilend\:
        resource: '%kernel.project_dir%/src/*'
        # The directory Unilend contains the legacy bundles. The services are managed by their own configurations.
        exclude: '%kernel.project_dir%/src/{Console,Entity,Migrations,Tests,Traits,Kernel.php}'

    Unilend\Controller\SecurityController:
        $recaptchaKey: '%env(GOOGLE_RECAPTCHA_KEY)%'

    Unilend\Service\Translation\TranslationLoader:
        tags:
            - { name: translation.loader, alias: db }

    Unilend\Service\WebServiceClient\InseeManager:
        $client: '@eight_points_guzzle.client.insee'

    Unilend\Service\Attachment\AttachmentManager:
        $uploadRootDirectory: '%directory.protected%attachments'

    Unilend\Service\GoogleRecaptchaManager:
        $client: '@eight_points_guzzle.client.google_recaptcha'
        $secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'

    docusign.http_client:
        class: 'Symfony\Contracts\HttpClient\HttpClientInterface'
        factory: ['Symfony\Component\HttpClient\HttpClient', create]

    Unilend\Service\ElectronicSignatureManager:
        $integratorKey: '%env(DOCUSIGN_INTEGRATOR_KEY)%'
        $userId: '%env(DOCUSIGN_USER_ID)%'
        $privateKey: '%env(file:DOCUSIGN_PRIVATE_KEY)%'
        $httpClient: '@docusign.http_client'
        $accountHost: '%env(DOCUSIGN_ACCOUNT_HOST)%'
        $apiHost: '%env(DOCUSIGN_API_HOST)%'
        $debug: '%kernel.debug%'

    currency_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::CURRENCY

    currency_formatter_no_decimal:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::CURRENCY
        calls:
            - method: setAttribute
              arguments:
                - !php/const \NumberFormatter::MAX_FRACTION_DIGITS
                - 0

    number_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::DEFAULT_STYLE

    date_formatter:
        public: true
        class: IntlDateFormatter
        arguments:
            - '%locale%'
            - !php/const \IntlDateFormatter::MEDIUM
            - !php/const \IntlDateFormatter::SHORT

    clients_listener:
        class: Unilend\Listener\Entity\ClientsListener
        arguments:
            - '@Unilend\Service\MailerManager'
            - '@doctrine.orm.entity_manager'
            - '@Symfony\Component\Messenger\MessageBusInterface'
        tags:
            - name: doctrine.orm.entity_listener
              event: preUpdate
              entity: Unilend\Entity\Clients

    percentage_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::PERCENT
        calls:
            - method: setAttribute
              arguments:
                  - !php/const \NumberFormatter::FRACTION_DIGITS
                  - 2

    UserAgentParser\Provider\WhichBrowser:
        class: UserAgentParser\Provider\WhichBrowser

    UserAgentParser\Provider\PiwikDeviceDetector:
        class: UserAgentParser\Provider\PiwikDeviceDetector

    UserAgentParser\Provider\Chain:
        $providers:
            - '@UserAgentParser\Provider\WhichBrowser'
            - '@UserAgentParser\Provider\PiwikDeviceDetector'
