parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: unilend
    database_user: unilend
    database_password: myPassw0rd
    database_user_migration: unilend
    database_password_migration: myPassw0rd
    database_ssl_key: null
    database_ssl_cert: null
    database_ssl_ca: null
    mongodb_server: 'mongodb://127.0.0.1:27017'
    mongodb_username: unilend
    mongodb_password: passw0rd
    mongodb_default_database: ws_call
    mongodb_auth_source: ws_call
    mongodb_ssl_connect: false
    mongodb_replica_set_name: null
    mongodb.log.enable: false
    mailjet.api_key: null
    mailjet.api_secret: null
    mailjet.api_version: v3.1
    mailer_transport: smtp
    mailer_host: localhost
    mailer_port: 1025
    desk_user: ''
    desk_password: ''
    google.gtm_token: ''
    google.recaptcha_key: ''
    google.recaptcha_secret: ''
    google.recaptcha_url: 'https://www.google.com/recaptcha/api/siteverify'
    url.universign: ''
    url.host_admin: admin.local.unilend.fr
    url.host_default: www.local.unilend.fr
    sonata_cache.servers:
        -
            domain: www.local.unilend.fr
            ip: 192.168.110.12
            port: 443
    payline.merchant_id: ''
    payline.access_key: ''
    ekomi.url: 'https://srr.ekomi.com/add-recipient'
    ekomi.shop_id: null
    ekomi.password: null
    euler.account_key: ''
    euler.grading_key: ''
    euler.url: 'https://api-demo.single-invoice.co/v2.0/'
    euler.email: ''
    euler.password: ''
    codinf.user: null
    codinf.password: null
    codinf.url: 'https://www.codinf.fr/incidents/'
    infolegale.token: ''
    infolegale.url: 'https://wspreprod.infolegale.fr/'
    infogreffe.login: ''
    infogreffe.password: ''
    infogreffe.url: 'https://qual.infogreffe.fr:443/WSContextInfogreffe/INFOGREFFE'
    infogreffe.wsdl_url: 'https://qual.infogreffe.fr/InfogreffeWs/wsdl.jsp'
    altares.login: ''
    altares.password: ''
    altares.wsdl_url_identity: 'https://intuiz.altares.fr/iws-v3.13/services/CallistoIdentite?wsdl'
    altares.wsdl_url_risk: 'https://intuiz.altares.fr/iws-v3.13/services/CallistoRisque?wsdl'
    altares.wsdl_url_risk_monitoring: 'https://intuiz.altares.fr/iws-v3.13/services/CallistoAlerte?wsdl'
    ellisphere.contract_id: null
    ellisphere.user_prefix: null
    ellisphere.user_id: null
    ellisphere.password: null
    ellisphere.url: 'https://services.data-access-gateway.com/1/rest/'
    greenpoint.url: 'https://id-control.fr/api/'
    greenpoint.login: ''
    greenpoint.password: ''
    slack.default_channel: '#it-testing'
    dbal_wrapper_class: Unilend\Doctrine\DBAL\Connection
    dbal_driver_class: Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver
    secret: ''
    locale: fr_FR
    server1.memcache_host: 127.0.0.1
    server1.memcache_port: 11211
    image_resize:
        projets:
            authorized:
                - 72
                - 169
            height: 1365
            width: 2048
    router.request_context.scheme: https
    path.static: /data/sites/unilend/public/default/
    path.shared: /data/medias/nfs/
    path.shared_tmp: '%path.shared%tmp/'
    path.user: '%path.shared%var/'
    path.sftp: '%path.shared%sftp/'
    path.protected: '%path.shared%protected/'
    path.logs: /data/log
    path.payline: '%path.logs%/payline'
    mapbox.token: ''
    security.bcrypt.cost: 13
    new_relic.api_key: edc37da0a36bfd74eded96d4d454c8f7b4b0ab8d4bce97e
    new_relic.front_app_name: Unilend-front
    new_relic.back_app_name: Unilend-backoffice
    new_relic.console_app_name: Unilend-batchjobs
    slack.team_id: ''
    slack.command_token: ''
    slack.monitoring_channel: '#it-monitoring'
    slack.default_username: Unilend
    slack.endpoint: 'https://hooks.slack.com/services'
    mailchimp.api_key: '-'
    mailchimp.webhook_secret: ''
    mailchimp.list_id: ''
    mailchimp.gdpr_segment_id: ''
    translation_cache_path: '%kernel.cache_dir%/translations'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $consoleLogger: '@monolog.logger.console'
            $wsClientLogger: '@monolog.logger.wsclient'
            $defaultLocale: '%locale%'
            $sharedTemporaryPath: '%path.shared_tmp%'
            $templateMessageFQCN: 'Unilend\SwiftMailer\TemplateMessage'
            $frontUrl: '%router.request_context.scheme%://%url.host_default%'
            $adminUrl: '%router.request_context.scheme%://%url.host_admin%'
            $rootDirectory: '%kernel.root_dir%'
            $numberFormatter: '@number_formatter'
            $currencyFormatter: '@currency_formatter'
            $environment: '%kernel.environment%'
            $protectedPath: '%path.protected%'
            $staticPath: '%path.static%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Unilend\:
        resource: '%kernel.project_dir%/src/*'
        # The directory Unilend contains the legacy bundles. The services are managed by their own configurations.
        exclude: '%kernel.project_dir%/src/{Console,Entity,Migrations,Tests,Unilend,Kernel.php}'

    # Define the memcache adaptor as the application default cache globally in order to have the right adaptor when autowiring Psr\Cache\CacheItemPoolInterface
    # Since we use the cache/adapter-bundle as the cache system, the configuration framework.cache.app won't work.
    # It can be removed once TECH-333 will be done.
    cache.app: '@memcache.default'
    # Define the logger service as public so we can continue to have access to it via $container->get().
    # But $container->get('logger') is deprecated, do not use it any more.
    logger:
        alias: 'monolog.logger'
        public: true

    Mailjet\Client:
        $key: '%mailjet.api_key%'
        $secret: '%mailjet.api_secret%'
        $call: true
        $settings:
            version: '%mailjet.api_version%'

    # Swift Mailer and its bridges
    swiftmailer.spool.db: '@Unilend\SwiftMailer\DatabaseSpool'
    swiftmailer.mailer.default.spool.db: '@Unilend\SwiftMailer\DatabaseSpool'
    swiftmailer.mailer.transport.mailjet: '@Unilend\SwiftMailer\MailjetTransport'
    mailjet: '@Unilend\SwiftMailer\MailjetTransport'

    Unilend\Service\Translation\TranslationLoader:
        tags:
            - { name: translation.loader, alias: db }

    Unilend\Service\WebServiceClient\CallHistoryManager:
        arguments:
            $alertChannel: '%slack.default_channel%'
            $mongoDBLogger: '@monolog.logger.mongodb'
            $mongoLogEnabled: "%mongodb.log.enable%"

    soap_client.altares_identity:
        class: SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_identity%'
            $options:
                exception: 1
                trace: 1

    soap_client.altares_risque:
        class: SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_risk%'
            $options:
                exception: 1
                trace: 1

    soap_client.altares_risk_monitoring:
        class: SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_risk_monitoring%'
            $options:
                exception: 1
                trace: 1

    Unilend\Service\WebServiceClient\EulerHermesManager:
        $client: '@eight_points_guzzle.client.euler'
        $gradingApiKey: '%euler.grading_key%'
        $accountApiKey: '%euler.account_key%'
        $accountPassword: '%euler.password%'
        $accountEmail: '%euler.email%'

    Unilend\Service\WebServiceClient\CodinfManager:
        $client: '@eight_points_guzzle.client.codinf'
        $user: '%codinf.user%'
        $password: '%codinf.password%'

    Unilend\Service\WebServiceClient\InfolegaleManager:
        $client: '@eight_points_guzzle.client.infolegale'
        $token: '%infolegale.token%'

    Unilend\Service\WebServiceClient\InfogreffeManager:
        $login: '%infogreffe.login%'
        $password: '%infogreffe.password%'
        $wsdl: '%infogreffe.wsdl_url%'
        $url: '%infogreffe.url%'

    Unilend\Service\WebServiceClient\AltaresManager:
        $login: '%altares.login%'
        $password: '%altares.password%'
        $identityClient: '@soap_client.altares_identity'
        $riskClient: '@soap_client.altares_risque'
        $riskMonitoringClient: '@soap_client.altares_risk_monitoring'

    Unilend\Service\WebServiceClient\EllisphereManager:
        $client: '@eight_points_guzzle.client.ellisphere'
        $contractId: '%ellisphere.contract_id%'
        $userPrefix: '%ellisphere.user_prefix%'
        $userId: '%ellisphere.user_id%'
        $password: '%ellisphere.password%'

    Unilend\Service\WebServiceClient\GreenPointManager:
        $client: '@eight_points_guzzle.client.greenpoint'
        $login: '%greenpoint.login%'
        $password: '%greenpoint.password%'

    Unilend\Service\WebServiceClient\InseeManager:
        $client: '@eight_points_guzzle.client.insee'

    Unilend\Service\Product\ProductManager: '@Unilend\Service\PartnerProductManager'

    # The "public: true" can be removed if there is no more access via $container->get()
    Unilend\Service\AcceptedBidAndLoanNotificationSender:
        public: true

    Unilend\Service\SalesforceManager:
        $extractionDir: '%path.protected%dataloader'
        $configDir: '%kernel.root_dir%/dataloader/conf'

    Unilend\Service\LocationManager:
        $mapboxToken: '%mapbox.token%'

    Unilend\Service\SearchService:
        $deskUser: '%desk_user%'
        $deskPassword: '%desk_password%'

    Unilend\Service\Ekomi:
        $url: '%ekomi.url%'
        $shopId: '%ekomi.shop_id%'
        $password: '%ekomi.password%'

    Unilend\Service\PaylineManager:
        $merchantId: '%payline.merchant_id%'
        $accessKey: '%payline.access_key%'
        $logPath: '%path.payline%'

    Unilend\Service\AttachmentManager:
        $uploadRootDirectory: '%path.protected%attachments'
        $tmpDirectory: '%path.shared_tmp%'

    Unilend\Service\GoogleRecaptchaManager:
        $client: '@eight_points_guzzle.client.google_recaptcha'
        $secret: '%google.recaptcha_secret%'

    currency_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::CURRENCY

    number_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::DEFAULT_STYLE

    date_formatter:
        public: true
        class: IntlDateFormatter
        arguments:
            - '%locale%'
            - !php/const \IntlDateFormatter::MEDIUM
            - !php/const \IntlDateFormatter::SHORT

    UserAgentParser\Provider\WhichBrowser:
        class: UserAgentParser\Provider\WhichBrowser

    UserAgentParser\Provider\PiwikDeviceDetector:
        class: UserAgentParser\Provider\PiwikDeviceDetector

    UserAgentParser\Provider\Chain:
        $providers:
            - '@UserAgentParser\Provider\WhichBrowser'
            - '@UserAgentParser\Provider\PiwikDeviceDetector'

    Unilend\Security\BCryptPasswordEncoder:
        $cost: '%security.bcrypt.cost%'

    Unilend\Service\Front\UniversignManager:
        $universignURL: '%url.universign%'
