imports:
    - { resource: doctrine_listeners.yml }

parameters:
    locale: fr_FR
    router.request_context.scheme: https
    directory.public: /data/sites/unilend/public
    directory.shared: /data/medias/nfs/
    directory.temporary: '%directory.shared%tmp/'
    directory.protected: '%directory.shared%protected/'
    front.host: '%env(HOST_APP_URL)%'
    maintenance: '%env(MAINTENANCE_MODE)%'
    slack.webhook.support: '%env(SLACK_WEBHOOK_URL)%'
    slack.webhook.security: https://hooks.slack.com/services/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
    security.recipients: ['tech@ca-lendingservices.com']
    file_encryption.kek_file: '%env(FILE_ENCRYPTION_KEK_FILE)%'
    file_encryption.kek_passphrase: '%env(FILE_ENCRYPTION_KEK_PASSPHRASE)%'
    psn.public_key: '%env(base64:PSN_PUBLIC_KEY)%'
    psn.private_key: '%env(base64:PSN_PRIVATE_KEY)%'
    psn.base_uri: '%env(PSN_BASE_URI)%'
    mailer.error_reporting_email: tech@kls-platform.com
    mailer.sender_address: support@kls-platform.com

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $consoleLogger: '@monolog.logger.console'
            $defaultLocale: '%locale%'
            $temporaryDirectory: '%directory.temporary%'
            $templateMessageFQCN: 'Unilend\Core\SwiftMailer\TemplateMessage'
            $numberFormatter: '@number_formatter'
            $currencyFormatter: '@currency_formatter'
            $percentageFormatter: '@percentage_formatter'
            $currencyFormatterNoDecimal: '@currency_formatter_no_decimal'
            $environment: '%kernel.environment%'
            $publicDirectory: '%directory.public%'
            $documentRootDirectory: '%directory.protected%/generated_document/'
            $projectDirectory: '%kernel.project_dir%'
            $userAttachmentFilesystem: '@League\Flysystem\UserAttachmentFilesystem'
            $generatedDocumentFilesystem: '@League\Flysystem\GeneratedDocumentFilesystem'
            $securityRecipients: '%security.recipients%'
            $debug: '%kernel.debug%'
            $senderAddress: '%mailer.sender_address%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Unilend\:
        resource: '%kernel.project_dir%/src/*'
        # The directory Unilend contains the legacy bundles. The services are managed by their own configurations.
        exclude: [
            '%kernel.project_dir%/src/Kernel.php',
            '%kernel.project_dir%/src/{Core,Syndication,CreditGuaranty}/{Console,Entity,Migrations,Controller,Tests,Traits,Listener}'
        ]

    Unilend\Core\Controller\:
        resource: '%kernel.project_dir%/src/Core/Controller'
        tags:
            - { name: 'controller.service_arguments' }

    Unilend\Core\Service\WebServiceClient\InseeManager:
        $client: '@eight_points_guzzle.client.insee'

    Unilend\Core\Service\GoogleRecaptchaManager:
        $client: '@eight_points_guzzle.client.google_recaptcha'
        $secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'

    docusign.http_client:
        class: 'Symfony\Contracts\HttpClient\HttpClientInterface'
        factory: ['Symfony\Component\HttpClient\HttpClient', create]

    Unilend\Core\Service\ElectronicSignatureManager:
        $integratorKey: '%env(DOCUSIGN_INTEGRATOR_KEY)%'
        $userId: '%env(DOCUSIGN_USER_ID)%'
        $privateKey: '%env(file:DOCUSIGN_PRIVATE_KEY)%'
        $httpClient: '@docusign.http_client'
        $accountHost: '%env(DOCUSIGN_ACCOUNT_HOST)%'
        $apiHost: '%env(DOCUSIGN_API_HOST)%'
        $debug: '%kernel.debug%'

    currency_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::CURRENCY

    currency_formatter_no_decimal:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::CURRENCY
        calls:
            - method: setAttribute
              arguments:
                - !php/const \NumberFormatter::MAX_FRACTION_DIGITS
                - 0

    number_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::DEFAULT_STYLE

    date_formatter:
        public: true
        class: IntlDateFormatter
        arguments:
            - '%locale%'
            - !php/const \IntlDateFormatter::MEDIUM
            - !php/const \IntlDateFormatter::SHORT

    percentage_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::PERCENT
        calls:
            - method: setAttribute
              arguments:
                  - !php/const \NumberFormatter::FRACTION_DIGITS
                  - 2

    Unilend\Core\Swagger\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.api_gateway'

    Unilend\Core\Serializer\ContextBuilder\Staff\CurrentStaff:
        decorates: 'api_platform.serializer.context_builder'
        autoconfigure: false

    Unilend\Core\Serializer\ContextBuilder\CurrentUser:
        decorates: 'api_platform.serializer.context_builder'
        autoconfigure: false

    Unilend\Core\Serializer\ContextBuilder\SkipNullValue:
        decorates: 'api_platform.serializer.context_builder'
        autoconfigure: false

    Unilend\Core\Serializer\ContextBuilder\MaxDepth:
        decorates: 'api_platform.serializer.context_builder'
        autoconfigure: false

    Unilend\Core\Serializer\ContextBuilder\CircularReferenceHandler:
        decorates: 'api_platform.serializer.context_builder'
        autoconfigure: false

    Unilend\Core\Serializer\ContextBuilder\DeepObjectToPopulate:
        decorates: 'api_platform.serializer.context_builder'
        autoconfigure: false

    Unilend\Core\Service\ElectronicSignature\XmlSigner:
        $publicKey: '%psn.public_key%'
        $privateKey: '%psn.private_key%'

    Unilend\Core\Service\DataCrypto:
        $masterKeyPath: '%file_encryption.kek_file%'
        $masterKeyPassPhrase: '%file_encryption.kek_passphrase%'

    Unilend\Core\Security\UsernamePasswordRecaptchaAuthenticator:
        $authenticationSuccessHandler: '@lexik_jwt_authentication.handler.authentication_success'
        $authenticationFailureHandler: '@lexik_jwt_authentication.handler.authentication_failure'
        $path: '/core/authentication_token'

    Unilend\Core\Listener\MaintenanceListener:
        arguments: ["%maintenance%"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    Unilend\Core\SwiftMailer\TemplateErrorReportingPlugin:
        tags:
            - { name: swiftmailer.default.plugin }
        arguments:
            $enableErrorDelivery: '%env(MAILJET_ERROR_DELIVERY)%'
            $errorReportingEmail: '%mailer.error_reporting_email%'

    Unilend\Core\ApiPlatform\Metadata\Metadata\Resource\Factory\ShortNameResourceMetadataFactory:
        decorates: 'api_platform.metadata.resource.metadata_factory'
