parameters:
    sonata_cache.servers:
        - { domain: '%env(INTERNAL_SERVER_DOMAIN_HOST1)%', ip: '%env(INTERNAL_SERVER_IP_HOST1)%', port: '%env(int:INTERNAL_SERVER_PORT_HOST1)%' }
    dbal_wrapper_class: Unilend\Doctrine\DBAL\Connection
    dbal_driver_class: Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver
    locale: fr_FR
    image_resize:
        projets:
            authorized:
                - 72
                - 169
            height: 1365
            width: 2048
    router.request_context.scheme: https
    directory.public: /data/sites/unilend/public/default/
    directory.shared: /data/medias/nfs/
    directory.temporary: '%directory.shared%tmp/'
    directory.user: '%directory.shared%var/'
    directory.sftp: '%directory.shared%sftp/'
    directory.protected: '%directory.shared%protected/'
    directory.logs: /data/log
    mapbox.token: ''
    security.bcrypt.cost: 13
    translation_cache_path: '%kernel.cache_dir%/translations'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $consoleLogger: '@monolog.logger.console'
            $wsClientLogger: '@monolog.logger.wsclient'
            $defaultLocale: '%locale%'
            $temporaryDirectory: '%directory.temporary%'
            $templateMessageFQCN: 'Unilend\SwiftMailer\TemplateMessage'
            $frontUrl: '%router.request_context.scheme%://%env(HOST_DEFAULT_URL)%'
            $adminUrl: '%router.request_context.scheme%://%env(HOST_ADMIN_URL)%'
            $numberFormatter: '@number_formatter'
            $currencyFormatter: '@currency_formatter'
            $currencyFormatterNoDecimal: '@currency_formatter_no_decimal'
            $environment: '%kernel.environment%'
            $protectedDirectory: '%directory.protected%'
            $publicDirectory: '%directory.public%'
            $documentRootDirectory: '%directory.protected%/generated_document/'
            $projectDirectory: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Unilend\:
        resource: '%kernel.project_dir%/src/*'
        # The directory Unilend contains the legacy bundles. The services are managed by their own configurations.
        exclude: '%kernel.project_dir%/src/{Console,Entity,Migrations,Tests,Unilend,Kernel.php}'

    # Define the logger service as public so we can continue to have access to it via $container->get().
    # But $container->get('logger') is deprecated, do not use it any more.
    logger:
        alias: 'monolog.logger'
        public: true

    Unilend\Service\Translation\TranslationLoader:
        tags:
            - { name: translation.loader, alias: db }

    Unilend\Service\WebServiceClient\InseeManager:
        $client: '@eight_points_guzzle.client.insee'

    Unilend\Service\Attachment\AttachmentManager:
        $uploadRootDirectory: '%directory.protected%attachments'

    Unilend\Service\GoogleRecaptchaManager:
        $client: '@eight_points_guzzle.client.google_recaptcha'
        $secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'

    docusign.http_client:
        class: 'Symfony\Contracts\HttpClient\HttpClientInterface'
        factory: ['Symfony\Component\HttpClient\HttpClient', create]

    Unilend\Service\ElectronicSignatureManager:
        $integratorKey: '%env(DOCUSIGN_INTEGRATOR_KEY)%'
        $userId: '%env(DOCUSIGN_USER_ID)%'
        $privateKey: '%env(file:DOCUSIGN_PRIVATE_KEY)%'
        $httpClient: '@docusign.http_client'
        $accountHost: '%env(DOCUSIGN_ACCOUNT_HOST)%'
        $apiHost: '%env(DOCUSIGN_API_HOST)%'
        $debug: '%kernel.debug%'

    currency_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::CURRENCY

    currency_formatter_no_decimal:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::CURRENCY
        calls:
            - method: setAttribute
              arguments:
                - !php/const \NumberFormatter::MAX_FRACTION_DIGITS
                - 0

    number_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::DEFAULT_STYLE

    date_formatter:
        public: true
        class: IntlDateFormatter
        arguments:
            - '%locale%'
            - !php/const \IntlDateFormatter::MEDIUM
            - !php/const \IntlDateFormatter::SHORT

    UserAgentParser\Provider\WhichBrowser:
        class: UserAgentParser\Provider\WhichBrowser

    UserAgentParser\Provider\PiwikDeviceDetector:
        class: UserAgentParser\Provider\PiwikDeviceDetector

    UserAgentParser\Provider\Chain:
        $providers:
            - '@UserAgentParser\Provider\WhichBrowser'
            - '@UserAgentParser\Provider\PiwikDeviceDetector'
