parameters:
    # To delete
    ekomi.shop_id: null
    ekomi.password: null
    ekomi.url: 'https://srr.ekomi.com/add-recipient'
    # End of to delete
    sonata_cache.servers:
        -
            domain: www.local.unilend.fr
            ip: 192.168.110.12
            port: 443
    dbal_wrapper_class: Unilend\Doctrine\DBAL\Connection
    dbal_driver_class: Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver
    locale: fr_FR
    server1.memcache_host: 127.0.0.1
    server1.memcache_port: 11211
    image_resize:
        projets:
            authorized:
                - 72
                - 169
            height: 1365
            width: 2048
    router.request_context.scheme: https
    path.static: /data/sites/unilend/public/default/
    path.shared: /data/medias/nfs/
    path.shared_tmp: '%path.shared%tmp/'
    path.user: '%path.shared%var/'
    path.sftp: '%path.shared%sftp/'
    path.protected: '%path.shared%protected/'
    path.logs: /data/log
    path.payline: '%path.logs%/payline'
    mapbox.token: ''
    security.bcrypt.cost: 13
    translation_cache_path: '%kernel.cache_dir%/translations'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $consoleLogger: '@monolog.logger.console'
            $wsClientLogger: '@monolog.logger.wsclient'
            $defaultLocale: '%locale%'
            $sharedTemporaryPath: '%path.shared_tmp%'
            $templateMessageFQCN: 'Unilend\SwiftMailer\TemplateMessage'
            $frontUrl: '%router.request_context.scheme%://%env(HOST_DEFAULT_URL)%'
            $adminUrl: '%router.request_context.scheme%://%env(HOST_ADMIN_URL)%'
            $rootDirectory: '%kernel.root_dir%'
            $numberFormatter: '@number_formatter'
            $currencyFormatter: '@currency_formatter'
            $environment: '%kernel.environment%'
            $protectedPath: '%path.protected%'
            $staticPath: '%path.static%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Unilend\:
        resource: '%kernel.project_dir%/src/*'
        # The directory Unilend contains the legacy bundles. The services are managed by their own configurations.
        exclude: '%kernel.project_dir%/src/{Console,Entity,Migrations,Tests,Unilend,Kernel.php}'

    # Define the memcache adaptor as the application default cache globally in order to have the right adaptor when autowiring Psr\Cache\CacheItemPoolInterface
    # Since we use the cache/adapter-bundle as the cache system, the configuration framework.cache.app won't work.
    # It can be removed once TECH-333 will be done.
    cache.app: '@memcache.default'
    # Define the logger service as public so we can continue to have access to it via $container->get().
    # But $container->get('logger') is deprecated, do not use it any more.
    logger:
        alias: 'monolog.logger'
        public: true

    Unilend\Service\Translation\TranslationLoader:
        tags:
            - { name: translation.loader, alias: db }

    Unilend\Service\WebServiceClient\CallHistoryManager:
        arguments:
            $alertChannel: '%slack.default_channel%'
            $mongoDBLogger: '@monolog.logger.mongodb'
            $mongoLogEnabled: "%mongodb.log.enable%"

    soap_client.altares_identity:
        class: SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_identity%'
            $options:
                exception: 1
                trace: 1

    soap_client.altares_risque:
        class: SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_risk%'
            $options:
                exception: 1
                trace: 1

    soap_client.altares_risk_monitoring:
        class: SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_risk_monitoring%'
            $options:
                exception: 1
                trace: 1

    Unilend\Service\WebServiceClient\EulerHermesManager:
        $client: '@eight_points_guzzle.client.euler'
        $gradingApiKey: '%euler.grading_key%'
        $accountApiKey: '%euler.account_key%'
        $accountPassword: '%euler.password%'
        $accountEmail: '%euler.email%'

    Unilend\Service\WebServiceClient\CodinfManager:
        $client: '@eight_points_guzzle.client.codinf'
        $user: '%codinf.user%'
        $password: '%codinf.password%'

    Unilend\Service\WebServiceClient\InfolegaleManager:
        $client: '@eight_points_guzzle.client.infolegale'
        $token: '%infolegale.token%'

    Unilend\Service\WebServiceClient\InfogreffeManager:
        $login: '%infogreffe.login%'
        $password: '%infogreffe.password%'
        $wsdl: '%infogreffe.wsdl_url%'
        $url: '%infogreffe.url%'

    Unilend\Service\WebServiceClient\AltaresManager:
        $login: '%altares.login%'
        $password: '%altares.password%'
        $identityClient: '@soap_client.altares_identity'
        $riskClient: '@soap_client.altares_risque'
        $riskMonitoringClient: '@soap_client.altares_risk_monitoring'

    Unilend\Service\WebServiceClient\EllisphereManager:
        $client: '@eight_points_guzzle.client.ellisphere'
        $contractId: '%ellisphere.contract_id%'
        $userPrefix: '%ellisphere.user_prefix%'
        $userId: '%ellisphere.user_id%'
        $password: '%ellisphere.password%'

    Unilend\Service\WebServiceClient\GreenPointManager:
        $client: '@eight_points_guzzle.client.greenpoint'
        $login: '%greenpoint.login%'
        $password: '%greenpoint.password%'

    Unilend\Service\WebServiceClient\InseeManager:
        $client: '@eight_points_guzzle.client.insee'

    Unilend\Service\Product\ProductManager: '@Unilend\Service\PartnerProductManager'

    # The "public: true" can be removed if there is no more access via $container->get()
    Unilend\Service\AcceptedBidAndLoanNotificationSender:
        public: true

    Unilend\Service\SalesforceManager:
        $extractionDir: '%path.protected%dataloader'
        $configDir: '%kernel.root_dir%/dataloader/conf'

    Unilend\Service\LocationManager:
        $mapboxToken: '%mapbox.token%'

    Unilend\Service\Ekomi:
        $url: '%ekomi.url%'
        $shopId: '%ekomi.shop_id%'
        $password: '%ekomi.password%'

    Unilend\Service\PaylineManager:
        $merchantId: '%payline.merchant_id%'
        $accessKey: '%payline.access_key%'
        $logPath: '%path.payline%'

    Unilend\Service\AttachmentManager:
        $uploadRootDirectory: '%path.protected%attachments'
        $tmpDirectory: '%path.shared_tmp%'

    Unilend\Service\GoogleRecaptchaManager:
        $client: '@eight_points_guzzle.client.google_recaptcha'
        $secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'

    currency_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::CURRENCY

    number_formatter:
        public: true
        class: NumberFormatter
        arguments:
            - '%locale%'
            - !php/const \NumberFormatter::DEFAULT_STYLE

    date_formatter:
        public: true
        class: IntlDateFormatter
        arguments:
            - '%locale%'
            - !php/const \IntlDateFormatter::MEDIUM
            - !php/const \IntlDateFormatter::SHORT

    UserAgentParser\Provider\WhichBrowser:
        class: UserAgentParser\Provider\WhichBrowser

    UserAgentParser\Provider\PiwikDeviceDetector:
        class: UserAgentParser\Provider\PiwikDeviceDetector

    UserAgentParser\Provider\Chain:
        $providers:
            - '@UserAgentParser\Provider\WhichBrowser'
            - '@UserAgentParser\Provider\PiwikDeviceDetector'

    Unilend\Security\BCryptPasswordEncoder:
        $cost: '%security.bcrypt.cost%'

    Unilend\Service\Front\UniversignManager:
        $universignURL: '%url.universign%'
