parameters:
    url.universign: ''
    payline.merchant_id: ''
    payline.access_key: ''
    euler.account_key: ''
    euler.grading_key: ''
    euler.url: 'https://api-demo.single-invoice.co/v2.0/'
    euler.email: ''
    euler.password: ''
    codinf.user: null
    codinf.password: null
    codinf.url: 'https://www.codinf.fr/incidents/'
    infolegale.token: ''
    infolegale.url: 'https://wspreprod.infolegale.fr/'
    infogreffe.login: ''
    infogreffe.password: ''
    infogreffe.url: 'https://qual.infogreffe.fr:443/WSContextInfogreffe/INFOGREFFE'
    infogreffe.wsdl_url: 'https://qual.infogreffe.fr/InfogreffeWs/wsdl.jsp'
    altares.login: ''
    altares.password: ''
    altares.wsdl_url_identity: 'https://intuiz.altares.fr/iws-v3.13/services/CallistoIdentite?wsdl'
    altares.wsdl_url_risk: 'https://intuiz.altares.fr/iws-v3.13/services/CallistoRisque?wsdl'
    altares.wsdl_url_risk_monitoring: 'https://intuiz.altares.fr/iws-v3.13/services/CallistoAlerte?wsdl'
    ellisphere.contract_id: null
    ellisphere.user_prefix: null
    ellisphere.user_id: null
    ellisphere.password: null
    ellisphere.url: 'https://services.data-access-gateway.com/1/rest/'
    greenpoint.url: 'https://id-control.fr/api/'
    greenpoint.login: ''
    greenpoint.password: ''
    slack.default_channel: '#it-testing'
    new_relic.front_app_name: Unilend-front
    new_relic.back_app_name: Unilend-backoffice
    new_relic.console_app_name: Unilend-batchjobs
    slack.team_id: ''
    slack.command_token: ''
    slack.monitoring_channel: '#it-monitoring'
    slack.default_username: Unilend
    slack.endpoint: 'https://hooks.slack.com/services'
    mailchimp.api_key: '-'
    mailchimp.webhook_secret: ''
    mailchimp.list_id: ''
    mailchimp.gdpr_segment_id: ''
