services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $logger: '@monolog.logger.wsclient'

    Unilend\Bundle\WSClientBundle\:
        resource: '%kernel.project_dir%/src/Unilend/Bundle/WSClientBundle/*'
        exclude: '%kernel.project_dir%/src/Unilend/Bundle/WSClientBundle/Entity'

    Unilend\Bundle\WSClientBundle\Service\CallHistoryManager:
        arguments:
            $alertChannel: '%slack.default_channel%'
            $mongoDBLogger: '@monolog.logger.mongodb'

    soap_client.altares_identity:
        class: \SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_identity%'
            $options:
                exception: 1
                trace: 1

    soap_client.altares_risque:
        class: \SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_risk%'
            $options:
                exception: 1
                trace: 1

    soap_client.altares_risk_monitoring:
        class: \SoapClient
        arguments:
            $wsdl: '%altares.wsdl_url_risk_monitoring%'
            $options:
                exception: 1
                trace: 1

    Unilend\Bundle\WSClientBundle\Service\EulerHermesManager:
        $client: '@eight_points_guzzle.client.euler'
        $gradingApiKey: '%euler.grading_key%'
        $accountApiKey: '%euler.account_key%'
        $accountPassword: '%euler.password%'
        $accountEmail: '%euler.email%'

    Unilend\Bundle\WSClientBundle\Service\CodinfManager:
        $client: '@eight_points_guzzle.client.codinf'
        $user: '%codinf.user%'
        $password: '%codinf.password%'

    Unilend\Bundle\WSClientBundle\Service\InfolegaleManager:
        $client: '@eight_points_guzzle.client.infolegale'
        $token: '%infolegale.token%'

    Unilend\Bundle\WSClientBundle\Service\InfogreffeManager:
        $login: '%infogreffe.login%'
        $password: '%infogreffe.password%'
        $wsdl: '%infogreffe.wsdl_url%'
        $url: '%infogreffe.url%'

    Unilend\Bundle\WSClientBundle\Service\AltaresManager:
        $login: '%altares.login%'
        $password: '%altares.password%'
        $identityClient: '@soap_client.altares_identity'
        $riskClient: '@soap_client.altares_risque'
        $riskMonitoringClient: '@soap_client.altares_risk_monitoring'

    Unilend\Bundle\WSClientBundle\Service\EllisphereManager:
        $client: '@eight_points_guzzle.client.ellisphere'
        $contractId: '%ellisphere.contract_id%'
        $userPrefix: '%ellisphere.user_prefix%'
        $userId: '%ellisphere.user_id%'
        $password: '%ellisphere.password%'
