home:
  path: /
login:
  path: /login
privacy:                               
  path: /politique-de-confidentialite
legal_notice:                          
  path: /mentions-legales
inscription_finalisation:
  path: /finalisation-inscription/{temporaryTokenHash}/{clientHash}
tos:                                   
  path: /cgu
404:
  path: /404
403:
  path: /403
password_change:                       
  path: /password/change/{temporaryTokenHash}/{clientHash}
password_request:                      
  path: /password/request
participation_index:                   
  path: /participation
participation_project_view:            
  path: /participation/project/{projectHash}
participation_project_confidentiality: 
  path: /participation/project/{projectHash}/confidentiality
habilitation:                          
  path: /habilitations
arrangement_kanban:                    
  path: /arrangement
arrangement_project_view:              
  path: /arrangement/project/{projectHash}
arrangement_project_publish:           
  path: /arrangement/project/{projectHash}/publication
arrangement_project_syndicate:         
  path: /arrangement/project/{projectHash}/syndication
arrangement_project_create:            
  path: /arrangement/project
arrangement_document_sign_result:
  path: /arrangemeent/document/{documentId}/signature/result
image:
  path: /images/{imageFileName}
  requirements:
    imageFileName: .+
