<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210510135344 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'CALS-3413 [Core] hydrate core_naf_nace table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<SQL
INSERT INTO `core_naf_nace`
    (naf_code, naf_title, nace_code, nace_title)
VALUES
    ('0111Z', "Culture de céréales (à l'exception du riz), de légumineuses et de graines oléagineuses", 'A1.1.1', "A1.1.1 - Growing of cereals (except rice), leguminous crops and oil seeds"),
    ('0112Z', "Culture du riz", 'A1.1.2', "A1.1.2 - Growing of rice"),
    ('0113Z', "Culture de légumes, de melons, de racines et de tubercules", 'A1.1.3', "A1.1.3 - Growing of vegetables and melons, roots and tubers"),
    ('0114Z', "Culture de la canne à sucre", 'A1.1.4', "A1.1.4 - Growing of sugar cane"),
    ('0115Z', "Culture du tabac", 'A1.1.5', "A1.1.5 - Growing of tobacco"),
    ('0116Z', "Culture de plantes à fibres", 'A1.1.6', "A1.1.6 - Growing of fibre crops"),
    ('0119Z', "Autres cultures non permanentes", 'A1.1.9', "A1.1.9 - Growing of other non-perennial crops"),
    ('0121Z', "Culture de la vigne", 'A1.2.1', "A1.2.1 - Growing of grapes"),
    ('0122Z', "Culture de fruits tropicaux et subtropicaux", 'A1.2.2', "A1.2.2 - Growing of tropical and subtropical fruits"),
    ('0123Z', "Culture d'agrumes", 'A1.2.3', "A1.2.3 - Growing of citrus fruits"),
    ('0124Z', "Culture de fruits à pépins et à noyau", 'A1.2.4', "A1.2.4 - Growing of pome fruits and stone fruits"),
    ('0125Z', "Culture d'autres fruits d'arbres ou d'arbustes et de fruits à coque", 'A1.2.5', "A1.2.5 - Growing of other tree and bush fruits and nuts"),
    ('0126Z', "Culture de fruits oléagineux", 'A1.2.6', "A1.2.6 - Growing of oleaginous fruits"),
    ('0127Z', "Culture de plantes à boissons", 'A1.2.7', "A1.2.7 - Growing of beverage crops"),
    ('0128Z', "Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques", 'A1.2.8', "A1.2.8 - Growing of spices, aromatic, drug and pharmaceutical crops"),
    ('0129Z', "Autres cultures permanentes", 'A1.2.9', "A1.2.9 - Growing of other perennial crops"),
    ('0130Z', "Reproduction de plantes", 'A1.3.0', "A1.3.0 - Plant propagation"),
    ('0141Z', "Élevage de vaches laitières", 'A1.4.1', "A1.4.1 - Raising of dairy cattle"),
    ('0142Z', "Élevage d'autres bovins et de buffles", 'A1.4.2', "A1.4.2 - Raising of other cattle and buffaloes"),
    ('0143Z', "Élevage de chevaux et d'autres équidés", 'A1.4.3', "A1.4.3 - Raising of horses and other equines"),
    ('0144Z', "Élevage de chameaux et d'autres camélidés", 'A1.4.4', "A1.4.4 - Raising of camels and camelids"),
    ('0145Z', "Élevage d'ovins et de caprins", 'A1.4.5', "A1.4.5 - Raising of sheep and goats"),
    ('0146Z', "Élevage de porcins", 'A1.4.6', "A1.4.6 - Raising of swine/pigs"),
    ('0147Z', "Élevage de volailles", 'A1.4.7', "A1.4.7 - Raising of poultry"),
    ('0149Z', "Élevage d'autres animaux", 'A1.4.9', "A1.4.9 - Raising of other animals"),
    ('0150Z', "Culture et élevage associés", 'A1.5.0', "A1.5.0 - Mixed farming"),
    ('0161Z', "Activités de soutien aux cultures", 'A1.6.1', "A1.6.1 - Support activities for crop production"),
    ('0162Z', "Activités de soutien à la production animale", 'A1.6.2', "A1.6.2 - Support activities for animal production"),
    ('0163Z', "Traitement primaire des récoltes", 'A1.6.3', "A1.6.3 - Post-harvest crop activities"),
    ('0164Z', "Traitement des semences", 'A1.6.4', "A1.6.4 - Seed processing for propagation"),
    ('0170Z', "Chasse, piégeage et services annexes", 'A1.7.0', "A1.7.0 - Hunting, trapping and related service activities"),
    ('0210Z', "Sylviculture et autres activités forestières", 'A2.1.0', "A2.1.0 - Silviculture and other forestry activities"),
    ('0220Z', "Exploitation forestière", 'A2.2.0', "A2.2.0 - Logging"),
    ('0230Z', "Récolte de produits forestiers non ligneux poussant à l'état sauvage", 'A2.3.0', "A2.3.0 - Gathering of wild growing non-wood products"),
    ('0240Z', "Services de soutien à l'exploitation forestière", 'A2.4.0', "A2.4.0 - Support services to forestry"),
    ('0311Z', "Pêche en mer", 'A3.1.1', "A3.1.1 - Marine fishing"),
    ('0312Z', "Pêche en eau douce", 'A3.1.2', "A3.1.2 - Freshwater fishing"),
    ('0321Z', "Aquaculture en mer", 'A3.2.1', "A3.2.1 - Marine aquaculture"),
    ('0322Z', "Aquaculture en eau douce", 'A3.2.2', "A3.2.2 - Freshwater aquaculture"),
    ('0510Z', "Extraction de houille", 'B5.1.0', "B5.1.0 - Mining of hard coal"),
    ('0520Z', "Extraction de lignite", 'B5.2.0', "B5.2.0 - Mining of lignite"),
    ('0610Z', "Extraction de pétrole brut", 'B6.1.0', "B6.1.0 - Extraction of crude petroleum"),
    ('0620Z', "Extraction de gaz naturel", 'B6.2.0', "B6.2.0 - Extraction of natural gas"),
    ('0710Z', "Extraction de minerais de fer", 'B7.1.0', "B7.1.0 - Mining of iron ores"),
    ('0721Z', "Extraction de minerais d'uranium et de thorium", 'B7.2.1', "B7.2.1 - Mining of uranium and thorium ores"),
    ('0729Z', "Extraction d'autres minerais de métaux non ferreux", 'B7.2.9', "B7.2.9 - Mining of other non-ferrous metal ores"),
    ('0811Z', "Extraction de pierres ornementales et de construction, de calcaire industriel, de gypse, de craie et d'ardoise", 'B8.1.1', "B8.1.1 - Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate"),
    ('0812Z', "Exploitation de gravières et sablières, extraction d’argiles et de kaolin", 'B8.1.2', "B8.1.2 - Operation of gravel and sand pits; mining of clays and kaolin"),
    ('0891Z', "Extraction des minéraux chimiques et d'engrais minéraux", 'B8.9.1', "B8.9.1 - Mining of chemical and fertiliser minerals"), 
    ('0892Z', "Extraction de tourbe", 'B8.9.2', "B8.9.2 - Extraction of peat"),
    ('0893Z', "Production de sel", 'B8.9.3', "B8.9.3 - Extraction of salt"), 
    ('0899Z', "Autres activités extractives n.c.a.", 'B8.9.9', "B8.9.9 - Other mining and quarrying n.e.c."),
    ('0910Z', "Activités de soutien à l'extraction d'hydrocarbures", 'B9.1.0', "B9.1.0 - Support activities for petroleum and natural gas extraction"),
    ('0990Z', "Activités de soutien aux autres industries extractives", 'B9.9.0', "B9.9.0 - Support activities for other mining and quarrying"), 
    ('1011Z', "Transformation et conservation de la viande de boucherie", 'C10.1.1', "C10.1.1 - Processing and preserving of meat"),
    ('1012Z', "Transformation et conservation de la viande de volaille", 'C10.1.2', "C10.1.2 - Processing and preserving of poultry meat"),
    ('1013A', "Préparation industrielle de produits à base de viande", 'C10.1.3', "C10.1.3 - Production of meat and poultry meat products"),
    ('1013B', "Charcuterie", 'C10.1.3', "C10.1.3 - Production of meat and poultry meat products"),
    ('1020Z', "Transformation et conservation de poisson, de crustacés et de mollusques", 'C10.2.0', "C10.2.0 - Processing and preserving of fish, crustaceans and molluscs"),
    ('1031Z', "Transformation et conservation de pommes de terre", 'C10.3.1', "C10.3.1 - Processing and preserving of potatoes"),
    ('1032Z', "Préparation de jus de fruits et légumes", 'C10.3.2', "C10.3.2 - Manufacture of fruit and vegetable juice"),
    ('1039A', "Autre transformation et conservation de légumes", 'C10.3.9', "C10.3.9 - Other processing and preserving of fruit and vegetables"),
    ('1039B', "Transformation et conservation de fruits", 'C10.3.9', "C10.3.9 - Other processing and preserving of fruit and vegetables"),
    ('1041A', "Fabrication d'huiles et graisses brutes", 'C10.4.1', "C10.4.1 - Manufacture of oils and fats"),
    ('1041B', "Fabrication d'huiles et graisses raffinées", 'C10.4.1', "C10.4.1 - Manufacture of oils and fats"),
    ('1042Z', "Fabrication de margarine et graisses comestibles similaires", 'C10.4.2', "C10.4.2 - Manufacture of margarine and similar edible fats"),
    ('1051A', "Fabrication de lait liquide et de produits frais", 'C10.5.1', "C10.5.1 - Operation of dairies and cheese making"),
    ('1051B', "Fabrication de beurre", 'C10.5.1', "C10.5.1 - Operation of dairies and cheese making"),
    ('1051C', "Fabrication de fromage", 'C10.5.1', "C10.5.1 - Operation of dairies and cheese making"),
    ('1051D', "Fabrication d'autres produits laitiers", 'C10.5.1', "C10.5.1 - Operation of dairies and cheese making"),
    ('1052Z', "Fabrication de glaces et sorbets", 'C10.5.2', "C10.5.2 - Manufacture of ice cream"),
    ('1061A', "Meunerie", 'C10.6.1', "C10.6.1 - Manufacture of grain mill products"),
    ('1061B', "Autres activités du travail des grains", 'C10.6.1', "C10.6.1 - Manufacture of grain mill products"),
    ('1062Z', "Fabrication de produits amylacés", 'C10.6.2', "C10.6.2 - Manufacture of starches and starch products"),
    ('1071A', "Fabrication industrielle de pain et de pâtisserie fraîche", 'C10.7.1', "C10.7.1 - Manufacture of bread; manufacture of fresh pastry goods and cakes"),
    ('1071B', "Cuisson de produits de boulangerie", 'C10.7.1', "C10.7.1 - Manufacture of bread; manufacture of fresh pastry goods and cakes"),
    ('1071C', "Boulangerie et boulangerie-pâtisserie", 'C10.7.1', "C10.7.1 - Manufacture of bread; manufacture of fresh pastry goods and cakes"),
    ('1071D', "Pâtisserie", 'C10.7.1', "C10.7.1 - Manufacture of bread; manufacture of fresh pastry goods and cakes"),
    ('1072Z', "Fabrication de biscuits, biscottes et pâtisseries de conservation", 'C10.7.2', "C10.7.2 - Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes"),
    ('1073Z', "Fabrication de pâtes alimentaires", 'C10.7.3', "C10.7.3 - Manufacture of macaroni, noodles, couscous and similar farinaceous products"),
    ('1081Z', "Fabrication de sucre", 'C10.8.1', "C10.8.1 - Manufacture of sugar"),
    ('1082Z', "Fabrication de cacao, chocolat et de produits de confiserie", 'C10.8.2', "C10.8.2 - Manufacture of cocoa, chocolate and sugar confectionery"),
    ('1083Z', "Transformation du thé et du café", 'C10.8.3', "C10.8.3 - Processing of tea and coffee"),
    ('1084Z', "Fabrication de condiments et assaisonnements", 'C10.8.4', "C10.8.4 - Manufacture of condiments and seasonings"),
    ('1085Z', "Fabrication de plats préparés", 'C10.8.5', "C10.8.5 - Manufacture of prepared meals and dishes"),
    ('1086Z', "Fabrication d'aliments homogénéisés et diététiques", 'C10.8.6', "C10.8.6 - Manufacture of homogenised food preparations and dietetic food"),
    ('1089Z', "Fabrication d'autres produits alimentaires n.c.a.", 'C10.8.9', "C10.8.9 - Manufacture of other food products n.e.c."),
    ('1091Z', "Fabrication d'aliments pour animaux de ferme", 'C10.9.1', "C10.9.1 - Manufacture of prepared feeds for farm animals"),
    ('1092Z', "Fabrication d'aliments pour animaux de compagnie", 'C10.9.2', "C10.9.2 - Manufacture of prepared pet foods"),
    ('1101Z', "Production de boissons alcooliques distillées", 'C11.0.1', "C11.0.1 - Distilling, rectifying and blending of spirits"),
    ('1102A', "Fabrication de vins effervescents", 'C11.0.2', "C11.0.2 - Manufacture of wine from grape"),
    ('1102B', "Vinification", 'C11.0.2', "C11.0.2 - Manufacture of wine from grape"),
    ('1103Z', "Fabrication de cidre et de vins de fruits", 'C11.0.3', "C11.0.3 - Manufacture of cider and other fruit wines"), 
    ('1104Z', "Production d'autres boissons fermentées non distillées", 'C11.0.4', "C11.0.4 - Manufacture of other non-distilled fermented beverages"),
    ('1105Z', "Fabrication de bière", 'C11.0.5', "C11.0.5 - Manufacture of beer"),
    ('1106Z', "Fabrication de malt", 'C11.0.6', "C11.0.6 - Manufacture of malt"),
    ('1107A', "Industrie des eaux de table", 'C11.0.7', "C11.0.7 - Manufacture of soft drinks; production of mineral waters and other bottled waters"),
    ('1107B', "Production de boissons rafraîchissantes", 'C11.0.7', "C11.0.7 - Manufacture of soft drinks; production of mineral waters and other bottled waters"),
    ('1200Z', "Fabrication de produits à base de tabac", 'C12.0.0', "C12.0.0 - Manufacture of tobacco products"),
    ('1310Z', "Préparation de fibres textiles et filature", 'C13.1.0', "C13.1.0 - Preparation and spinning of textile fibres"),
    ('1320Z', "Tissage", 'C13.2.0', "C13.2.0 - Weaving of textiles"),
    ('1330Z', "Ennoblissement textile", 'C13.3.0', "C13.3.0 - Finishing of textiles"),
    ('1391Z', "Fabrication d'étoffes à mailles", 'C13.9.1', "C13.9.1 - Manufacture of knitted and crocheted fabrics"),
    ('1392Z', "Fabrication d'articles textiles, sauf habillement", 'C13.9.2', "C13.9.2 - Manufacture of made-up textile articles, except apparel"),
    ('1393Z', "Fabrication de tapis et moquettes", 'C13.9.3', "C13.9.3 - Manufacture of carpets and rugs"),
    ('1394Z', "Fabrication de ficelles, cordes et filets", 'C13.9.4', "C13.9.4 - Manufacture of cordage, rope, twine and netting"),
    ('1395Z', "Fabrication de non-tissés, sauf habillement", 'C13.9.5', "C13.9.5 - Manufacture of non-wovens and articles made from non-wovens, except apparel"),
    ('1396Z', "Fabrication d'autres textiles techniques et industriels", 'C13.9.6', "C13.9.6 - Manufacture of other technical and industrial textiles"),
    ('1399Z', "Fabrication d'autres textiles n.c.a.", 'C13.9.9', "C13.9.9 - Manufacture of other textiles n.e.c."),
    ('1411Z', "Fabrication de vêtements en cuir", 'C14.1.1', "C14.1.1 - Manufacture of leather clothes"),
    ('1412Z', "Fabrication de vêtements de travail", 'C14.1.2', "C14.1.2 - Manufacture of workwear"),
    ('1413Z', "Fabrication de vêtements de dessus", 'C14.1.3', "C14.1.3 - Manufacture of other outerwear"),
    ('1414Z', "Fabrication de vêtements de dessous", 'C14.1.4', "C14.1.4 - Manufacture of underwear"),
    ('1419Z', "Fabrication d'autres vêtements et accessoires", 'C14.1.9', "C14.1.9 - Manufacture of other wearing apparel and accessories"),
    ('1420Z', "Fabrication d'articles en fourrure", 'C14.2.0', "C14.2.0 - Manufacture of articles of fur"),
    ('1431Z', "Fabrication d'articles chaussants à mailles", 'C14.3.1', "C14.3.1 - Manufacture of knitted and crocheted hosiery"),
    ('1439Z', "Fabrication d'autres articles à mailles", 'C14.3.9', "C14.3.9 - Manufacture of other knitted and crocheted apparel"),
    ('1511Z', "Apprêt et tannage des cuirs ; préparation et teinture des fourrures", 'C15.1.1', "C15.1.1 - Tanning and dressing of leather; dressing and dyeing of fur"),
    ('1512Z', "Fabrication d'articles de voyage, de maroquinerie et de sellerie", 'C15.1.2', "C15.1.2 - Manufacture of luggage, handbags and the like, saddlery and harness"),
    ('1520Z', "Fabrication de chaussures", 'C15.2.0', "C15.2.0 - Manufacture of footwear"),
    ('1610A', "Sciage et rabotage du bois, hors imprégnation", 'C16.1.0', "C16.1.0 - Sawmilling and planing of wood"),
    ('1610B', "Imprégnation du bois", 'C16.1.0', "C16.1.0 - Sawmilling and planing of wood"),
    ('1621Z', "Fabrication de placage et de panneaux de bois", 'C16.2.1', "C16.2.1 - Manufacture of veneer sheets and wood-based panels"),
    ('1622Z', "Fabrication de parquets assemblés", 'C16.2.2', "C16.2.2 - Manufacture of assembled parquet floors"),
    ('1623Z', "Fabrication de charpentes et d'autres menuiseries", 'C16.2.3', "C16.2.3 - Manufacture of other builders' carpentry and joinery"),
    ('1624Z', "Fabrication d'emballages en bois", 'C16.2.4', "C16.2.4 - Manufacture of wooden containers"),
    ('1629Z', "Fabrication d'objets divers en bois ; fabrication d'objets en liège, vannerie et sparterie", 'C16.2.9', "C16.2.9 - Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials"),
    ('1711Z', "Fabrication de pâte à papier", 'C17.1.1', "C17.1.1 - Manufacture of pulp"),
    ('1712Z', "Fabrication de papier et de carton", 'C17.1.2', "C17.1.2 - Manufacture of paper and paperboard"),
    ('1721A', "Fabrication de carton ondulé", 'C17.2.1', "C17.2.1 - Manufacture of corrugated paper and paperboard and of containers of paper and paperboard"),
    ('1721B', "Fabrication de cartonnages", 'C17.2.1', "C17.2.1 - Manufacture of corrugated paper and paperboard and of containers of paper and paperboard"), 
    ('1721C', "Fabrication d'emballages en papier", 'C17.2.1', "C17.2.1 - Manufacture of corrugated paper and paperboard and of containers of paper and paperboard"),
    ('1722Z', "Fabrication d'articles en papier à usage sanitaire ou domestique", 'C17.2.2', "C17.2.2 - Manufacture of household and sanitary goods and of toilet requisites"),
    ('1723Z', "Fabrication d'articles de papeterie", 'C17.2.3', "C17.2.3 - Manufacture of paper stationery"),
    ('1724Z', "Fabrication de papiers peints", 'C17.2.4', "C17.2.4 - Manufacture of wallpaper"),
    ('1729Z', "Fabrication d'autres articles en papier ou en carton", 'C17.2.9', "C17.2.9 - Manufacture of other articles of paper and paperboard"),
    ('1811Z', "Imprimerie de journaux", 'C18.1.1', "C18.1.1 - Printing of newspapers"),
    ('1812Z', "Autre imprimerie (labeur)", 'C18.1.2', "C18.1.2 - Other printing"),
    ('1813Z', "Activités de pré-presse", 'C18.1.3', "C18.1.3 - Pre-press and pre-media services"), 
    ('1814Z', "Reliure et activités connexes", 'C18.1.4', "C18.1.4 - Binding and related services"),
    ('1820Z', "Reproduction d'enregistrements", 'C18.2.0', "C18.2.0 - Reproduction of recorded media"),
    ('1910Z', "Cokéfaction", 'C19.1.0', "C19.1.0 - Manufacture of coke oven products"),
    ('1920Z', "Raffinage du pétrole", 'C19.2.0', "C19.2.0 - Manufacture of refined petroleum products"),
    ('2011Z', "Fabrication de gaz industriels", 'C20.1.1', "C20.1.1 - Manufacture of industrial gases"),
    ('2012Z', "Fabrication de colorants et de pigments", 'C20.1.2', "C20.1.2 - Manufacture of dyes and pigments"),
    ('2013A', "Enrichissement et  retraitement de matières nucléaires", 'C20.1.3', "C20.1.3 - Manufacture of other inorganic basic chemicals"),
    ('2013B', "Fabrication d'autres produits chimiques inorganiques de base n.c.a.", 'C20.1.3', "C20.1.3 - Manufacture of other inorganic basic chemicals"),
    ('2014Z', "Fabrication d'autres produits chimiques organiques de base", 'C20.1.4', "C20.1.4 - Manufacture of other organic basic chemicals"),
    ('2015Z', "Fabrication de produits azotés et d'engrais", 'C20.1.5', "C20.1.5 - Manufacture of fertilisers and nitrogen compounds"),
    ('2016Z', "Fabrication de matières plastiques de base", 'C20.1.6', "C20.1.6 - Manufacture of plastics in primary forms"),
    ('2017Z', "Fabrication de caoutchouc synthétique", 'C20.1.7', "C20.1.7 - Manufacture of synthetic rubber in primary forms"),
    ('2020Z', "Fabrication de pesticides et d’autres produits agrochimiques", 'C20.2.0', "C20.2.0 - Manufacture of pesticides and other agrochemical products"),
    ('2030Z', "Fabrication de peintures, vernis, encres et mastics", 'C20.3.0', "C20.3.0 - Manufacture of paints, varnishes and similar coatings, printing ink and mastics"),
    ('2041Z', "Fabrication de savons, détergents et produits d'entretien", 'C20.4.1', "C20.4.1 - Manufacture of soap and detergents, cleaning and polishing preparations"),
    ('2042Z', "Fabrication de parfums et de produits pour la toilette", 'C20.4.2', "C20.4.2 - Manufacture of perfumes and toilet preparations"),
    ('2051Z', "Fabrication de produits explosifs", 'C20.5.1', "C20.5.1 - Manufacture of explosives"),
    ('2052Z', "Fabrication de colles", 'C20.5.2', "C20.5.2 - Manufacture of glues"),
    ('2053Z', "Fabrication d'huiles essentielles", 'C20.5.3', "C20.5.3 - Manufacture of essential oils"),
    ('2059Z', "Fabrication d'autres produits chimiques n.c.a.", 'C20.5.9', "C20.5.9 - Manufacture of other chemical products n.e.c."),
    ('2060Z', "Fabrication de fibres artificielles ou synthétiques", 'C20.6.0', "C20.6.0 - Manufacture of man-made fibres"),
    ('2110Z', "Fabrication de produits pharmaceutiques de base", 'C21.1.0', "C21.1.0 - Manufacture of basic pharmaceutical products"),
    ('2120Z', "Fabrication de préparations pharmaceutiques", 'C21.2.0', "C21.2.0 - Manufacture of pharmaceutical preparations"),
    ('2211Z', "Fabrication et rechapage de pneumatiques", 'C22.1.1', "C22.1.1 - Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres"),
    ('2219Z', "Fabrication d'autres articles en caoutchouc", 'C22.1.9', "C22.1.9 - Manufacture of other rubber products"),
    ('2221Z', "Fabrication de plaques, feuilles, tubes et profilés en matières plastiques", 'C22.2.1', "C22.2.1 - Manufacture of plastic plates, sheets, tubes and profiles"),
    ('2222Z', "Fabrication d'emballages en matières plastiques", 'C22.2.2', "C22.2.2 - Manufacture of plastic packing goods"),
    ('2223Z', "Fabrication d'éléments en matières plastiques pour la construction", 'C22.2.3', "C22.2.3 - Manufacture of buildersâ€™ ware of plastic"),
    ('2229A', "Fabrication de pièces techniques à base de matières plastiques", 'C22.2.9', "C22.2.9 - Manufacture of other plastic products"),
    ('2229B', "Fabrication de produits de consommation courante en matières plastiques", 'C22.2.9', "C22.2.9 - Manufacture of other plastic products"),
    ('2311Z', "Fabrication de verre plat", 'C23.1.1', "C23.1.1 - Manufacture of flat glass"),
    ('2312Z', "Façonnage et transformation du verre plat", 'C23.1.2', "C23.1.2 - Shaping and processing of flat glass"),
    ('2313Z', "Fabrication de verre creux", 'C23.1.3', "C23.1.3 - Manufacture of hollow glass"),
    ('2314Z', "Fabrication de fibres de verre", 'C23.1.4', "C23.1.4 - Manufacture of glass fibres"),
    ('2319Z', "Fabrication et façonnage d'autres articles en verre, y compris verre technique", 'C23.1.9', "C23.1.9 - Manufacture and processing of other glass, including technical glassware"),
    ('2320Z', "Fabrication de produits réfractaires", 'C23.2.0', "C23.2.0 - Manufacture of refractory products"),
    ('2331Z', "Fabrication de carreaux en céramique", 'C23.3.1', "C23.3.1 - Manufacture of ceramic tiles and flags"),
    ('2332Z', "Fabrication de briques, tuiles et produits de construction, en terre cuite", 'C23.3.2', "C23.3.2 - Manufacture of bricks, tiles and construction products, in baked clay"),
    ('2341Z', "Fabrication d'articles céramiques à usage domestique ou ornemental", 'C23.4.1', "C23.4.1 - Manufacture of ceramic household and ornamental articles"),
    ('2342Z', "Fabrication d'appareils sanitaires en céramique", 'C23.4.2', "C23.4.2 - Manufacture of ceramic sanitary fixtures"),
    ('2343Z', "Fabrication d'isolateurs et pièces isolantes en céramique", 'C23.4.3', "C23.4.3 - Manufacture of ceramic insulators and insulating fittings"),
    ('2344Z', "Fabrication d'autres produits céramiques à usage technique", 'C23.4.4', "C23.4.4 - Manufacture of other technical ceramic products"),
    ('2349Z', "Fabrication d'autres produits céramiques", 'C23.4.9', "C23.4.9 - Manufacture of other ceramic products"),
    ('2351Z', "Fabrication de ciment", 'C23.5.1', "C23.5.1 - Manufacture of cement"),
    ('2352Z', "Fabrication de chaux et plâtre", 'C23.5.2', "C23.5.2 - Manufacture of lime and plaster"),
    ('2361Z', "Fabrication d'éléments en béton pour la construction", 'C23.6.1', "C23.6.1 - Manufacture of concrete products for construction purposes"),
    ('2362Z', "Fabrication d'éléments en plâtre pour la construction", 'C23.6.2', "C23.6.2 - Manufacture of plaster products for construction purposes"),
    ('2363Z', "Fabrication de béton prêt à l'emploi", 'C23.6.3', "C23.6.3 - Manufacture of ready-mixed concrete"),
    ('2364Z', "Fabrication de mortiers et bétons secs", 'C23.6.4', "C23.6.4 - Manufacture of mortars"),
    ('2365Z', "Fabrication d'ouvrages en fibre-ciment", 'C23.6.5', "C23.6.5 - Manufacture of fibre cement"),
    ('2369Z', "Fabrication d'autres ouvrages en béton, en ciment ou en plâtre", 'C23.6.9', "C23.6.9 - Manufacture of other articles of concrete, plaster and cement"),
    ('2370Z', "Taille, façonnage et finissage de pierres", 'C23.7.0', "C23.7.0 - Cutting, shaping and finishing of stone"),
    ('2391Z', "Fabrication de produits abrasifs", 'C23.9.1', "C23.9.1 - Production of abrasive products"),
    ('2399Z', "Fabrication d'autres produits minéraux non métalliques n.c.a.", 'C23.9.9', "C23.9.9 - Manufacture of other non-metallic mineral products n.e.c."),
    ('2410Z', "Sidérurgie", 'C24.1.0', "C24.1.0 - Manufacture of basic iron and steel and of ferro-alloys "),
    ('2420Z', "Fabrication de tubes, tuyaux, profilés creux et accessoires correspondants en acier", 'C24.2.0', "C24.2.0 - Manufacture of tubes, pipes, hollow profiles and related fittings, of steel"), 
    ('2431Z', "Étirage à froid de barres", 'C24.3.1', "C24.3.1 - Cold drawing of bars"),
    ('2432Z', "Laminage à froid de feuillards", 'C24.3.2', "C24.3.2 - Cold rolling of narrow strip"),
    ('2433Z', "Profilage à froid par formage ou pliage", 'C24.3.3', "C24.3.3 - Cold forming or folding"),
    ('2434Z', "Tréfilage à froid", 'C24.3.4', "C24.3.4 - Cold drawing of wire"),
    ('2441Z', "Production de métaux précieux", 'C24.4.1', "C24.4.1 - Precious metals production"),
    ('2442Z', "Métallurgie de l'aluminium", 'C24.4.2', "C24.4.2 - Aluminium production"),
    ('2443Z', "Métallurgie du plomb, du zinc ou de l'étain", 'C24.4.3', "C24.4.3 - Lead, zinc and tin production"),
    ('2444Z', "Métallurgie du cuivre", 'C24.4.4', "C24.4.4 - Copper production"),
    ('2445Z', "Métallurgie des autres métaux non ferreux", 'C24.4.5', "C24.4.5 - Other non-ferrous metal production"),
    ('2446Z', "Élaboration et transformation de matières nucléaires", 'C24.4.6', "C24.4.6 - Processing of nuclear fuel "),
    ('2451Z', "Fonderie de fonte", 'C24.5.1', "C24.5.1 - Casting of iron"),
    ('2452Z', "Fonderie d'acier", 'C24.5.2', "C24.5.2 - Casting of steel"),
    ('2453Z', "Fonderie de métaux légers", 'C24.5.3', "C24.5.3 - Casting of light metals"),
    ('2454Z', "Fonderie d'autres métaux non ferreux", 'C24.5.4', "C24.5.4 - Casting of other non-ferrous metals"),
    ('2511Z', "Fabrication de structures métalliques et de parties de structures", 'C25.1.1', "C25.1.1 - Manufacture of metal structures and parts of structures"),
    ('2512Z', "Fabrication de portes et fenêtres en métal", 'C25.1.2', "C25.1.2 - Manufacture of doors and windows of metal"),
    ('2521Z', "Fabrication de radiateurs et de chaudières pour le chauffage central", 'C25.2.1', "C25.2.1 - Manufacture of central heating radiators and boilers"),
    ('2529Z', "Fabrication d'autres réservoirs, citernes et conteneurs métalliques", 'C25.2.9', "C25.2.9 - Manufacture of other tanks, reservoirs and containers of metal"),
    ('2530Z', "Fabrication de générateurs de vapeur, à l'exception des chaudières pour le chauffage central", 'C25.3.0', "C25.3.0 - Manufacture of steam generators, except central heating hot water boilers"),
    ('2540Z', "Fabrication d'armes et de munitions", 'C25.4.0', "C25.4.0 - Manufacture of weapons and ammunition"),
    ('2550A', "Forge, estampage, matriçage; métallurgie des poudres", 'C25.5.0', "C25.5.0 - Forging, pressing, stamping and roll-forming of metal; powder metallurgy"),
    ('2550B', "Découpage, emboutissage", 'C25.5.0', "C25.5.0 - Forging, pressing, stamping and roll-forming of metal; powder metallurgy"),
    ('2561Z', "Traitement et revêtement des métaux", 'C25.6.1', "C25.6.1 - Treatment and coating of metals"),
    ('2562A', "Décolletage", 'C25.6.2', "C25.6.2 - Machining"),
    ('2562B', "Mécanique industrielle", 'C25.6.2', "C25.6.2 - Machining"),
    ('2571Z', "Fabrication de coutellerie", 'C25.7.1', "C25.7.1 - Manufacture of cutlery"),
    ('2572Z', "Fabrication de serrures et de ferrures", 'C25.7.2', "C25.7.2 - Manufacture of locks and hinges"),
    ('2573A', "Fabrication de moules et modèles", 'C25.7.3', "C25.7.3 - Manufacture of tools"),
    ('2573B', "Fabrication d'autres outillages", 'C25.7.3', "C25.7.3 - Manufacture of tools"),
    ('2591Z', "Fabrication de fûts et emballages métalliques similaires", 'C25.9.1', "C25.9.1 - Manufacture of steel drums and similar containers"),
    ('2592Z', "Fabrication d'emballages métalliques légers", 'C25.9.2', "C25.9.2 - Manufacture of light metal packaging "),
    ('2593Z', "Fabrication d'articles en fils métalliques, de chaînes et de ressorts", 'C25.9.3', "C25.9.3 - Manufacture of wire products, chain and springs"),
    ('2594Z', "Fabrication de vis et de boulons", 'C25.9.4', "C25.9.4 - Manufacture of fasteners and screw machine products"),
    ('2599A', "Fabrication d'articles métalliques ménagers", 'C25.9.9', "C25.9.9 - Manufacture of other fabricated metal products n.e.c."),
    ('2599B', "Fabrication d'autres articles métalliques", 'C25.9.9', "C25.9.9 - Manufacture of other fabricated metal products n.e.c."),
    ('2611Z', "Fabrication de composants électroniques", 'C26.1.1', "C26.1.1 - Manufacture of electronic components"),
    ('2612Z', "Fabrication de cartes électroniques assemblées", 'C26.1.2', "C26.1.2 - Manufacture of loaded electronic boards"),
    ('2620Z', "Fabrication d'ordinateurs et d'équipements périphériques", 'C26.2.0', "C26.2.0 - Manufacture of computers and peripheral equipment"),
    ('2630Z', "Fabrication d'équipements de communication", 'C26.3.0', "C26.3.0 - Manufacture of communication equipment"), 
    ('2640Z', "Fabrication de produits électroniques grand public", 'C26.4.0', "C26.4.0 - Manufacture of consumer electronics"),
    ('2651A', "Fabrication d'équipements d'aide à la navigation", 'C26.5.1', "C26.5.1 - Manufacture of instruments and appliances for measuring, testing and navigation"),
    ('2651B', "Fabrication d'instrumentation scientifique et technique", 'C26.5.1', "C26.5.1 - Manufacture of instruments and appliances for measuring, testing and navigation"),
    ('2652Z', "Horlogerie", 'C26.5.2', "C26.5.2 - Manufacture of watches and clocks"),
    ('2660Z', "Fabrication d'équipements d'irradiation médicale, d'équipements électromédicaux et électrothérapeutiques", 'C26.6.0', "C26.6.0 - Manufacture of irradiation, electromedical and electrotherapeutic equipment"), 
    ('2670Z', "Fabrication de matériels optique et photographique", 'C26.7.0', "C26.7.0 - Manufacture of optical instruments and photographic equipment"),
    ('2680Z', "Fabrication de supports magnétiques et optiques", 'C26.8.0', "C26.8.0 - Manufacture of magnetic and optical media"),
    ('2711Z', "Fabrication de moteurs, génératrices et transformateurs électriques", 'C27.1.1', "C27.1.1 - Manufacture of electric motors, generators and transformers"),
    ('2712Z', "Fabrication de matériel de distribution et de commande électrique", 'C27.1.2', "C27.1.2 - Manufacture of electricity distribution and control apparatus"),
    ('2720Z', "Fabrication de piles et d'accumulateurs électriques", 'C27.2.0', "C27.2.0 - Manufacture of batteries and accumulators"),
    ('2731Z', "Fabrication de câbles de fibres optiques", 'C27.3.1', "C27.3.1 - Manufacture of fibre optic cables"),
    ('2732Z', "Fabrication d'autres fils et câbles électroniques ou électriques", 'C27.3.2', "C27.3.2 - Manufacture of other electronic and electric wires and cables"),
    ('2733Z', "Fabrication de matériel d'installation électrique", 'C27.3.3', "C27.3.3 - Manufacture of wiring devices"),
    ('2740Z', "Fabrication d'appareils d'éclairage électrique", 'C27.4.0', "C27.4.0 - Manufacture of electric lighting equipment"),
    ('2751Z', "Fabrication d'appareils électroménagers", 'C27.5.1', "C27.5.1 - Manufacture of electric domestic appliances"),
    ('2752Z', "Fabrication d'appareils ménagers non électriques", 'C27.5.2', "C27.5.2 - Manufacture of non-electric domestic appliances"),
    ('2790Z', "Fabrication d'autres matériels électriques", 'C27.9.0', "C27.9.0 - Manufacture of other electrical equipment"),
    ('2811Z', "Fabrication de moteurs et turbines, à l'exception des moteurs d’avions et de véhicules", 'C28.1.1', "C28.1.1 - Manufacture of engines and turbines, except aircraft, vehicle and cycle engines"),
    ('2812Z', "Fabrication d'équipements hydrauliques et pneumatiques", 'C28.1.2', "C28.1.2 - Manufacture of fluid power equipment"),
    ('2813Z', "Fabrication d'autres pompes et compresseurs", 'C28.1.3', "C28.1.3 - Manufacture of other pumps and compressors"),
    ('2814Z', "Fabrication d'autres articles de robinetterie", 'C28.1.4', "C28.1.4 - Manufacture of other taps and valves"),
    ('2815Z', "Fabrication d'engrenages et d'organes mécaniques de transmission", 'C28.1.5', "C28.1.5 - Manufacture of bearings, gears, gearing and driving elements"),
    ('2821Z', "Fabrication de fours et brûleurs", 'C28.2.1', "C28.2.1 - Manufacture of ovens, furnaces and furnace burners"),
    ('2822Z', "Fabrication de matériel de levage et de manutention", 'C28.2.2', "C28.2.2 - Manufacture of lifting and handling equipment"),
    ('2823Z', "Fabrication de machines et d'équipements de bureau (à l'exception des ordinateurs et équipements périphériques)", 'C28.2.3', "C28.2.3 - Manufacture of office machinery and equipment (except computers and peripheral equipment)"),
    ('2824Z', "Fabrication d'outillage portatif à moteur incorporé", 'C28.2.4', "C28.2.4 - Manufacture of power-driven hand tools"),
    ('2825Z', "Fabrication d'équipements aérauliques et frigorifiques industriels", 'C28.2.5', "C28.2.5 - Manufacture of non-domestic cooling and ventilation equipment"),
    ('2829A', "Fabrication d'équipements d'emballage, de conditionnement et de pesage", 'C28.2.9', "C28.2.9 - Manufacture of other general-purpose machinery n.e.c."), 
    ('2829B', "Fabrication d'autres machines d'usage général", 'C28.2.9', "C28.2.9 - Manufacture of other general-purpose machinery n.e.c."),
    ('2830Z', "Fabrication de machines agricoles et forestières", 'C28.3.0', "C28.3.0 - Manufacture of agricultural and forestry machinery"),
    ('2841Z', "Fabrication de machines-outils pour le travail des métaux", 'C28.4.1', "C28.4.1 - Manufacture of metal forming machinery"),
    ('2849Z', "Fabrication d'autres machines-outils", 'C28.4.9', "C28.4.9 - Manufacture of other machine tools"), 
    ('2891Z', "Fabrication de machines pour la métallurgie", 'C28.9.1', "C28.9.1 - Manufacture of machinery for metallurgy"),
    ('2892Z', "Fabrication de machines pour l'extraction ou la construction", 'C28.9.2', "C28.9.2 - Manufacture of machinery for mining, quarrying and construction"),
    ('2893Z', "Fabrication de machines pour l'industrie agro-alimentaire", 'C28.9.3', "C28.9.3 - Manufacture of machinery for food, beverage and tobacco processing"),
    ('2894Z', "Fabrication de machines pour les industries textiles", 'C28.9.4', "C28.9.4 - Manufacture of machinery for textile, apparel and leather production"),
    ('2895Z', "Fabrication de machines pour les industries du papier et du carton", 'C28.9.5', "C28.9.5 - Manufacture of machinery for paper and paperboard production"),
    ('2896Z', "Fabrication de machines pour le travail du caoutchouc ou des plastiques", 'C28.9.6', "C28.9.6 - Manufacture of plastics and rubber machinery"),
    ('2899A', "Fabrication de machines d'imprimerie", 'C28.9.9', "C28.9.9 - Manufacture of other special-purpose machinery n.e.c."),
    ('2899B', "Fabrication d'autres machines spécialisées", 'C28.9.9', "C28.9.9 - Manufacture of other special-purpose machinery n.e.c."),
    ('2910Z', "Construction de véhicules automobiles", 'C29.1.0', "C29.1.0 - Manufacture of motor vehicles"),
    ('2920Z', "Fabrication de carrosseries et remorques", 'C29.2.0', "C29.2.0 - Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers"),
    ('2931Z', "Fabrication d'équipements électriques et électroniques automobiles", 'C29.3.1', "C29.3.1 - Manufacture of electrical and electronic equipment for motor vehicles"),
    ('2932Z', "Fabrication d'autres équipements automobiles", 'C29.3.2', "C29.3.2 - Manufacture of other parts and accessories for motor vehicles"),
    ('3011Z', "Construction de navires et de structures flottantes", 'C30.1.1', "C30.1.1 - Building of ships and floating structures"),
    ('3012Z', "Construction de bateaux de plaisance", 'C30.1.2', "C30.1.2 - Building of pleasure and sporting boats"),
    ('3020Z', "Construction de locomotives et d'autre matériel ferroviaire roulant", 'C30.2.0', "C30.2.0 - Manufacture of railway locomotives and rolling stock"), 
    ('3030Z', "Construction aéronautique et spatiale", 'C30.3.0', "C30.3.0 - Manufacture of air and spacecraft and related machinery"), 
    ('3040Z', "Construction de véhicules militaires de combat", 'C30.4.0', "C30.4.0 - Manufacture of military fighting vehicles"), 
    ('3091Z', "Fabrication de motocycles", 'C30.9.1', "C30.9.1 - Manufacture of motorcycles"),
    ('3092Z', "Fabrication de bicyclettes et de véhicules pour invalides", 'C30.9.2', "C30.9.2 - Manufacture of bicycles and invalid carriages"),
    ('3099Z', "Fabrication d’autres équipements de transport n.c.a.", 'C30.9.9', "C30.9.9 - Manufacture of other transport equipment n.e.c."),
    ('3101Z', "Fabrication de meubles de bureau et de magasin", 'C31.0.1', "C31.0.1 - Manufacture of office and shop furniture"),
    ('3102Z', "Fabrication de meubles de cuisine", 'C31.0.2', "C31.0.2 - Manufacture of kitchen furniture"), 
    ('3103Z', "Fabrication de matelas", 'C31.0.3', "C31.0.3 - Manufacture of mattresses"),
    ('3109A', "Fabrication de sièges d'ameublement d'intérieur", 'C31.0.9', "C31.0.9 - Manufacture of other furniture"),
    ('3109B', "Fabrication d’autres meubles et industries connexes de l’ameublement", 'C31.0.9', "C31.0.9 - Manufacture of other furniture"),
    ('3211Z', "Frappe de monnaie", 'C32.1.1', "C32.1.1 - Striking of coins"),
    ('3212Z', "Fabrication d’articles de joaillerie et bijouterie", 'C32.1.2', "C32.1.2 - Manufacture of jewellery and related articles"),
    ('3213Z', "Fabrication d’articles de bijouterie fantaisie et articles similaires", 'C32.1.3', "C32.1.3 - Manufacture of imitation jewellery and related articles"),
    ('3220Z', "Fabrication d'instruments de musique", 'C32.2.0', "C32.2.0 - Manufacture of musical instruments"),
    ('3230Z', "Fabrication d'articles de sport", 'C32.3.0', "C32.3.0 - Manufacture of sports goods"),
    ('3240Z', "Fabrication de jeux et jouets", 'C32.4.0', "C32.4.0 - Manufacture of games and toys"),
    ('3250A', "Fabrication de matériel médico-chirurgical et dentaire", 'C32.5.0', "C32.5.0 - Manufacture of medical and dental instruments and supplies"),
    ('3250B', "Fabrication de lunettes", 'C32.5.0', "C32.5.0 - Manufacture of medical and dental instruments and supplies"),
    ('3291Z', "Fabrication d’articles de brosserie", 'C32.9.1', "C32.9.1 - Manufacture of brooms and brushes"),
    ('3299Z', "Autres activités manufacturières n.c.a.", 'C32.9.9', "C32.9.9 - Other manufacturing n.e.c. "), 
    ('3311Z', "Réparation d'ouvrages en métaux", 'C33.1.1', "C33.1.1 - Repair of fabricated metal products"),
    ('3312Z', "Réparation de machines et équipements mécaniques", 'C33.1.2', "C33.1.2 - Repair of machinery"),
    ('3313Z', "Réparation de matériels électroniques et optiques", 'C33.1.3', "C33.1.3 - Repair of electronic and optical equipment"),
    ('3314Z', "Réparation d'équipements électriques", 'C33.1.4', "C33.1.4 - Repair of electrical equipment"),
    ('3315Z', "Réparation et maintenance navale", 'C33.1.5', "C33.1.5 - Repair and maintenance of ships and boats"),
    ('3316Z', "Réparation et maintenance d'aéronefs et d'engins spatiaux", 'C33.1.6', "C33.1.6 - Repair and maintenance of aircraft and spacecraft"), 
    ('3317Z', "Réparation et maintenance d'autres équipements de transport", 'C33.1.7', "C33.1.7 - Repair and maintenance of other transport equipment"),
    ('3319Z', "Réparation d'autres équipements", 'C33.1.9', "C33.1.9 - Repair of other equipment"),
    ('3320A', "Installation de structures métalliques, chaudronnées et de tuyauterie", 'C33.2.0', "C33.2.0 - Installation of industrial machinery and equipment"),
    ('3320B', "Installation de machines et équipements mécaniques", 'C33.2.0', "C33.2.0 - Installation of industrial machinery and equipment"),
    ('3320C', "Conception d'ensemble et assemblage sur site industriel d'équipements de contrôle des processus industriels", 'C33.2.0', "C33.2.0 - Installation of industrial machinery and equipment"), 
    ('3320D', "Installation d'équipements électriques, de matériels électroniques et optiques ou d'autres matériels", 'C33.2.0', "C33.2.0 - Installation of industrial machinery and equipment"),
    ('3511Z', "Production d'électricité", 'D35.1.1', "D35.1.1 - Production of electricity"),
    ('3512Z', "Transport d'électricité", 'D35.1.2', "D35.1.2 - Transmission of electricity"),
    ('3513Z', "Distribution d'électricité", 'D35.1.3', "D35.1.3 - Distribution of electricity"),
    ('3514Z', "Commerce d'électricité", 'D35.1.4', "D35.1.4 - Trade of electricity"),
    ('3521Z', "Production de combustibles gazeux", 'D35.2.1', "D35.2.1 - Manufacture of gas"),
    ('3522Z', "Distribution de combustibles gazeux par conduites", 'D35.2.2', "D35.2.2 - Distribution of gaseous fuels through mains"),
    ('3523Z', "Commerce de combustibles gazeux par conduites", 'D35.2.3', "D35.2.3 - Trade of gas through mains"),
    ('3530Z', "Production et distribution de vapeur et d'air conditionné", 'D35.3.0', "D35.3.0 - Steam and air conditioning supply"), 
    ('3600Z', "Captage, traitement et distribution d'eau", 'E36.0.0', "E36.0.0 - Water collection, treatment and supply"),
    ('3700Z', "Collecte et traitement des eaux usées", 'E37.0.0', "E37.0.0 - Sewerage"),
    ('3811Z', "Collecte des déchets non dangereux", 'E38.1.1', "E38.1.1 - Collection of non-hazardous waste"),
    ('3812Z', "Collecte des déchets dangereux", 'E38.1.2', "E38.1.2 - Collection of hazardous waste"),
    ('3821Z', "Traitement et élimination des déchets non dangereux", 'E38.2.1', "E38.2.1 - Treatment and disposal of non-hazardous waste"),
    ('3822Z', "Traitement et élimination des déchets dangereux", 'E38.2.2', "E38.2.2 - Treatment and disposal of hazardous waste"),
    ('3831Z', "Démantèlement d'épaves", 'E38.3.1', "E38.3.1 - Dismantling of wrecks"),
    ('3832Z', "Récupération de déchets triés", 'E38.3.2', "E38.3.2 - Recovery of sorted materials"),
    ('3900Z', "Dépollution et autres services de gestion des déchets", 'E39.0.0', "E39.0.0 - Remediation activities and other waste management services"),
    ('4110A', "Promotion immobilière de logements", 'F41.1.0', "F41.1.0 - Development of building projects"),
    ('4110B', "Promotion immobilière de bureaux", 'F41.1.0', "F41.1.0 - Development of building projects"),
    ('4110C', "Promotion immobilière d'autres bâtiments", 'F41.1.0', "F41.1.0 - Development of building projects"),
    ('4110D', "Supports juridiques de programmes", 'F41.1.0', "F41.1.0 - Development of building projects"),
    ('4120A', "Construction de maisons individuelles", 'F41.2.0', "F41.2.0 - Construction of residential and non-residential buildings"),
    ('4120B', "Construction d'autres bâtiments", 'F41.2.0', "F41.2.0 - Construction of residential and non-residential buildings"),
    ('4211Z', "Construction de routes et autoroutes", 'F42.1.1', "F42.1.1 - Construction of roads and motorways"),
    ('4212Z', "Construction de voies ferrées de surface et souterraines", 'F42.1.2', "F42.1.2 - Construction of railways and underground railways"),
    ('4213A', "Construction d'ouvrages d'art", 'F42.1.3', "F42.1.3 - Construction of bridges and tunnels"),
    ('4213B', "Construction et entretien de tunnels", 'F42.1.3', "F42.1.3 - Construction of bridges and tunnels"),
    ('4221Z', "Construction de réseaux pour fluides", 'F42.2.1', "F42.2.1 - Construction of utility projects for fluids"),
    ('4222Z', "Construction de réseaux électriques et de télécommunications", 'F42.2.2', "F42.2.2 - Construction of utility projects for electricity and telecommunications"),
    ('4291Z', "Construction d'ouvrages maritimes et fluviaux", 'F42.9.1', "F42.9.1 - Construction of water projects"),
    ('4299Z', "Construction d'autres ouvrages de génie civil n.c.a.", 'F42.9.9', "F42.9.9 - Construction of other civil engineering projects n.e.c."),
    ('4311Z', "Travaux de démolition", 'F43.1.1', "F43.1.1 - Demolition"),
    ('4312A', "Travaux de terrassement courants et travaux préparatoires", 'F43.1.2', "F43.1.2 - Site preparation"),
    ('4312B', "Travaux de terrassement spécialisés ou de grande masse", 'F43.1.2', "F43.1.2 - Site preparation"),
    ('4313Z', "Forages et sondages", 'F43.1.3', "F43.1.3 - Test drilling and boring"),
    ('4321A', "Travaux d'installation électrique dans tous locaux", 'F43.2.1', "F43.2.1 - Electrical installation"),
    ('4321B', "Travaux d'installation électrique sur la voie publique", 'F43.2.1', "F43.2.1 - Electrical installation"),
    ('4322A', "Travaux d'installation d'eau et de gaz en tous locaux", 'F43.2.2', "F43.2.2 - Plumbing, heat and air-conditioning installation"),
    ('4322B', "Travaux d'installation d'équipements thermiques et de climatisation", 'F43.2.2', "F43.2.2 - Plumbing, heat and air-conditioning installation"),
    ('4329A', "Travaux d'isolation", 'F43.2.9', "F43.2.9 - Other construction installation"),
    ('4329B', "Autres travaux d'installation n.c.a.", 'F43.2.9', "F43.2.9 - Other construction installation"),
    ('4331Z', "Travaux de plâtrerie", 'F43.3.1', "F43.3.1 - Plastering"),
    ('4332A', "Travaux de menuiserie bois et PVC", 'F43.3.2', "F43.3.2 - Joinery installation"),
    ('4332B', "Travaux de menuiserie métallique et serrurerie", 'F43.3.2', "F43.3.2 - Joinery installation"),
    ('4332C', "Agencement de lieux de vente", 'F43.3.2', "F43.3.2 - Joinery installation"),
    ('4333Z', "Travaux de revêtement des sols et des murs", 'F43.3.3', "F43.3.3 - Floor and wall covering"),
    ('4334Z', "Travaux de peinture et vitrerie", 'F43.3.4', "F43.3.4 - Painting and glazing"),
    ('4339Z', "Autres travaux de finition", 'F43.3.9', "F43.3.9 - Other building completion and finishing"),
    ('4391A', "Travaux de charpente", 'F43.9.1', "F43.9.1 - Roofing activities"),
    ('4391B', "Travaux de couverture par éléments", 'F43.9.1', "F43.9.1 - Roofing activities"),
    ('4399A', "Travaux d'étanchéification", 'F43.9.9', "F43.9.9 - Other specialised construction activities n.e.c."),
    ('4399B', "Travaux de montage de structures métalliques", 'F43.9.9', "F43.9.9 - Other specialised construction activities n.e.c."),
    ('4399C', "Travaux de maçonnerie générale et gros œuvre de bâtiment", 'F43.9.9', "F43.9.9 - Other specialised construction activities n.e.c."),
    ('4399D', "Autres travaux spécialisés de construction", 'F43.9.9', "F43.9.9 - Other specialised construction activities n.e.c."),
    ('4399E', "Location avec opérateur de matériel de construction", 'F43.9.9', "F43.9.9 - Other specialised construction activities n.e.c."),
    ('4511Z', "Commerce de voitures et de véhicules automobiles légers", 'G45.1.1', "G45.1.1 - Sale of cars and light motor vehicles"),
    ('4519Z', "Commerce d'autres véhicules automobiles", 'G45.1.9', "G45.1.9 - Sale of other motor vehicles"),
    ('4520A', "Entretien et réparation de véhicules automobiles légers", 'G45.2.0', "G45.2.0 - Maintenance and repair of motor vehicles"),
    ('4520B', "Entretien et réparation d'autres véhicules automobiles", 'G45.2.0', "G45.2.0 - Maintenance and repair of motor vehicles"),
    ('4531Z', "Commerce de gros d'équipements automobiles", 'G45.3.1', "G45.3.1 - Wholesale trade of motor vehicle parts and accessories"),
    ('4532Z', "Commerce de détail d'équipements automobiles", 'G45.3.2', "G45.3.2 - Retail trade of motor vehicle parts and accessories"),
    ('4540Z', "Commerce et réparation de motocycles", 'G45.4.0', "G45.4.0 - Sale, maintenance and repair of motorcycles and related parts and accessories"),
    ('4611Z', "Intermédiaires du commerce en matières premières agricoles, animaux vivants, matières premières textiles et produits semi-finis", 'G46.1.1', "G46.1.1 - Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods"),
    ('4612A', "Centrales d'achat de carburant", 'G46.1.2', "G46.1.2 - Agents involved in the sale of fuels, ores, metals and industrial chemicals"),
    ('4612B', "Autres intermédiaires du commerce en combustibles, métaux, minéraux et produits chimiques", 'G46.1.2', "G46.1.2 - Agents involved in the sale of fuels, ores, metals and industrial chemicals"),
    ('4613Z', "Intermédiaires du commerce en bois et matériaux de construction", 'G46.1.3', "G46.1.3 - Agents involved in the sale of timber and building materials"),
    ('4614Z', "Intermédiaires du commerce en machines, équipements industriels, navires et avions", 'G46.1.4', "G46.1.4 - Agents involved in the sale of machinery, industrial equipment, ships and aircraft"),
    ('4615Z', "Intermédiaires du commerce en meubles, articles de ménage et quincaillerie", 'G46.1.5', "G46.1.5 - Agents involved in the sale of furniture, household goods, hardware and ironmongery"),
    ('4616Z', "Intermédiaires du commerce en textiles, habillement, fourrures, chaussures et articles en cuir", 'G46.1.6', "G46.1.6 - Agents involved in the sale of textiles, clothing, fur, footwear and leather goods"),
    ('4617A', "Centrales d'achat alimentaires", 'G46.1.7', "G46.1.7 - Agents involved in the sale of food, beverages and tobacco"),
    ('4617B', "Autres intermédiaires du commerce en denrées, boissons et tabac", 'G46.1.7', "G46.1.7 - Agents involved in the sale of food, beverages and tobacco"),
    ('4618Z', "Intermédiaires spécialisés dans le commerce d'autres produits spécifiques", 'G46.1.8', "G46.1.8 - Agents specialised in the sale of other particular products"),
    ('4619A', "Centrales d'achat non alimentaires", 'G46.1.9', "G46.1.9 - Agents involved in the sale of a variety of goods"),
    ('4619B', "Autres intermédiaires du commerce en produits divers", 'G46.1.9', "G46.1.9 - Agents involved in the sale of a variety of goods"),
    ('4621Z', "Commerce de gros (commerce interentreprises) de céréales, de tabac non manufacturé, de semences et d'aliments pour le bétail", 'G46.2.1', "G46.2.1 - Wholesale of grain, unmanufactured tobacco, seeds and animal feeds"), 
    ('4622Z', "Commerce de gros (commerce interentreprises) de fleurs et plantes", 'G46.2.2', "G46.2.2 - Wholesale of flowers and plants"),
    ('4623Z', "Commerce de gros (commerce interentreprises) d'animaux vivants", 'G46.2.3', "G46.2.3 - Wholesale of live animals"),
    ('4624Z', "Commerce de gros (commerce interentreprises) de cuirs et peaux", 'G46.2.4', "G46.2.4 - Wholesale of hides, skins and leather"),
    ('4631Z', "Commerce de gros (commerce interentreprises) de fruits et légumes", 'G46.3.1', "G46.3.1 - Wholesale of fruit and vegetables"),
    ('4632A', "Commerce de gros (commerce interentreprises) de viandes de boucherie", 'G46.3.2', "G46.3.2 - Wholesale of meat and meat products"),
    ('4632B', "Commerce de gros (commerce interentreprises) de produits à base de viande", 'G46.3.2', "G46.3.2 - Wholesale of meat and meat products"),
    ('4632C', "Commerce de gros (commerce interentreprises) de volailles et gibier", 'G46.3.2', "G46.3.2 - Wholesale of meat and meat products"),
    ('4633Z', "Commerce de gros (commerce interentreprises) de produits laitiers, œufs, huiles et matières grasses comestibles", 'G46.3.3', "G46.3.3 - Wholesale of dairy products, eggs and edible oils and fats"),
    ('4634Z', "Commerce de gros (commerce interentreprises) de boissons", 'G46.3.4', "G46.3.4 - Wholesale of beverages"),
    ('4635Z', "Commerce de gros (commerce interentreprises) de produits à base de tabac", 'G46.3.5', "G46.3.5 - Wholesale of tobacco products"),
    ('4636Z', "Commerce de gros (commerce interentreprises) de sucre, chocolat et confiserie", 'G46.3.6', "G46.3.6 - Wholesale of sugar and chocolate and sugar confectionery"),
    ('4637Z', "Commerce de gros (commerce interentreprises) de café, thé, cacao et épices", 'G46.3.7', "G46.3.7 - Wholesale of coffee, tea, cocoa and spices"),
    ('4638A', "Commerce de gros (commerce interentreprises) de poissons, crustacés et mollusques", 'G46.3.8', "G46.3.8 - Wholesale of other food, including fish, crustaceans and molluscs"),
    ('4638B', "Commerce de gros (commerce interentreprises) alimentaire spécialisé divers", 'G46.3.8', "G46.3.8 - Wholesale of other food, including fish, crustaceans and molluscs"),
    ('4639A', "Commerce de gros (commerce interentreprises) de produits surgelés", 'G46.3.9', "G46.3.9 - Non-specialised wholesale of food, beverages and tobacco"),
    ('4639B', "Commerce de gros (commerce interentreprises) alimentaire non spécialisé", 'G46.3.9', "G46.3.9 - Non-specialised wholesale of food, beverages and tobacco"),
    ('4641Z', "Commerce de gros (commerce interentreprises) de textiles", 'G46.4.1', "G46.4.1 - Wholesale of textiles"),
    ('4642Z', "Commerce de gros (commerce interentreprises) d'habillement et de chaussures", 'G46.4.2', "G46.4.2 - Wholesale of clothing and footwear"),
    ('4643Z', "Commerce de gros (commerce interentreprises) d'appareils électroménagers", 'G46.4.3', "G46.4.3 - Wholesale of electrical household appliances"),
    ('4644Z', "Commerce de gros (commerce interentreprises) de vaisselle, verrerie et produits d'entretien", 'G46.4.4', "G46.4.4 - Wholesale of china and glassware and cleaning materials"),
    ('4645Z', "Commerce de gros (commerce interentreprises) de parfumerie et de produits de beauté", 'G46.4.5', "G46.4.5 - Wholesale of perfume and cosmetics"),
    ('4646Z', "Commerce de gros (commerce interentreprises) de produits pharmaceutiques", 'G46.4.6', "G46.4.6 - Wholesale of pharmaceutical goods"),
    ('4647Z', "Commerce de gros (commerce interentreprises) de meubles, de tapis et d'appareils d'éclairage", 'G46.4.7', "G46.4.7 - Wholesale of furniture, carpets and lighting equipment"), 
    ('4648Z', "Commerce de gros (commerce interentreprises) d'articles d'horlogerie et de bijouterie", 'G46.4.8', "G46.4.8 - Wholesale of watches and jewellery"),
    ('4649Z', "Commerce de gros (commerce interentreprises) d'autres biens domestiques", 'G46.4.9', "G46.4.9 - Wholesale of other household goods"), 
    ('4651Z', "Commerce de gros (commerce interentreprises) d'ordinateurs, d'équipements informatiques périphériques et de logiciels", 'G46.5.1', "G46.5.1 - Wholesale of computers, computer peripheral equipment and software"),
    ('4652Z', "Commerce de gros (commerce interentreprises) de composants et d'équipements électroniques et de télécommunication", 'G46.5.2', "G46.5.2 - Wholesale of electronic and telecommunications equipment and parts"),
    ('4661Z', "Commerce de gros (commerce interentreprises) de matériel agricole", 'G46.6.1', "G46.6.1 - Wholesale of agricultural machinery, equipment and supplies"),
    ('4662Z', "Commerce de gros (commerce interentreprises) de machines-outils", 'G46.6.2', "G46.6.2 - Wholesale of machine tools"),
    ('4663Z', "Commerce de gros (commerce interentreprises) de machines pour l'extraction, la construction et le génie civil", 'G46.6.3', "G46.6.3 - Wholesale of mining, construction and civil engineering machinery"), 
    ('4664Z', "Commerce de gros (commerce interentreprises) de machines pour l'industrie textile et l'habillement", 'G46.6.4', "G46.6.4 - Wholesale of machinery for the textile industry and of sewing and knitting machines"),
    ('4665Z', "Commerce de gros (commerce interentreprises) de mobilier de bureau", 'G46.6.5', "G46.6.5 - Wholesale of office furniture"),
    ('4666Z', "Commerce de gros (commerce interentreprises) d'autres machines et équipements de bureau", 'G46.6.6', "G46.6.6 - Wholesale of other office machinery and equipment"), 
    ('4669A', "Commerce de gros (commerce interentreprises) de matériel électrique", 'G46.6.9', "G46.6.9 - Wholesale of other machinery and equipment"),
    ('4669B', "Commerce de gros (commerce interentreprises) de fournitures et équipements industriels divers", 'G46.6.9', "G46.6.9 - Wholesale of other machinery and equipment"),
    ('4669C', "Commerce de gros (commerce interentreprises) de fournitures et équipements divers pour le commerce et les services", 'G46.6.9', "G46.6.9 - Wholesale of other machinery and equipment"),
    ('4671Z', "Commerce de gros (commerce interentreprises) de combustibles et de produits annexes", 'G46.7.1', "G46.7.1 - Wholesale of solid, liquid and gaseous fuels and related products"),
    ('4672Z', "Commerce de gros (commerce interentreprises) de minerais et métaux", 'G46.7.2', "G46.7.2 - Wholesale of metals and metal ores"),
    ('4673A', "Commerce de gros (commerce interentreprises) de bois et de matériaux de construction", 'G46.7.3', "G46.7.3 - Wholesale of wood, construction materials and sanitary equipment"), 
    ('4673B', "Commerce de gros (commerce interentreprises) d'appareils sanitaires et de produits de décoration", 'G46.7.3', "G46.7.3 - Wholesale of wood, construction materials and sanitary equipment"),
    ('4674A', "Commerce de gros (commerce interentreprises) de quincaillerie", 'G46.7.4', "G46.7.4 - Wholesale of hardware, plumbing and heating equipment and supplies"),
    ('4674B', "Commerce de gros (commerce interentreprises) de fournitures pour la plomberie et le chauffage", 'G46.7.4', "G46.7.4 - Wholesale of hardware, plumbing and heating equipment and supplies"),
    ('4675Z', "Commerce de gros (commerce interentreprises) de produits chimiques", 'G46.7.5', "G46.7.5 - Wholesale of chemical products"),
    ('4676Z', "Commerce de gros (commerce interentreprises) d'autres produits intermédiaires", 'G46.7.6', "G46.7.6 - Wholesale of other intermediate products"),
    ('4677Z', "Commerce de gros (commerce interentreprises) de déchets et débris", 'G46.7.7', "G46.7.7 - Wholesale of waste and scrap"),
    ('4690Z', "Commerce de gros (commerce interentreprises) non spécialisé", 'G46.9.0', "G46.9.0 - Non-specialised wholesale trade"),
    ('4711A', "Commerce de détail de produits surgelés", 'G47.1.1', "G47.1.1 - Retail sale in non-specialised stores with food, beverages or tobacco predominating"),
    ('4711B', "Commerce d'alimentation générale", 'G47.1.1', "G47.1.1 - Retail sale in non-specialised stores with food, beverages or tobacco predominating"),
    ('4711C', "Supérettes", 'G47.1.1', "G47.1.1 - Retail sale in non-specialised stores with food, beverages or tobacco predominating"),
    ('4711D', "Supermarchés", 'G47.1.1', "G47.1.1 - Retail sale in non-specialised stores with food, beverages or tobacco predominating"),
    ('4711E', "Magasins multi-commerces", 'G47.1.1', "G47.1.1 - Retail sale in non-specialised stores with food, beverages or tobacco predominating"),
    ('4711F', "Hypermarchés", 'G47.1.1', "G47.1.1 - Retail sale in non-specialised stores with food, beverages or tobacco predominating"),
    ('4719A', "Grands magasins", 'G47.1.9', "G47.1.9 - Other retail sale in non-specialised stores"),
    ('4719B', "Autres commerces de détail en magasin non spécialisé", 'G47.1.9', "G47.1.9 - Other retail sale in non-specialised stores"),
    ('4721Z', "Commerce de détail de fruits et légumes en magasin spécialisé", 'G47.2.1', "G47.2.1 - Retail sale of fruit and vegetables in specialised stores"),
    ('4722Z', "Commerce de détail de viandes et de produits à base de viande en magasin spécialisé", 'G47.2.2', "G47.2.2 - Retail sale of meat and meat products in specialised stores"),
    ('4723Z', "Commerce de détail de poissons, crustacés et mollusques en magasin spécialisé", 'G47.2.3', "G47.2.3 - Retail sale of fish, crustaceans and molluscs in specialised stores"),
    ('4724Z', "Commerce de détail de pain, pâtisserie et confiserie en magasin spécialisé", 'G47.2.4', "G47.2.4 - Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores"),
    ('4725Z', "Commerce de détail de boissons en magasin spécialisé", 'G47.2.5', "G47.2.5 - Retail sale of beverages in specialised stores"),
    ('4726Z', "Commerce de détail de produits à base de tabac en magasin spécialisé", 'G47.2.6', "G47.2.6 - Retail sale of tobacco products in specialised stores"),
    ('4729Z', "Autres commerces de détail alimentaires en magasin spécialisé", 'G47.2.9', "G47.2.9 - Other retail sale of food in specialised stores"), 
    ('4730Z', "Commerce de détail de carburants en magasin spécialisé", 'G47.3.0', "G47.3.0 - Retail sale of automotive fuel in specialised stores"),
    ('4741Z', "Commerce de détail d'ordinateurs, d'unités périphériques et de logiciels en magasin spécialisé", 'G47.4.1', "G47.4.1 - Retail sale of computers, peripheral units and software in specialised stores"),
    ('4742Z', "Commerce de détail de matériels de télécommunication en magasin spécialisé", 'G47.4.2', "G47.4.2 - Retail sale of telecommunications equipment in specialised stores"),
    ('4743Z', "Commerce de détail de matériels audio et vidéo en magasin spécialisé", 'G47.4.3', "G47.4.3 - Retail sale of audio and video equipment in specialised stores"),
    ('4751Z', "Commerce de détail de textiles en magasin spécialisé", 'G47.5.1', "G47.5.1 - Retail sale of textiles in specialised stores"),
    ('4752A', "Commerce de détail de quincaillerie, peintures et verres en petites surfaces (moins de 400 m2)", 'G47.5.2', "G47.5.2 - Retail sale of hardware, paints and glass in specialised stores"),
    ('4752B', "Commerce de détail de quincaillerie, peintures et verres en grandes surfaces (400 m2et plus)", 'G47.5.2', "G47.5.2 - Retail sale of hardware, paints and glass in specialised stores"),
    ('4753Z', "Commerce de détail de tapis, moquettes et revêtements de murs et de sols en magasin spécialisé", 'G47.5.3', "G47.5.3 - Retail sale of carpets, rugs, wall and floor coverings in specialised stores"),
    ('4754Z', "Commerce de détail d'appareils électroménagers en magasin spécialisé", 'G47.5.4', "G47.5.4 - Retail sale of electrical household appliances in specialised stores"),
    ('4759A', "Commerce de détail de meubles", 'G47.5.9', "G47.5.9 - Retail sale of furniture, lighting equipment and other household articles in specialised stores"),
    ('4759B', "Commerce de détail d'autres équipements du foyer", 'G47.5.9', "G47.5.9 - Retail sale of furniture, lighting equipment and other household articles in specialised stores"),
    ('4761Z', "Commerce de détail de livres en magasin spécialisé", 'G47.6.1', "G47.6.1 - Retail sale of books in specialised stores"),
    ('4762Z', "Commerce de détail de journaux et papeterie en magasin spécialisé", 'G47.6.2', "G47.6.2 - Retail sale of newspapers and stationery in specialised stores"),
    ('4763Z', "Commerce de détail d'enregistrements musicaux et vidéo en magasin spécialisé", 'G47.6.3', "G47.6.3 - Retail sale of music and video recordings in specialised stores"),
    ('4764Z', "Commerce de détail d'articles de sport en magasin spécialisé", 'G47.6.4', "G47.6.4 - Retail sale of sporting equipment in specialised stores"),
    ('4765Z', "Commerce de détail de jeux et jouets en magasin spécialisé", 'G47.6.5', "G47.6.5 - Retail sale of games and toys in specialised stores"),
    ('4771Z', "Commerce de détail d'habillement en magasin spécialisé", 'G47.7.1', "G47.7.1 - Retail sale of clothing in specialised stores"),
    ('4772A', "Commerce de détail de la chaussure", 'G47.7.2', "G47.7.2 - Retail sale of footwear and leather goods in specialised stores"),
    ('4772B', "Commerce de détail de maroquinerie et d'articles de voyage", 'G47.7.2', "G47.7.2 - Retail sale of footwear and leather goods in specialised stores"),
    ('4773Z', "Commerce de détail de produits pharmaceutiques en magasin spécialisé", 'G47.7.3', "G47.7.3 - Dispensing chemist in specialised stores"),
    ('4774Z', "Commerce de détail d'articles médicaux et orthopédiques en magasin spécialisé", 'G47.7.4', "G47.7.4 - Retail sale of medical and orthopaedic goods in specialised stores"),
    ('4775Z', "Commerce de détail de parfumerie et de produits de beauté en magasin spécialisé", 'G47.7.5', "G47.7.5 - Retail sale of cosmetic and toilet articles in specialised stores"),
    ('4776Z', "Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie et aliments pour ces animaux en magasin spécialisé", 'G47.7.6', "G47.7.6 - Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores"),
    ('4777Z', "Commerce de détail d'articles d'horlogerie et de bijouterie en magasin spécialisé", 'G47.7.7', "G47.7.7 - Retail sale of watches and jewellery in specialised stores"),
    ('4778A', "Commerces de détail d'optique", 'G47.7.8', "G47.7.8 - Other retail sale of new goods in specialised stores"),
    ('4778B', "Commerces de détail de charbons et combustibles", 'G47.7.8', "G47.7.8 - Other retail sale of new goods in specialised stores"),
    ('4778C', "Autres commerces de détail spécialisés divers", 'G47.7.8', "G47.7.8 - Other retail sale of new goods in specialised stores"),
    ('4779Z', "Commerce de détail de biens d'occasion en magasin", 'G47.7.9', "G47.7.9 - Retail sale of second-hand goods in stores"),
    ('4781Z', "Commerce de détail alimentaire sur éventaires et marchés", 'G47.8.1', "G47.8.1 - Retail sale via stalls and markets of food, beverages and tobacco products"),
    ('4782Z', "Commerce de détail de textiles, d'habillement et de chaussures sur éventaires et marchés", 'G47.8.2', "G47.8.2 - Retail sale via stalls and markets of textiles, clothing and footwear"),
    ('4789Z', "Autres commerces de détail sur éventaires et marchés", 'G47.8.9', "G47.8.9 - Retail sale via stalls and markets of other goods"),
    ('4791A', "Vente à distance sur catalogue général", 'G47.9.1', "G47.9.1 - Retail sale via mail order houses or via Internet"),
    ('4791B', "Vente à distance sur catalogue spécialisé", 'G47.9.1', "G47.9.1 - Retail sale via mail order houses or via Internet"),
    ('4799A', "Vente à domicile", 'G47.9.9', "G47.9.9 - Other retail sale not in stores, stalls or markets"),
    ('4799B', "Vente par automates et autres commerces de détail hors magasin, éventaires ou marchés n.c.a.", 'G47.9.9', "G47.9.9 - Other retail sale not in stores, stalls or markets"),
    ('4910Z', "Transport ferroviaire interurbain de voyageurs", 'H49.1.0', "H49.1.0 - Passenger rail transport, interurban"),
    ('4920Z', "Transports ferroviaires de fret", 'H49.2.0', "H49.2.0 - Freight rail transport"), 
    ('4931Z', "Transports urbains et suburbains de voyageurs", 'H49.3.1', "H49.3.1 - Urban and suburban passenger land transport"),
    ('4932Z', "Transports de voyageurs par taxis", 'H49.3.2', "H49.3.2 - Taxi operation"),
    ('4939A', "Transports routiers réguliers de voyageurs", 'H49.3.9', "H49.3.9 - Other passenger land transport n.e.c."),
    ('4939B', "Autres transports routiers de voyageurs", 'H49.3.9', "H49.3.9 - Other passenger land transport n.e.c."), 
    ('4939C', "Téléphériques et remontées mécaniques", 'H49.3.9', "H49.3.9 - Other passenger land transport n.e.c."),
    ('4941A', "Transports routiers de fret interurbains", 'H49.4.1', "H49.4.1 - Freight transport by road"),
    ('4941B', "Transports routiers de fret de proximité", 'H49.4.1', "H49.4.1 - Freight transport by road"),
    ('4941C', "Location de camions avec chauffeur", 'H49.4.1', "H49.4.1 - Freight transport by road"),
    ('4942Z', "Services de déménagement", 'H49.4.2', "H49.4.2 - Removal services"),
    ('4950Z', "Transports par conduites", 'H49.5.0', "H49.5.0 - Transport via pipeline"),
    ('5010Z', "Transports maritimes et côtiers de passagers", 'H50.1.0', "H50.1.0 - Sea and coastal passenger water transport"),
    ('5020Z', "Transports maritimes et côtiers de fret", 'H50.2.0', "H50.2.0 - Sea and coastal freight water transport"),
    ('5030Z', "Transports fluviaux de passagers", 'H50.3.0', "H50.3.0 - Inland passenger water transport"),
    ('5040Z', "Transports fluviaux de fret", 'H50.4.0', "H50.4.0 - Inland freight water transport"), 
    ('5110Z', "Transports aériens de passagers", 'H51.1.0', "H51.1.0 - Passenger air transport"),
    ('5121Z', "Transports aériens de fret", 'H51.2.1', "H51.2.1 - Freight air transport"),
    ('5122Z', "Transports spatiaux", 'H51.2.2', "H51.2.2 - Space transport"),
    ('5210A', "Entreposage et stockage frigorifique", 'H52.1.0', "H52.1.0 - Warehousing and storage"),
    ('5210B', "Entreposage et stockage non frigorifique", 'H52.1.0', "H52.1.0 - Warehousing and storage"),
    ('5221Z', "Services auxiliaires des transports terrestres", 'H52.2.1', "H52.2.1 - Service activities incidental to land transportation"),
    ('5222Z', "Services auxiliaires des transports par eau", 'H52.2.2', "H52.2.2 - Service activities incidental to water transportation"),
    ('5223Z', "Services auxiliaires des transports aériens", 'H52.2.3', "H52.2.3 - Service activities incidental to air transportation"),
    ('5224A', "Manutention portuaire", 'H52.2.4', "H52.2.4 - Cargo handling"),
    ('5224B', "Manutention non portuaire", 'H52.2.4', "H52.2.4 - Cargo handling"),
    ('5229A', "Messagerie, fret express", 'H52.2.9', "H52.2.9 - Other transportation support activities "),
    ('5229B', "Affrètement et organisation des transports", 'H52.2.9', "H52.2.9 - Other transportation support activities "), 
    ('5310Z', "Activités de poste dans le cadre d'une obligation de service universel", 'H53.1.0', "H53.1.0 - Postal activities under universal service obligation"), 
    ('5320Z', "Autres activités de poste et de courrier", 'H53.2.0', "H53.2.0 - Other postal and courier activities"),
    ('5510Z', "Hôtels et hébergement similaire", 'I55.1.0', "I55.1.0 - Hotels and similar accommodation"), 
    ('5520Z', "Hébergement touristique et autre hébergement de courte durée", 'I55.2.0', "I55.2.0 - Holiday and other short-stay accommodation"), 
    ('5530Z', "Terrains de camping et parcs pour caravanes ou véhicules de loisirs", 'I55.3.0', "I55.3.0 - Camping grounds, recreational vehicle parks and trailer parks"),
    ('5590Z', "Autres hébergements", 'I55.9.0', "I55.9.0 - Other accommodation"), 
    ('5610A', "Restauration traditionnelle", 'I56.1.0', "I56.1.0 - Restaurants and mobile food service activities"),
    ('5610B', "Cafétérias et autres libres-services", 'I56.1.0', "I56.1.0 - Restaurants and mobile food service activities"),
    ('5610C', "Restauration de type rapide", 'I56.1.0', "I56.1.0 - Restaurants and mobile food service activities"),
    ('5621Z', "Services des traiteurs", 'I56.2.1', "I56.2.1 - Event catering activities"), 
    ('5629A', "Restauration collective sous contrat", 'I56.2.9', "I56.2.9 - Other food service activities"),
    ('5629B', "Autres services de restauration n.c.a.", 'I56.2.9', "I56.2.9 - Other food service activities"),
    ('5630Z', "Débits de boissons", 'I56.3.0', "I56.3.0 - Beverage serving activities"),
    ('5811Z', "Édition de livres", 'J58.1.1', "J58.1.1 - Book publishing"),
    ('5812Z', "Édition de répertoires et de fichiers d'adresses", 'J58.1.2', "J58.1.2 - Publishing of directories and mailing lists"),
    ('5813Z', "Édition de journaux", 'J58.1.3', "J58.1.3 - Publishing of newspapers"),
    ('5814Z', "Édition de revues et périodiques", 'J58.1.4', "J58.1.4 - Publishing of journals and periodicals"),
    ('5819Z', "Autres activités d'édition", 'J58.1.9', "J58.1.9 - Other publishing activities"),
    ('5821Z', "Édition de jeux électroniques", 'J58.2.1', "J58.2.1 - Publishing of computer games"),
    ('5829A', "Édition de logiciels système et de réseau", 'J58.2.9', "J58.2.9 - Other software publishing"),
    ('5829B', "Edition de logiciels outils de développement et de langages", 'J58.2.9', "J58.2.9 - Other software publishing"),
    ('5829C', "Edition de logiciels applicatifs", 'J58.2.9', "J58.2.9 - Other software publishing"),
    ('5911A', "Production de films et de programmes pour la télévision", 'J59.1.1', "J59.1.1 - Motion picture, video and television programme production activities"), 
    ('5911B', "Production de films institutionnels et publicitaires", 'J59.1.1', "J59.1.1 - Motion picture, video and television programme production activities"),
    ('5911C', "Production de films pour le cinéma", 'J59.1.1', "J59.1.1 - Motion picture, video and television programme production activities"),
    ('5912Z', "Post-production de films cinématographiques, de vidéo et de programmes de télévision", 'J59.1.2', "J59.1.2 - Motion picture, video and television programme post-production activities"),
    ('5913A', "Distribution de films cinématographiques", 'J59.1.3', "J59.1.3 - Motion picture, video and television programme distribution activities"),
    ('5913B', "Edition et distribution vidéo", 'J59.1.3', "J59.1.3 - Motion picture, video and television programme distribution activities"),
    ('5914Z', "Projection de films cinématographiques", 'J59.1.4', "J59.1.4 - Motion picture projection activities"),
    ('5920Z', "Enregistrement sonore et édition musicale", 'J59.2.0', "J59.2.0 - Sound recording and music publishing activities"), 
    ('6010Z', "Édition et diffusion de programmes radio", 'J60.1.0', "J60.1.0 - Radio broadcasting"),
    ('6020A', "Edition de chaînes généralistes", 'J60.2.0', "J60.2.0 - Television programming and broadcasting activities"),
    ('6020B', "Edition de chaînes thématiques", 'J60.2.0', "J60.2.0 - Television programming and broadcasting activities"),
    ('6110Z', "Télécommunications filaires", 'J61.1.0', "J61.1.0 - Wired telecommunications activities"),
    ('6120Z', "Télécommunications sans fil", 'J61.2.0', "J61.2.0 - Wireless telecommunications activities"), 
    ('6130Z', "Télécommunications par satellite", 'J61.3.0', "J61.3.0 - Satellite telecommunications activities"),
    ('6190Z', "Autres activités de télécommunication", 'J61.9.0', "J61.9.0 - Other telecommunications activities"), 
    ('6201Z', "Programmation informatique", 'J62.0.1', "J62.0.1 - Computer programming activities"),
    ('6202A', "Conseil en systèmes et logiciels informatiques", 'J62.0.2', "J62.0.2 - Computer consultancy activities"),
    ('6202B', "Tierce maintenance de systèmes et d’applications informatiques", 'J62.0.2', "J62.0.2 - Computer consultancy activities"),
    ('6203Z', "Gestion d'installations informatiques", 'J62.0.3', "J62.0.3 - Computer facilities management activities"),
    ('6209Z', "Autres activités informatiques", 'J62.0.9', "J62.0.9 - Other information technology and computer service activities"),
    ('6311Z', "Traitement de données, hébergement et activités connexes", 'J63.1.1', "J63.1.1 - Data processing, hosting and related activities"),
    ('6312Z', "Portails Internet", 'J63.1.2', "J63.1.2 - Web portals"),
    ('6391Z', "Activités des agences de presse", 'J63.9.1', "J63.9.1 - News agency activities"),
    ('6399Z', "Autres services d'information n.c.a.", 'J63.9.9', "J63.9.9 - Other information service activities n.e.c."),
    ('6411Z', "Activités de banque centrale", 'K64.1.1', "K64.1.1 - Central banking"),
    ('6419Z', "Autres intermédiations monétaires", 'K64.1.9', "K64.1.9 - Other monetary intermediation"),
    ('6420Z', "Activités des sociétés holding", 'K64.2.0', "K64.2.0 - Activities of holding companies"),
    ('6430Z', "Fonds de placement et entités financières similaires", 'K64.3.0', "K64.3.0 - Trusts, funds and similar financial entities"),
    ('6491Z', "Crédit-bail", 'K64.9.1', "K64.9.1 - Financial leasing"), 
    ('6492Z', "Autre distribution de crédit", 'K64.9.2', "K64.9.2 - Other credit granting"),
    ('6499Z', "Autres activités des services financiers, hors assurance et caisses de retraite, n.c.a.", 'K64.9.9', "K64.9.9 - Other financial service activities, except insurance and pension funding n.e.c."),
    ('6511Z', "Assurance vie", 'K65.1.1', "K65.1.1 - Life insurance"),
    ('6512Z', "Autres assurances", 'K65.1.2', "K65.1.2 - Non-life insurance"),
    ('6520Z', "Réassurance", 'K65.2.0', "K65.2.0 - Reinsurance"),
    ('6530Z', "Caisses de retraite", 'K65.3.0', "K65.3.0 - Pension funding"),
    ('6611Z', "Administration de marchés financiers", 'K66.1.1', "K66.1.1 - Administration of financial markets"),
    ('6612Z', "Courtage de valeurs mobilières et de marchandises", 'K66.1.2', "K66.1.2 - Security and commodity contracts brokerage"),
    ('6619A', "Supports juridiques de gestion de patrimoine mobilier", 'K66.1.9', "K66.1.9 - Other activities auxiliary to financial services, except insurance and pension funding"),
    ('6619B', "Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite, n.c.a.", 'K66.1.9', "K66.1.9 - Other activities auxiliary to financial services, except insurance and pension funding"),
    ('6621Z', "Évaluation des risques et dommages", 'K66.2.1', "K66.2.1 - Risk and damage evaluation"),
    ('6622Z', "Activités des agents et courtiers d'assurances", 'K66.2.2', "K66.2.2 - Activities of insurance agents and brokers"),
    ('6629Z', "Autres activités auxiliaires d'assurance et de caisses de retraite", 'K66.2.9', "K66.2.9 - Other activities auxiliary to insurance and pension funding"),
    ('6630Z', "Gestion de fonds", 'K66.3.0', "K66.3.0 - Fund management activities"),
    ('6810Z', "Activités des marchands de biens immobiliers", 'L68.1.0', "L68.1.0 - Buying and selling of own real estate"),
    ('6820A', "Location de logements", 'L68.2.0', "L68.2.0 - Rental and operating of own or leased real estate"),
    ('6820B', "Location de terrains et d'autres biens immobiliers", 'L68.2.0', "L68.2.0 - Rental and operating of own or leased real estate"),
    ('6831Z', "Agences immobilières", 'L68.3.1', "L68.3.1 - Real estate agencies"),
    ('6832A', "Administration d'immeubles et autres biens immobiliers", 'L68.3.2', "L68.3.2 - Management of real estate on a fee or contract basis"),
    ('6832B', "Supports juridiques de gestion de patrimoine immobilier", 'L68.3.2', "L68.3.2 - Management of real estate on a fee or contract basis"),
    ('6910Z', "Activités juridiques", 'M69.1.0', "M69.1.0 - Legal activities"),
    ('6920Z', "Activités comptables", 'M69.2.0', "M69.2.0 - Accounting, bookkeeping and auditing activities; tax consultancy"),
    ('7010Z', "Activités des sièges sociaux", 'M70.1.0', "M70.1.0 - Activities of head offices"),
    ('7021Z', "Conseil en relations publiques et communication", 'M70.2.1', "M70.2.1 - Public relations and communication activities"),
    ('7022Z', "Conseil pour les affaires et autres conseils de gestion", 'M70.2.2', "M70.2.2 - Business and other management consultancy activities"),
    ('7111Z', "Activités d'architecture", 'M71.1.1', "M71.1.1 - Architectural activities "), 
    ('7112A', "Activité des géomètres", 'M71.1.2', "M71.1.2 - Engineering activities and related technical consultancy"),
    ('7112B', "Ingénierie, études techniques", 'M71.1.2', "M71.1.2 - Engineering activities and related technical consultancy"),
    ('7120A', "Contrôle technique automobile", 'M71.2.0', "M71.2.0 - Technical testing and analysis"),
    ('7120B', "Analyses, essais et inspections techniques", 'M71.2.0', "M71.2.0 - Technical testing and analysis"),
    ('7211Z', "Recherche-développement en biotechnologie", 'M72.1.1', "M72.1.1 - Research and experimental development on biotechnology"),
    ('7219Z', "Recherche-développement en autres sciences physiques et naturelles", 'M72.1.9', "M72.1.9 - Other research and experimental development on natural sciences and engineering"),
    ('7220Z', "Recherche-développement en sciences humaines et sociales", 'M72.2.0', "M72.2.0 - Research and experimental development on social sciences and humanities"),
    ('7311Z', "Activités des agences de publicité", 'M73.1.1', "M73.1.1 - Advertising agencies"),
    ('7312Z', "Régie publicitaire de médias", 'M73.1.2', "M73.1.2 - Media representation"),
    ('7320Z', "Études de marché et sondages", 'M73.2.0', "M73.2.0 - Market research and public opinion polling"),
    ('7410Z', "Activités spécialisées de design", 'M74.1.0', "M74.1.0 - Specialised design activities"),
    ('7420Z', "Activités photographiques", 'M74.2.0', "M74.2.0 - Photographic activities"),
    ('7430Z', "Traduction et interprétation", 'M74.3.0', "M74.3.0 - Translation and interpretation activities"),
    ('7490A', "Activité des économistes de la construction", 'M74.9.0', "M74.9.0 - Other professional, scientific and technical activities n.e.c."),
    ('7490B', "Activités spécialisées, scientifiques et techniques diverses", 'M74.9.0', "M74.9.0 - Other professional, scientific and technical activities n.e.c."),
    ('7500Z', "Activités vétérinaires", 'M75.0.0', "M75.0.0 - Veterinary activities"),
    ('7711A', "Location de courte durée de voitures et de véhicules automobiles légers", 'N77.1.1', "N77.1.1 - Rental and leasing of cars and light motor vehicles"),
    ('7711B', "Location de longue durée de voitures et de véhicules automobiles légers", 'N77.1.1', "N77.1.1 - Rental and leasing of cars and light motor vehicles"),
    ('7712Z', "Location et location-bail de camions", 'N77.1.2', "N77.1.2 - Rental and leasing of trucks"),
    ('7721Z', "Location et location-bail d'articles de loisirs et de sport", 'N77.2.1', "N77.2.1 - Rental and leasing of recreational and sports goods"), 
    ('7722Z', "Location de vidéocassettes et disques vidéo", 'N77.2.2', "N77.2.2 - Rental of video tapes and disks"),
    ('7729Z', "Location et location-bail d'autres biens personnels et domestiques", 'N77.2.9', "N77.2.9 - Rental and leasing of other personal and household goods"),
    ('7731Z', "Location et location-bail de machines et équipements agricoles", 'N77.3.1', "N77.3.1 - Rental and leasing of agricultural machinery and equipment"),
    ('7732Z', "Location et location-bail de machines et équipements pour la construction", 'N77.3.2', "N77.3.2 - Rental and leasing of construction and civil engineering machinery and equipment"),
    ('7733Z', "Location et location-bail de machines de bureau et de matériel informatique", 'N77.3.3', "N77.3.3 - Rental and leasing of office machinery and equipment (including computers)"),
    ('7734Z', "Location et location-bail de matériels de transport par eau", 'N77.3.4', "N77.3.4 - Rental and leasing of water transport equipment"),
    ('7735Z', "Location et location-bail de matériels de transport aérien", 'N77.3.5', "N77.3.5 - Rental and leasing of air transport equipment"),
    ('7739Z', "Location et location-bail d'autres machines, équipements et biens matériels n.c.a.", 'N77.3.9', "N77.3.9 - Rental and leasing of other machinery, equipment and tangible goods n.e.c."), 
    ('7740Z', "Location-bail de propriété intellectuelle et de produits similaires, à l'exception des œuvres soumises à copyright", 'N77.4.0', "N77.4.0 - Leasing of intellectual property and similar products, except copyrighted works"),
    ('7810Z', "Activités des agences de placement de main-d'œuvre", 'N78.1.0', "N78.1.0 - Activities of employment placement agencies"), 
    ('7820Z', "Activités des agences de travail temporaire", 'N78.2.0', "N78.2.0 - Temporary employment agency activities"), 
    ('7830Z', "Autre mise à disposition de ressources humaines", 'N78.3.0', "N78.3.0 - Other human resources provision"),
    ('7911Z', "Activités des agences de voyage", 'N79.1.1', "N79.1.1 - Travel agency activities"),
    ('7912Z', "Activités des voyagistes", 'N79.1.2', "N79.1.2 - Tour operator activities"),
    ('7990Z', "Autres services de réservation et activités connexes", 'N79.9.0', "N79.9.0 - Other reservation service and related activities"),
    ('8010Z', "Activités de sécurité privée", 'N80.1.0', "N80.1.0 - Private security activities"), 
    ('8020Z', "Activités liées aux systèmes de sécurité", 'N80.2.0', "N80.2.0 - Security systems service activities"), 
    ('8030Z', "Activités d'enquête", 'N80.3.0', "N80.3.0 - Investigation activities"),
    ('8110Z', "Activités combinées de soutien lié aux bâtiments", 'N81.1.0', "N81.1.0 - Combined facilities support activities"), 
    ('8121Z', "Nettoyage courant des bâtiments", 'N81.2.1', "N81.2.1 - General cleaning of buildings"),
    ('8122Z', "Autres activités de nettoyage des bâtiments et nettoyage industriel", 'N81.2.2', "N81.2.2 - Other building and industrial cleaning activities"),
    ('8129A', "Désinfection, désinsectisation, dératisation", 'N81.2.9', "N81.2.9 - Other cleaning activities"),
    ('8129B', "Autres activités de nettoyage n.c.a.", 'N81.2.9', "N81.2.9 - Other cleaning activities"),
    ('8130Z', "Services d'aménagement paysager", 'N81.3.0', "N81.3.0 - Landscape service activities"), 
    ('8211Z', "Services administratifs combinés de bureau", 'N82.1.1', "N82.1.1 - Combined office administrative service activities"),
    ('8219Z', "Photocopie, préparation de documents et autres activités spécialisées de soutien de bureau", 'N82.1.9', "N82.1.9 - Photocopying, document preparation and other specialised office support activities"),
    ('8220Z', "Activités de centres d'appels", 'N82.2.0', "N82.2.0 - Activities of call centres"),
    ('8230Z', "Organisation de foires, salons professionnels et congrès", 'N82.3.0', "N82.3.0 - Organisation of conventions and trade shows"),
    ('8291Z', "Activités des agences de recouvrement de factures et des sociétés d'information financière sur la clientèle", 'N82.9.1', "N82.9.1 - Activities of collection agencies and credit bureaus"),
    ('8292Z', "Activités de conditionnement", 'N82.9.2', "N82.9.2 - Packaging activities"),
    ('8299Z', "Autres activités de soutien aux entreprises n.c.a.", 'N82.9.9', "N82.9.9 - Other business support service activities n.e.c."),
    ('8411Z', "Administration publique générale", 'O84.1.1', "O84.1.1 - General public administration activities"),
    ('8412Z', "Administration publique (tutelle) de la santé, de la formation, de la culture et des services sociaux, autre que sécurité sociale", 'O84.1.2', "O84.1.2 - Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security"), 
    ('8413Z', "Administration publique (tutelle) des activités économiques", 'O84.1.3', "O84.1.3 - Regulation of and contribution to more efficient operation of businesses"),
    ('8421Z', "Affaires étrangères", 'O84.2.1', "O84.2.1 - Foreign affairs"),
    ('8422Z', "Défense", 'O84.2.2', "O84.2.2 - Defence activities"),
    ('8423Z', "Justice", 'O84.2.3', "O84.2.3 - Justice and judicial activities"),
    ('8424Z', "Activités d’ordre public et de sécurité", 'O84.2.4', "O84.2.4 - Public order and safety activities"),
    ('8425Z', "Services du feu et de secours", 'O84.2.5', "O84.2.5 - Fire service activities"),
    ('8430A', "Activités générales de sécurité sociale", 'O84.3.0', "O84.3.0 - Compulsory social security activities"),
    ('8430B', "Gestion des retraites complémentaires", 'O84.3.0', "O84.3.0 - Compulsory social security activities"),
    ('8430C', "Distribution sociale de revenus", 'O84.3.0', "O84.3.0 - Compulsory social security activities"),
    ('8510Z', "Enseignement pré-primaire", 'P85.1.0', "P85.1.0 - Pre-primary education "),
    ('8520Z', "Enseignement primaire", 'P85.2.0', "P85.2.0 - Primary education "),
    ('8531Z', "Enseignement secondaire général", 'P85.3.1', "P85.3.1 - General secondary education "),
    ('8532Z', "Enseignement secondaire technique ou professionnel", 'P85.3.2', "P85.3.2 - Technical and vocational secondary education "),
    ('8541Z', "Enseignement post-secondaire non supérieur", 'P85.4.1', "P85.4.1 - Post-secondary non-tertiary education"),
    ('8542Z', "Enseignement supérieur", 'P85.4.2', "P85.4.2 - Tertiary education"),
    ('8551Z', "Enseignement de disciplines sportives et d'activités de loisirs", 'P85.5.1', "P85.5.1 - Sports and recreation education"),
    ('8552Z', "Enseignement culturel", 'P85.5.2', "P85.5.2 - Cultural education"),
    ('8553Z', "Enseignement de la conduite", 'P85.5.3', "P85.5.3 - Driving school activities"),
    ('8559A', "Formation continue d'adultes", 'P85.5.9', "P85.5.9 - Other education n.e.c."),
    ('8559B', "Autres enseignements", 'P85.5.9', "P85.5.9 - Other education n.e.c."),
    ('8560Z', "Activités de soutien à l'enseignement", 'P85.6.0', "P85.6.0 - Educational support activities"),
    ('8610Z', "Activités hospitalières", 'Q86.1.0', "Q86.1.0 - Hospital activities"),
    ('8621Z', "Activité des médecins généralistes", 'Q86.2.1', "Q86.2.1 - General medical practice activities"),
    ('8622A', "Activités de radiodiagnostic et de radiothérapie", 'Q86.2.2', "Q86.2.2 - Specialist medical practice activities"),
    ('8622B', "Activités chirurgicales", 'Q86.2.2', "Q86.2.2 - Specialist medical practice activities"),
    ('8622C', "Autres activités des médecins spécialistes", 'Q86.2.2', "Q86.2.2 - Specialist medical practice activities"),
    ('8623Z', "Pratique dentaire", 'Q86.2.3', "Q86.2.3 - Dental practice activities"),
    ('8690A', "Ambulances", 'Q86.9.0', "Q86.9.0 - Other human health activities"),
    ('8690B', "Laboratoires d'analyses médicales", 'Q86.9.0', "Q86.9.0 - Other human health activities"),
    ('8690C', "Centres de collecte et banques d'organes", 'Q86.9.0', "Q86.9.0 - Other human health activities"),
    ('8690D', "Activités des infirmiers et des sages-femmes", 'Q86.9.0', "Q86.9.0 - Other human health activities"),
    ('8690E', "Activités des professionnels de la rééducation, de l’appareillage et des pédicures-podologues", 'Q86.9.0', "Q86.9.0 - Other human health activities"),
    ('8690F', "Activités de santé humaine non classées ailleurs", 'Q86.9.0', "Q86.9.0 - Other human health activities"),
    ('8710A', "Hébergement médicalisé pour personnes âgées", 'Q87.1.0', "Q87.1.0 - Residential nursing care activities"),
    ('8710B', "Hébergement médicalisé pour enfants handicapés", 'Q87.1.0', "Q87.1.0 - Residential nursing care activities"), 
    ('8710C', "Hébergement médicalisé pour adultes handicapés et autre hébergement médicalisé", 'Q87.1.0', "Q87.1.0 - Residential nursing care activities"), 
    ('8720A', "Hébergement social pour handicapés mentaux et malades mentaux", 'Q87.2.0', "Q87.2.0 - Residential care activities for mental retardation, mental health and substance abuse"), 
    ('8720B', "Hébergement social pour toxicomanes", 'Q87.2.0', "Q87.2.0 - Residential care activities for mental retardation, mental health and substance abuse"),
    ('8730A', "Hébergement social pour personnes âgées", 'Q87.3.0', "Q87.3.0 - Residential care activities for the elderly and disabled"),
    ('8730B', "Hébergement social pour handicapés  physiques", 'Q87.3.0', "Q87.3.0 - Residential care activities for the elderly and disabled"),
    ('8790A', "Hébergement social pour enfants en difficultés", 'Q87.9.0', "Q87.9.0 - Other residential care activities"), 
    ('8790B', "Hébergement social pour adultes et familles en difficultés et autre hébergement social", 'Q87.9.0', "Q87.9.0 - Other residential care activities"), 
    ('8810A', "Aide à domicile", 'Q88.1.0', "Q88.1.0 - Social work activities without accommodation for the elderly and disabled"),  
    ('8810B', "Accueil ou accompagnement sans hébergement d’adultes handicapés ou de  personnes âgées", 'Q88.1.0', "Q88.1.0 - Social work activities without accommodation for the elderly and disabled"),
    ('8810C', "Aide par le travail", 'Q88.1.0', "Q88.1.0 - Social work activities without accommodation for the elderly and disabled"), 
    ('8891A', "Accueil de jeunes enfants", 'Q88.9.1', "Q88.9.1 - Child day-care activities"),
    ('8891B', "Accueil ou accompagnement sans hébergement d’enfants handicapés", 'Q88.9.1', "Q88.9.1 - Child day-care activities"),
    ('8899A', "Autre accueil ou accompagnement sans hébergement d’enfants et d’adolescents", 'Q88.9.9', "Q88.9.9 - Other social work activities without accommodation n.e.c."),
    ('8899B', "Action sociale sans hébergement n.c.a.", 'Q88.9.9', "Q88.9.9 - Other social work activities without accommodation n.e.c."),
    ('9001Z', "Arts du spectacle vivant", 'R90.0.1', "R90.0.1 - Performing arts"),
    ('9002Z', "Activités de soutien au spectacle vivant", 'R90.0.2', "R90.0.2 - Support activities to performing arts"),
    ('9003A', "Création artistique relevant des arts plastiques", 'R90.0.3', "R90.0.3 - Artistic creation"),
    ('9003B', "Autre création artistique", 'R90.0.3', "R90.0.3 - Artistic creation"),
    ('9004Z', "Gestion de salles de spectacles", 'R90.0.4', "R90.0.4 - Operation of arts facilities"),
    ('9101Z', "Gestion des bibliothèques et des archives", 'R91.0.1', "R91.0.1 - Library and archives activities"),
    ('9102Z', "Gestion des musées", 'R91.0.2', "R91.0.2 - Museums activities"),
    ('9103Z', "Gestion des sites et monuments historiques et des attractions touristiques similaires", 'R91.0.3', "R91.0.3 - Operation of historical sites and buildings and similar visitor attractions"),
    ('9104Z', "Gestion des jardins botaniques et zoologiques et des réserves naturelles", 'R91.0.4', "R91.0.4 - Botanical and zoological gardens and nature reserves activities"),
    ('9200Z', "Organisation de jeux de hasard et d'argent", 'R92.0.0', "R92.0.0 - Gambling and betting activities"),
    ('9311Z', "Gestion d'installations sportives", 'R93.1.1', "R93.1.1 - Operation of sports facilities"),
    ('9312Z', "Activités de clubs de sports", 'R93.1.2', "R93.1.2 - Activities of sports clubs"),
    ('9313Z', "Activités des centres de culture physique", 'R93.1.3', "R93.1.3 - Fitness facilities"),
    ('9319Z', "Autres activités liées au sport", 'R93.1.9', "R93.1.9 - Other sports activities"),
    ('9321Z', "Activités des parcs d'attractions et parcs à thèmes", 'R93.2.1', "R93.2.1 - Activities of amusement parks and theme parks"),
    ('9329Z', "Autres activités récréatives et de loisirs", 'R93.2.9', "R93.2.9 - Other amusement and recreation activities"),
    ('9411Z', "Activités des organisations patronales et consulaires", 'S94.1.1', "S94.1.1 - Activities of business and employers membership organisations"),
    ('9412Z', "Activités des organisations professionnelles", 'S94.1.2', "S94.1.2 - Activities of professional membership organisations"),
    ('9420Z', "Activités des syndicats de salariés", 'S94.2.0', "S94.2.0 - Activities of trade unions"),
    ('9491Z', "Activités des organisations religieuses", 'S94.9.1', "S94.9.1 - Activities of religious organisations"),
    ('9492Z', "Activités des organisations politiques", 'S94.9.2', "S94.9.2 - Activities of political organisations"),
    ('9499Z', "Autres organisations fonctionnant par adhésion volontaire", 'S94.9.9', "S94.9.9 - Activities of other membership organisations n.e.c."),
    ('9511Z', "Réparation d'ordinateurs et d'équipements périphériques", 'S95.1.1', "S95.1.1 - Repair of computers and peripheral equipment"),
    ('9512Z', "Réparation d'équipements de communication", 'S95.1.2', "S95.1.2 - Repair of communication equipment"),
    ('9521Z', "Réparation de produits électroniques grand public", 'S95.2.1', "S95.2.1 - Repair of consumer electronics"),
    ('9522Z', "Réparation d'appareils électroménagers et d'équipements pour la maison et le jardin", 'S95.2.2', "S95.2.2 - Repair of household appliances and home and garden equipment"),
    ('9523Z', "Réparation de chaussures et d'articles en cuir", 'S95.2.3', "S95.2.3 - Repair of footwear and leather goods"),
    ('9524Z', "Réparation de meubles et d'équipements du foyer", 'S95.2.4', "S95.2.4 - Repair of furniture and home furnishings"),
    ('9525Z', "Réparation d'articles d'horlogerie et de bijouterie", 'S95.2.5', "S95.2.5 - Repair of watches, clocks and jewellery"),
    ('9529Z', "Réparation d'autres biens personnels et domestiques", 'S95.2.9', "S95.2.9 - Repair of other personal and household goods"),
    ('9601A', "Blanchisserie-teinturerie de gros", 'S96.0.1', "S96.0.1 - Washing and (dry-)cleaning of textile and fur products"),
    ('9601B', "Blanchisserie-teinturerie de détail", 'S96.0.1', "S96.0.1 - Washing and (dry-)cleaning of textile and fur products"),
    ('9602A', "Coiffure", 'S96.0.2', "S96.0.2 - Hairdressing and other beauty treatment"),
    ('9602B', "Soins de beauté", 'S96.0.2', "S96.0.2 - Hairdressing and other beauty treatment"),
    ('9603Z', "Services funéraires", 'S96.0.3', "S96.0.3 - Funeral and related activities"),
    ('9604Z', "Entretien corporel", 'S96.0.4', "S96.0.4 - Physical well-being activities"),
    ('9609Z', "Autres services personnels n.c.a.", 'S96.0.9', "S96.0.9 - Other personal service activities n.e.c."),
    ('9700Z', "Activités des ménages en tant qu'employeurs de personnel domestique", 'T97.0.0', "T97.0.0 - Activities of households as employers of domestic personnel"),
    ('9810Z', "Activités indifférenciées des ménages en tant que producteurs de biens pour usage propre", 'T98.1.0', "T98.1.0 - Undifferentiated goods-producing activities of private households for own use"),
    ('9820Z', "Activités indifférenciées des ménages en tant que producteurs de services pour usage propre", 'T98.2.0', "T98.2.0 - Undifferentiated service-producing activities of private households for own use"),
    ('9900Z', "Activités des organisations et organismes extraterritoriaux", 'U99.0.0', "U99.0.0 - Activities of extraterritorial organisations and bodies")
SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
    }
}
