<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190222110910 extends AbstractMigration
{
    public function getDescription() : string
    {
        return 'Initial migration';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('SET FOREIGN_KEY_CHECKS=0');
        $this->addSql('TRUNCATE TABLE migration_versions');
        $this->addSql('CREATE TABLE user_agent (id INT AUTO_INCREMENT NOT NULL, id_client INT NOT NULL, browser_name VARCHAR(48) DEFAULT NULL, browser_version VARCHAR(32) DEFAULT NULL, device_model VARCHAR(48) DEFAULT NULL, device_brand VARCHAR(48) DEFAULT NULL, device_type VARCHAR(32) DEFAULT NULL, user_agent_string VARCHAR(256) NOT NULL, added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', INDEX IDX_C44967C5E173B1B8 (id_client), INDEX idx_user_agent_client_browser_device_model_brand_type (id_client, browser_name, device_model, device_brand, device_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('DROP TABLE accept_cookies');
        $this->addSql('DROP TABLE banques');
        $this->addSql('DROP TABLE daily_state_balance_history');
        $this->addSql('DROP TABLE mailjet_event_blocked');
        $this->addSql('DROP TABLE mailjet_event_bounce');
        $this->addSql('DROP TABLE mailjet_event_click');
        $this->addSql('DROP TABLE mailjet_event_open');
        $this->addSql('DROP TABLE mailjet_event_spam');
        $this->addSql('DROP TABLE mailjet_event_unsub');
        $this->addSql('DROP TABLE non_migrated_transactions');
        $this->addSql('DROP TABLE prescripteurs');
        $this->addSql('DROP TABLE projects_remb');
        $this->addSql('DROP TABLE projects_remb_log');
        $this->addSql('DROP TABLE regularization_operation_history');
        $this->addSql('ALTER TABLE settings CHANGE type type VARCHAR(191) NOT NULL, CHANGE value value MEDIUMTEXT NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE settings RENAME INDEX type TO unq_settings_type');
        $this->addSql('ALTER TABLE tax_type CHANGE rate rate NUMERIC(5, 2) NOT NULL');
        $this->addSql('ALTER TABLE company_status CHANGE id id SMALLINT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE clients_status CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE risk_data_monitoring_type CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('CREATE INDEX IDX_CEBACC612374BEE7 ON risk_data_monitoring_type (id_project_eligibility_rule)');
        $this->addSql('ALTER TABLE virements DROP FOREIGN KEY fk_virements_id_bank_account');
        $this->addSql('ALTER TABLE virements DROP FOREIGN KEY fk_virements_id_client');
        $this->addSql('ALTER TABLE virements DROP FOREIGN KEY fk_virements_id_project');
        $this->addSql('ALTER TABLE virements DROP FOREIGN KEY fk_virements_id_user_request');
        $this->addSql('ALTER TABLE virements DROP FOREIGN KEY fk_virements_id_user_validation');
        $this->addSql('ALTER TABLE virements DROP id_transaction, CHANGE id_bank_account id_bank_account INT DEFAULT NULL, CHANGE montant montant INT NOT NULL, CHANGE type type SMALLINT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE receptions DROP INDEX reception_id_reception_rejected, ADD UNIQUE INDEX UNIQ_B08F24D7ADB6538E (id_reception_rejected)');
        $this->addSql('ALTER TABLE receptions DROP FOREIGN KEY fk_receptions_id_client');
        $this->addSql('ALTER TABLE receptions DROP FOREIGN KEY fk_receptions_id_project');
        $this->addSql('ALTER TABLE receptions DROP FOREIGN KEY fk_receptions_id_reception_rejected');
        $this->addSql('ALTER TABLE receptions DROP FOREIGN KEY fk_receptions_id_user');
        $this->addSql('ALTER TABLE receptions DROP FOREIGN KEY fk_receptions_rejection_iso_code');
        $this->addSql('ALTER TABLE receptions CHANGE montant montant INT NOT NULL, CHANGE type type SMALLINT NOT NULL, CHANGE type_remb type_remb SMALLINT NOT NULL, CHANGE status_virement status_virement SMALLINT NOT NULL, CHANGE status_prelevement status_prelevement SMALLINT NOT NULL, CHANGE status_bo status_bo SMALLINT NOT NULL, CHANGE assignment_date assignment_date DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE comment comment LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE project_product_assessment DROP FOREIGN KEY fk_project_product_assessment_id_product');
        $this->addSql('ALTER TABLE project_product_assessment DROP FOREIGN KEY fk_project_product_assessment_id_product_attribute_type');
        $this->addSql('ALTER TABLE project_product_assessment DROP FOREIGN KEY fk_project_product_assessment_id_project');
        $this->addSql('ALTER TABLE project_product_assessment CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_product id_product INT NOT NULL, CHANGE id_product_attribute_type id_product_attribute_type SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE bids DROP FOREIGN KEY fk_bids_id_autobid');
        $this->addSql('ALTER TABLE bids DROP FOREIGN KEY fk_bids_id_lender_account');
        $this->addSql('ALTER TABLE bids DROP FOREIGN KEY fk_bids_id_project');
        $this->addSql('ALTER TABLE bids CHANGE amount amount INT NOT NULL, CHANGE rate rate NUMERIC(3, 1) NOT NULL, CHANGE ordre ordre INT DEFAULT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE notifications DROP FOREIGN KEY fk_notifications_id_lender');
        $this->addSql('ALTER TABLE notifications CHANGE type type SMALLINT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE product_underlying_contract DROP FOREIGN KEY fk_product_underlying_contract_contract');
        $this->addSql('ALTER TABLE product_underlying_contract DROP FOREIGN KEY fk_product_underlying_contract_product');
        $this->addSql('ALTER TABLE product_underlying_contract CHANGE id_product id_product INT NOT NULL, CHANGE id_contract id_contract INT NOT NULL, DROP updated');
        $this->addSql('ALTER TABLE product_underlying_contract RENAME INDEX fk_product_underlying_contract_contract TO IDX_E8A97A94B954C4CC');
        $this->addSql('ALTER TABLE clients_status_history DROP FOREIGN KEY fk_clients_status_history_id_status');
        $this->addSql('ALTER TABLE clients_status_history CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_status id_status INT NOT NULL, CHANGE id_user id_user INT NOT NULL, CHANGE numero_relance numero_relance INT DEFAULT NULL');
        $this->addSql('ALTER TABLE underlying_contract_attribute_type CHANGE id_type id_type SMALLINT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE tree CHANGE id_parent id_parent INT NOT NULL, CHANGE id_template id_template INT NOT NULL, CHANGE id_user id_user INT NOT NULL, CHANGE slug slug VARCHAR(191) NOT NULL, CHANGE img_menu img_menu VARCHAR(191) NOT NULL, CHANGE menu_title menu_title VARCHAR(191) NOT NULL, CHANGE meta_title meta_title VARCHAR(191) NOT NULL, CHANGE meta_description meta_description MEDIUMTEXT NOT NULL, CHANGE meta_keywords meta_keywords MEDIUMTEXT NOT NULL, CHANGE ordre ordre INT NOT NULL, CHANGE status status INT NOT NULL, CHANGE status_menu status_menu INT NOT NULL, CHANGE prive prive INT NOT NULL, CHANGE indexation indexation INT NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE nationalites_v2 CHANGE id_nationalite id_nationalite INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE sponsorship_campaign CHANGE status status SMALLINT NOT NULL, CHANGE validity_days validity_days SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE echeanciers_emprunteur DROP FOREIGN KEY fk_echeanciers_emprunteur_id_project');
        $this->addSql('ALTER TABLE echeanciers_emprunteur CHANGE status_emprunteur status_emprunteur SMALLINT NOT NULL, CHANGE status_ra status_ra SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_status_history_reason DROP FOREIGN KEY fk_project_abandon_reason_id_abandon_reason');
        $this->addSql('ALTER TABLE project_status_history_reason DROP FOREIGN KEY fk_project_rejection_reason_id_rejection_reason');
        $this->addSql('ALTER TABLE project_status_history_reason DROP FOREIGN KEY fk_project_status_history_id_project_status_history');
        $this->addSql('ALTER TABLE project_status_history_reason CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE address_type CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE clients_adresses DROP FOREIGN KEY fk_clients_adresses_id_client');
        $this->addSql('ALTER TABLE clients_adresses CHANGE defaut defaut INT NOT NULL, CHANGE type type INT NOT NULL, CHANGE meme_adresse_fiscal meme_adresse_fiscal TINYINT(1) DEFAULT NULL, CHANGE adresse_fiscal adresse_fiscal VARCHAR(191) DEFAULT NULL, CHANGE ville_fiscal ville_fiscal VARCHAR(191) DEFAULT NULL, CHANGE cp_fiscal cp_fiscal VARCHAR(191) DEFAULT NULL, CHANGE status status INT DEFAULT NULL');
        $this->addSql('ALTER TABLE operation_sub_type DROP FOREIGN KEY fk_operation_sub_type_id_parent');
        $this->addSql('ALTER TABLE clients_history_actions DROP FOREIGN KEY fk_clients_history_actions_id_client');
        $this->addSql('ALTER TABLE companies CHANGE id_status id_status SMALLINT DEFAULT NULL, CHANGE legal_form_code legal_form_code VARCHAR(10) DEFAULT NULL, CHANGE execices_comptables execices_comptables SMALLINT DEFAULT NULL, CHANGE id_address id_address INT DEFAULT NULL, CHANGE id_postal_address id_postal_address INT DEFAULT NULL, CHANGE status_adresse_correspondance status_adresse_correspondance SMALLINT DEFAULT NULL, CHANGE status_client status_client SMALLINT DEFAULT NULL, CHANGE status_conseil_externe_entreprise status_conseil_externe_entreprise SMALLINT DEFAULT NULL, CHANGE preciser_conseil_externe_entreprise preciser_conseil_externe_entreprise VARCHAR(191) DEFAULT NULL, CHANGE civilite_dirigeant civilite_dirigeant VARCHAR(255) DEFAULT NULL, CHANGE nom_dirigeant nom_dirigeant VARCHAR(191) DEFAULT NULL, CHANGE prenom_dirigeant prenom_dirigeant VARCHAR(191) DEFAULT NULL, CHANGE fonction_dirigeant fonction_dirigeant VARCHAR(191) DEFAULT NULL, CHANGE email_dirigeant email_dirigeant VARCHAR(191) DEFAULT NULL, CHANGE phone_dirigeant phone_dirigeant VARCHAR(45) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AD3D3C6F1 ON companies (id_address)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AAA4846F1 ON companies (id_postal_address)');
        $this->addSql('ALTER TABLE lender_tax_exemption DROP FOREIGN KEY fk_lender_tax_exemption_id_lender');
        $this->addSql('ALTER TABLE lender_tax_exemption CHANGE year year SMALLINT NOT NULL, CHANGE id_user id_user INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_17B0DAB06B3CA4B ON lender_tax_exemption (id_user)');
        $this->addSql('ALTER TABLE lender_tax_exemption RENAME INDEX unq_id_lender_year TO id_lender_year');
        $this->addSql('ALTER TABLE translations RENAME INDEX translation TO unq_translation');
        $this->addSql('ALTER TABLE pays CHANGE vigilance_status vigilance_status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE debt_collection_fee_detail DROP FOREIGN KEY fk_debt_collection_fee_detail_id_debt_collection_mission');
        $this->addSql('ALTER TABLE debt_collection_fee_detail DROP FOREIGN KEY fk_debt_collection_fee_detail_id_loan');
        $this->addSql('ALTER TABLE debt_collection_fee_detail DROP FOREIGN KEY fk_debt_collection_fee_detail_id_wallet_creditor');
        $this->addSql('ALTER TABLE debt_collection_fee_detail DROP FOREIGN KEY fk_debt_collection_fee_detail_id_wallet_debtor');
        $this->addSql('ALTER TABLE debt_collection_fee_detail DROP FOREIGN KEY fk_debt_collection_fee_detail_id_wire_transfer_in');
        $this->addSql('ALTER TABLE debt_collection_fee_detail CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_debt_collection_mission id_debt_collection_mission INT NOT NULL, CHANGE id_type id_type SMALLINT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('DROP INDEX idx_mail_templates_type ON mail_templates');
        $this->addSql('ALTER TABLE mail_templates CHANGE status status SMALLINT NOT NULL');
        $this->addSql('CREATE INDEX type ON mail_templates (type, locale, status, part)');
        $this->addSql('ALTER TABLE clients_gestion_notif_log CHANGE type type VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE offres_bienvenues_details CHANGE montant montant INT NOT NULL, CHANGE status status SMALLINT NOT NULL, CHANGE type type SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE client_address DROP FOREIGN KEY fk_client_address_id_client');
        $this->addSql('ALTER TABLE client_address DROP FOREIGN KEY fk_client_address_id_type');
        $this->addSql('ALTER TABLE client_address DROP FOREIGN KEY fk_client_address_pays_id_country');
        $this->addSql('ALTER TABLE client_address CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_type id_type INT NOT NULL');
        $this->addSql('ALTER TABLE client_address RENAME INDEX idx_client_address_id_type TO IDX_5F732BFC7FE4B2B');
        $this->addSql('ALTER TABLE wallet_balance_history DROP FOREIGN KEY wallet_balance_history_id_autobid_fk');
        $this->addSql('ALTER TABLE wallet_balance_history DROP FOREIGN KEY wallet_balance_history_id_bid_fk');
        $this->addSql('ALTER TABLE wallet_balance_history DROP FOREIGN KEY wallet_balance_history_id_loan_fk');
        $this->addSql('ALTER TABLE wallet_balance_history DROP FOREIGN KEY wallet_balance_history_id_operation_fk');
        $this->addSql('ALTER TABLE wallet_balance_history DROP FOREIGN KEY wallet_balance_history_id_project_fk');
        $this->addSql('ALTER TABLE wallet_balance_history DROP FOREIGN KEY wallet_balance_history_id_wallet_fk');
        $this->addSql('ALTER TABLE wallet_balance_history RENAME INDEX idx_added TO idx_wallet_balance_history_added');
        $this->addSql('ALTER TABLE infolegale_executive_personal_change CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE siren siren VARCHAR(9) DEFAULT NULL, CHANGE siren_if_company siren_if_company VARCHAR(9) DEFAULT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE close_out_netting_repayment DROP FOREIGN KEY fk_close_out_netting_repayment_id_loan');
        $this->addSql('ALTER TABLE close_out_netting_repayment CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE partner_product DROP FOREIGN KEY partner_product_ibfk_1');
        $this->addSql('ALTER TABLE partner_product DROP FOREIGN KEY partner_product_ibfk_2');
        $this->addSql('ALTER TABLE partner_product CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_partner id_partner INT NOT NULL, CHANGE id_product id_product INT NOT NULL, CHANGE commission_rate_funds commission_rate_funds NUMERIC(4, 2) NOT NULL, CHANGE commission_rate_repayment commission_rate_repayment NUMERIC(4, 2) NOT NULL');
        $this->addSql('ALTER TABLE client_address_attachment DROP FOREIGN KEY fk_client_address_attachement_id_client_address');
        $this->addSql('ALTER TABLE client_address_attachment DROP FOREIGN KEY fk_id_client_address_attachment');
        $this->addSql('ALTER TABLE client_address_attachment CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_client_address id_client_address INT NOT NULL');
        $this->addSql('ALTER TABLE partner_project_attachment DROP FOREIGN KEY partner_project_attachment_ibfk_1');
        $this->addSql('ALTER TABLE partner_project_attachment DROP FOREIGN KEY partner_project_attachment_ibfk_2');
        $this->addSql('ALTER TABLE partner_project_attachment CHANGE id_partner id_partner INT NOT NULL, CHANGE id_attachment_type id_attachment_type INT NOT NULL, CHANGE mandatory mandatory TINYINT(1) NOT NULL, CHANGE `rank` `rank` SMALLINT DEFAULT NULL');
        $this->addSql('DROP INDEX id_bilan ON company_balance');
        $this->addSql('ALTER TABLE company_balance CHANGE id_balance_type id_balance_type INT DEFAULT NULL, CHANGE value value DOUBLE PRECISION NOT NULL');
        $this->addSql('ALTER TABLE parrainages CHANGE status status INT NOT NULL');
        $this->addSql('ALTER TABLE company_balance_type DROP FOREIGN KEY fk_company_balance_type_company_tax_form_type');
        $this->addSql('ALTER TABLE company_balance_type CHANGE code code VARCHAR(3) NOT NULL');
        $this->addSql('ALTER TABLE company_status_history DROP FOREIGN KEY fk_company_status_history_id_company');
        $this->addSql('ALTER TABLE company_status_history DROP FOREIGN KEY fk_company_status_history_id_status');
        $this->addSql('ALTER TABLE company_status_history DROP FOREIGN KEY fk_company_status_history_id_user');
        $this->addSql('ALTER TABLE company_status_history CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_status id_status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_beneficial_owner_universign DROP FOREIGN KEY fk_project_beneficial_owner_universign_id_declaration');
        $this->addSql('ALTER TABLE project_beneficial_owner_universign DROP FOREIGN KEY fk_project_beneficial_owner_universign_id_project');
        $this->addSql('ALTER TABLE project_beneficial_owner_universign CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE transfer_attachment DROP FOREIGN KEY fk_transfer_attachment_id_attachment');
        $this->addSql('ALTER TABLE transfer_attachment DROP FOREIGN KEY fk_transfer_attachment_id_transfer');
        $this->addSql('ALTER TABLE transfer_attachment CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE bank_account DROP FOREIGN KEY fk_bank_account_id_attachment');
        $this->addSql('ALTER TABLE bank_account DROP FOREIGN KEY fk_bank_account_id_client');
        $this->addSql('ALTER TABLE bank_account CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_53A23E0ADCD5596C ON bank_account (id_attachment)');
        $this->addSql('ALTER TABLE bank_account RENAME INDEX iban_unique TO id_client_iban_UNIQUE');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY fk_operation_id_repayment_task_log');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY fk_operation_id_sponsorship');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY fk_operation_id_sub_type');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_backpayline_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_loan_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_payment_schedule_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_project_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_repayment_schedule_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_transfer_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_type_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_wallet_creditor_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_wallet_debtor_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_welcome_offer_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_wire_transfer_in_fk');
        $this->addSql('ALTER TABLE operation DROP FOREIGN KEY operation_id_wire_transfer_out_fk');
        $this->addSql('ALTER TABLE operation CHANGE id_repayment_task_log id_repayment_task_log INT DEFAULT NULL');
        $this->addSql('ALTER TABLE operation RENAME INDEX idx_operation_id_repayment_task_log TO IDX_1981A66DE30EA0D4');
        $this->addSql('DROP INDEX id_link ON temporary_links_login');
        $this->addSql('ALTER TABLE temporary_links_login CHANGE accessed accessed DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('CREATE INDEX fk_temporary_links_login_id_client ON temporary_links_login (id_client)');
        $this->addSql('ALTER TABLE prelevements DROP FOREIGN KEY fk_prelevements_id_client');
        $this->addSql('ALTER TABLE prelevements DROP FOREIGN KEY fk_prelevements_id_project');
        $this->addSql('ALTER TABLE prelevements DROP id_transaction, CHANGE montant montant INT NOT NULL, CHANGE type_prelevement type_prelevement SMALLINT NOT NULL, CHANGE type type SMALLINT NOT NULL, CHANGE num_prelevement num_prelevement SMALLINT NOT NULL, CHANGE status status SMALLINT NOT NULL, CHANGE date_execution_demande_prelevement date_execution_demande_prelevement DATE NOT NULL');
        $this->addSql('ALTER TABLE prelevements RENAME INDEX fk_prelevements_id_project TO idx_prelevements_id_project');
        $this->addSql('ALTER TABLE project_rejection_reason CHANGE status status TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE project_rejection_reason RENAME INDEX label TO UNIQ_10EE25EFEA750E8');
        $this->addSql('ALTER TABLE beneficial_owner DROP FOREIGN KEY fk_beneficial_owner_id_client');
        $this->addSql('ALTER TABLE beneficial_owner DROP FOREIGN KEY fk_beneficial_owner_id_declaration');
        $this->addSql('CREATE INDEX IDX_F5526F137FE4B2B ON beneficial_owner (id_type)');
        $this->addSql('ALTER TABLE beneficial_owner RENAME INDEX idx_beneficial_owner_id_declaration TO IDX_F5526F1362B11735');
        $this->addSql('ALTER TABLE beneficial_owner RENAME INDEX idx_beneficial_owner_id_client TO IDX_F5526F13E173B1B8');
        $this->addSql('ALTER TABLE product_attribute DROP FOREIGN KEY fk_idx_product_attribute_id_rule');
        $this->addSql('ALTER TABLE product_attribute DROP FOREIGN KEY fk_product_attribute_id_product');
        $this->addSql('ALTER TABLE product_attribute DROP FOREIGN KEY fk_product_attribute_id_type');
        $this->addSql('ALTER TABLE product_attribute CHANGE id_attribute id_attribute INT AUTO_INCREMENT NOT NULL, CHANGE id_product id_product INT NOT NULL, CHANGE id_type id_type SMALLINT NOT NULL, CHANGE id_rule id_rule INT DEFAULT NULL');
        $this->addSql('ALTER TABLE product_attribute RENAME INDEX idx_product_attribute_id_rule TO IDX_94DA5976CDF8B0CE');
        $this->addSql('ALTER TABLE close_out_netting_payment DROP INDEX fk_close_out_netting_payment_id_email_content, ADD UNIQUE INDEX UNIQ_5EB1A212FD2D8903 (id_email_content)');
        $this->addSql('ALTER TABLE close_out_netting_payment DROP FOREIGN KEY fk_close_out_netting_payment_id_project');
        $this->addSql('ALTER TABLE close_out_netting_payment CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5EB1A212F12E799E ON close_out_netting_payment (id_project)');
        $this->addSql('ALTER TABLE attachment DROP FOREIGN KEY fk_attachment_id_client');
        $this->addSql('ALTER TABLE attachment DROP FOREIGN KEY fk_attachment_id_type');
        $this->addSql('ALTER TABLE company_beneficial_owner_declaration DROP FOREIGN KEY fk_beneficial_owner_declaration_id_company');
        $this->addSql('ALTER TABLE company_beneficial_owner_declaration CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_repayment_task_log DROP FOREIGN KEY fk_project_repayment_task_log_id_task');
        $this->addSql('ALTER TABLE project_repayment_task_log CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_task id_task INT NOT NULL, CHANGE repayment_nb repayment_nb INT NOT NULL');
        $this->addSql('ALTER TABLE lender_statistic DROP FOREIGN KEY fk_lender_statistic_id_wallet');
        $this->addSql('ALTER TABLE lender_statistic CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE redirections CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_attachment DROP FOREIGN KEY fk_project_attachment_id_attachment');
        $this->addSql('ALTER TABLE project_attachment DROP FOREIGN KEY fk_project_attachment_id_project');
        $this->addSql('ALTER TABLE project_attachment CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE project_repayment_detail DROP FOREIGN KEY fk_project_repayment_task_details_id_loan');
        $this->addSql('ALTER TABLE project_repayment_detail DROP FOREIGN KEY fk_project_repayment_task_details_id_repayment_schedule');
        $this->addSql('ALTER TABLE project_repayment_detail DROP FOREIGN KEY fk_project_repayment_task_details_id_task');
        $this->addSql('ALTER TABLE project_repayment_detail DROP FOREIGN KEY fk_project_repayment_task_details_id_task_log');
        $this->addSql('ALTER TABLE project_repayment_detail CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_task id_task INT NOT NULL, CHANGE id_task_log id_task_log INT DEFAULT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE ws_external_resource CHANGE is_available is_available TINYINT(1) NOT NULL, CHANGE validity_days validity_days SMALLINT DEFAULT -1 NOT NULL');
        $this->addSql('ALTER TABLE bids_logs CHANGE nb_bids_encours nb_bids_encours INT NOT NULL, CHANGE nb_bids_ko nb_bids_ko INT NOT NULL, CHANGE total_bids_ko total_bids_ko INT NOT NULL, CHANGE total_bids total_bids INT NOT NULL, CHANGE rate_max rate_max NUMERIC(2, 1) NOT NULL');
        $this->addSql('ALTER TABLE project_eligibility_rule_set CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_contract_assessment DROP FOREIGN KEY fk_project_contract_assessment_id_contract');
        $this->addSql('ALTER TABLE project_contract_assessment DROP FOREIGN KEY fk_project_contract_assessment_id_contract_attribute_type');
        $this->addSql('ALTER TABLE project_contract_assessment DROP FOREIGN KEY fk_project_contract_assessment_id_project');
        $this->addSql('ALTER TABLE project_contract_assessment CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_contract id_contract INT NOT NULL, CHANGE id_contract_attribute_type id_contract_attribute_type SMALLINT NOT NULL');
        $this->addSql('DROP INDEX idx_client_nom ON clients');
        $this->addSql('DROP INDEX email ON clients');
        $this->addSql('ALTER TABLE clients CHANGE id_address id_address INT DEFAULT NULL, CHANGE id_postal_address id_postal_address INT DEFAULT NULL, CHANGE type type SMALLINT DEFAULT NULL, CHANGE funds_origin funds_origin SMALLINT DEFAULT NULL, CHANGE funds_origin_detail funds_origin_detail VARCHAR(255) DEFAULT NULL, CHANGE etape_inscription_preteur etape_inscription_preteur SMALLINT DEFAULT NULL, CHANGE status_inscription_preteur status_inscription_preteur SMALLINT DEFAULT NULL, CHANGE origine origine SMALLINT DEFAULT NULL, CHANGE optin1 optin1 SMALLINT DEFAULT NULL, CHANGE optin2 optin2 SMALLINT DEFAULT NULL, CHANGE id_client_status_history id_client_status_history INT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C82E74D3D3C6F1 ON clients (id_address)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C82E74AA4846F1 ON clients (id_postal_address)');
        $this->addSql('CREATE INDEX idx_client_nom ON clients (nom)');
        $this->addSql('CREATE INDEX email ON clients (email)');
        $this->addSql('ALTER TABLE clients_history ADD id_user_agent INT DEFAULT NULL, ADD ip VARCHAR(45) DEFAULT NULL, ADD country_iso_code VARCHAR(2) DEFAULT NULL, ADD city VARCHAR(64) DEFAULT NULL, CHANGE type type SMALLINT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('CREATE INDEX idx_clients_history_ip ON clients_history (ip)');
        $this->addSql('CREATE INDEX idx_clients_history_added ON clients_history (added)');
        $this->addSql('CREATE INDEX idx_clients_history_id_user_agent ON clients_history (id_user_agent)');
        $this->addSql('ALTER TABLE elements CHANGE id_template id_template INT NOT NULL, CHANGE id_bloc id_bloc INT NOT NULL, CHANGE name name VARCHAR(191) NOT NULL, CHANGE slug slug VARCHAR(191) NOT NULL, CHANGE ordre ordre INT DEFAULT 0 NOT NULL, CHANGE type_element type_element VARCHAR(50) NOT NULL, CHANGE status status SMALLINT NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE remboursement_anticipe_mail_a_envoyer CHANGE statut statut SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_attachment_type DROP FOREIGN KEY fk_project_attachment_type_id_category');
        $this->addSql('ALTER TABLE project_attachment_type DROP FOREIGN KEY fk_project_attachment_type_id_type');
        $this->addSql('ALTER TABLE project_attachment_type CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_category id_category INT DEFAULT NULL, CHANGE `rank` `rank` SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_attachment_type RENAME INDEX fk_project_attachment_type_id_category TO IDX_4C9C36E65697F554');
        $this->addSql('ALTER TABLE project_attachment_type RENAME INDEX unq_project_attachment_type_id_type TO UNIQ_4C9C36E67FE4B2B');
        $this->addSql('ALTER TABLE projects_notes CHANGE pre_scoring pre_scoring SMALLINT DEFAULT NULL, CHANGE performance_financiere performance_financiere NUMERIC(3, 1) DEFAULT NULL, CHANGE structure structure NUMERIC(3, 1) DEFAULT NULL, CHANGE rentabilite rentabilite NUMERIC(3, 1) DEFAULT NULL, CHANGE tresorerie tresorerie NUMERIC(3, 1) DEFAULT NULL, CHANGE marche_opere marche_opere NUMERIC(3, 1) DEFAULT NULL, CHANGE global global NUMERIC(3, 1) DEFAULT NULL, CHANGE individuel individuel NUMERIC(3, 1) DEFAULT NULL, CHANGE dirigeance dirigeance NUMERIC(3, 1) DEFAULT NULL, CHANGE indicateur_risque_dynamique indicateur_risque_dynamique NUMERIC(3, 1) DEFAULT NULL, CHANGE note note NUMERIC(3, 1) DEFAULT NULL, CHANGE performance_financiere_comite performance_financiere_comite NUMERIC(3, 1) DEFAULT NULL, CHANGE structure_comite structure_comite NUMERIC(3, 1) DEFAULT NULL, CHANGE rentabilite_comite rentabilite_comite NUMERIC(3, 1) DEFAULT NULL, CHANGE tresorerie_comite tresorerie_comite NUMERIC(3, 1) DEFAULT NULL, CHANGE marche_opere_comite marche_opere_comite NUMERIC(3, 1) DEFAULT NULL, CHANGE global_comite global_comite NUMERIC(3, 1) DEFAULT NULL, CHANGE individuel_comite individuel_comite NUMERIC(3, 1) DEFAULT NULL, CHANGE dirigeance_comite dirigeance_comite NUMERIC(3, 1) DEFAULT NULL, CHANGE indicateur_risque_dynamique_comite indicateur_risque_dynamique_comite NUMERIC(3, 1) DEFAULT NULL, CHANGE note_comite note_comite NUMERIC(3, 1) DEFAULT NULL');
        $this->addSql('ALTER TABLE projects_notes RENAME INDEX id_project TO UNIQ_949AF2B2F12E799E');
        $this->addSql('ALTER TABLE insee CHANGE CDC CDC SMALLINT DEFAULT NULL, CHANGE CHEFLIEU CHEFLIEU SMALLINT DEFAULT NULL, CHANGE REG REG SMALLINT DEFAULT NULL, CHANGE DEP DEP SMALLINT DEFAULT NULL, CHANGE COM COM SMALLINT DEFAULT NULL, CHANGE AR AR SMALLINT DEFAULT NULL, CHANGE CT CT SMALLINT DEFAULT NULL, CHANGE TNCC TNCC SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE tree_elements CHANGE id_tree id_tree INT NOT NULL, CHANGE id_element id_element INT NOT NULL, CHANGE value value LONGTEXT NOT NULL, CHANGE status status SMALLINT DEFAULT 0 NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE factures CHANGE type_commission type_commission SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE lender_questionnaire_question CHANGE id_lender_questionnaire_question id_lender_questionnaire_question INT AUTO_INCREMENT NOT NULL, CHANGE id_lender_questionnaire id_lender_questionnaire INT DEFAULT NULL, CHANGE `order` `order` INT NOT NULL');
        $this->addSql('ALTER TABLE debt_collection_mission_payment_schedule DROP FOREIGN KEY fk_dc_mission_payment_schedule_id_mission');
        $this->addSql('ALTER TABLE debt_collection_mission_payment_schedule DROP FOREIGN KEY fk_dc_mission_payment_schedule_id_payment');
        $this->addSql('ALTER TABLE debt_collection_mission_payment_schedule CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_mission id_mission INT NOT NULL, CHANGE capital capital NUMERIC(11, 2) NOT NULL, CHANGE interest interest NUMERIC(11, 2) NOT NULL, CHANGE commission_vat_incl commission_vat_incl NUMERIC(11, 2) NOT NULL');
        $this->addSql('ALTER TABLE backpayline DROP FOREIGN KEY fk_backpayline_id_wallet');
        $this->addSql('ALTER TABLE partner_type CHANGE id id SMALLINT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE projects_status_history_details CHANGE date date DATE DEFAULT NULL, CHANGE receiver receiver MEDIUMTEXT NOT NULL');
        $this->addSql('ALTER TABLE wire_transfer_out_universign DROP FOREIGN KEY fk_wire_transfer_out_universign_id_wire_transfer_out');
        $this->addSql('ALTER TABLE wire_transfer_out_universign CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_43BD8066FF4BCDA2 ON wire_transfer_out_universign (id_wire_transfer_out)');
        $this->addSql('ALTER TABLE lender_evaluation_log CHANGE id_lender_evaluation_log id_lender_evaluation_log INT AUTO_INCREMENT NOT NULL, CHANGE id_lender_evaluation id_lender_evaluation INT NOT NULL');
        $this->addSql('ALTER TABLE lender_evaluation_log RENAME INDEX id_lender_evaluation TO IDX_AD0CE8A467433907');
        $this->addSql('ALTER TABLE zones CHANGE name name VARCHAR(191) NOT NULL, CHANGE slug slug VARCHAR(191) NOT NULL, CHANGE status status TINYINT(1) NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE offres_bienvenues CHANGE montant montant INT NOT NULL, CHANGE status status TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE client_atypical_operation DROP FOREIGN KEY client_atypical_operation_ibfk_1');
        $this->addSql('ALTER TABLE client_atypical_operation DROP FOREIGN KEY client_atypical_operation_ibfk_2');
        $this->addSql('ALTER TABLE client_atypical_operation CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_rule id_rule INT NOT NULL, CHANGE detection_status detection_status SMALLINT NOT NULL');
        $this->addSql('CREATE INDEX IDX_D9F9D95C6B3CA4B ON client_atypical_operation (id_user)');
        $this->addSql('ALTER TABLE company_address DROP FOREIGN KEY fk_company_address_id_company');
        $this->addSql('ALTER TABLE company_address DROP FOREIGN KEY fk_company_address_id_type');
        $this->addSql('ALTER TABLE company_address DROP FOREIGN KEY fk_company_address_pays_id_country');
        $this->addSql('ALTER TABLE company_address CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_type id_type INT NOT NULL');
        $this->addSql('ALTER TABLE company_address RENAME INDEX idx_company_address_id_company TO IDX_2D1C75569122A03F');
        $this->addSql('ALTER TABLE company_address RENAME INDEX idx_company_address_pays_id_country TO IDX_2D1C75568DEE6016');
        $this->addSql('ALTER TABLE company_address RENAME INDEX idx_company_address_id_type TO IDX_2D1C75567FE4B2B');
        $this->addSql('ALTER TABLE wallet DROP FOREIGN KEY wallet_id_client_fk');
        $this->addSql('ALTER TABLE wallet DROP FOREIGN KEY wallet_id_type_fk');
        $this->addSql('ALTER TABLE wallet RENAME INDEX unq_wire_transfer_pattern TO UNIQ_7C68921FA4FA2043');
        $this->addSql('ALTER TABLE wallet RENAME INDEX fk_id_type_idx TO IDX_7C68921F7FE4B2B');
        $this->addSql('ALTER TABLE wallet RENAME INDEX idx_id_client TO IDX_7C68921FE173B1B8');
        $this->addSql('ALTER TABLE project_abandon_reason CHANGE status status TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE project_abandon_reason RENAME INDEX label TO UNIQ_37743971EA750E8');
        $this->addSql('ALTER TABLE client_data_history DROP FOREIGN KEY fk_client_data_history_id_client');
        $this->addSql('ALTER TABLE client_data_history DROP FOREIGN KEY fk_client_data_history_id_user');
        $this->addSql('ALTER TABLE client_data_history CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE autobid DROP FOREIGN KEY fk_autobid_id_lender');
        $this->addSql('ALTER TABLE autobid CHANGE status status SMALLINT NOT NULL, CHANGE rate_min rate_min NUMERIC(3, 1) NOT NULL');
        $this->addSql('ALTER TABLE sponsorship DROP FOREIGN KEY fk_sponsorship_id_campaign');
        $this->addSql('ALTER TABLE sponsorship DROP FOREIGN KEY fk_sponsorship_id_client_sponsee');
        $this->addSql('ALTER TABLE sponsorship DROP FOREIGN KEY fk_sponsorship_id_client_sponsor');
        $this->addSql('ALTER TABLE sponsorship CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_charge_type CHANGE id id SMALLINT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE accepted_bids DROP FOREIGN KEY fk_accepted_bids_id_bid');
        $this->addSql('ALTER TABLE accepted_bids CHANGE amount amount INT NOT NULL');
        $this->addSql('ALTER TABLE project_eligibility_rule_set_member DROP FOREIGN KEY fk_project_eligibility_rule_set_member_id_rule');
        $this->addSql('ALTER TABLE project_eligibility_rule_set_member DROP FOREIGN KEY fk_project_eligibility_rule_set_member_id_rule_set');
        $this->addSql('ALTER TABLE project_eligibility_rule_set_member CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_rule_set id_rule_set INT NOT NULL, CHANGE id_rule id_rule INT NOT NULL');
        $this->addSql('ALTER TABLE login_connection_admin CHANGE id_user id_user INT NOT NULL');
        $this->addSql('ALTER TABLE compteur_transferts CHANGE type type SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_need CHANGE `rank` `rank` SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE projects DROP FOREIGN KEY fk_projects_partner_id_partner');
        $this->addSql('ALTER TABLE projects DROP FOREIGN KEY fk_project_id_company');
        $this->addSql('ALTER TABLE projects DROP FOREIGN KEY projects_ibfk_1');
        $this->addSql('DROP INDEX id_prescripteur ON projects');
        $this->addSql('ALTER TABLE projects DROP id_prescripteur, CHANGE status status SMALLINT NOT NULL, CHANGE id_partner id_partner INT NOT NULL, CHANGE amount amount INT DEFAULT NULL, CHANGE period period SMALLINT DEFAULT NULL, CHANGE id_borrowing_motive id_borrowing_motive SMALLINT DEFAULT NULL, CHANGE comments comments MEDIUMTEXT DEFAULT NULL, CHANGE objectif_loan objectif_loan MEDIUMTEXT DEFAULT NULL, CHANGE means_repayment means_repayment MEDIUMTEXT DEFAULT NULL, CHANGE balance_count balance_count INT DEFAULT NULL, CHANGE create_bo create_bo TINYINT(1) NOT NULL, CHANGE remb_auto remb_auto SMALLINT DEFAULT NULL, CHANGE display display SMALLINT DEFAULT NULL, CHANGE id_product id_product INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_5C93B3A4B9B10D22 ON projects (id_target_company)');
        $this->addSql('CREATE INDEX IDX_5C93B3A45B50F2E8 ON projects (id_analyste)');
        $this->addSql('ALTER TABLE projects RENAME INDEX fk_projects_partner_id_partner TO IDX_5C93B3A4EFB69766');
        $this->addSql('ALTER TABLE projects RENAME INDEX status TO fk_projects_status');
        $this->addSql('ALTER TABLE templates CHANGE name name VARCHAR(191) NOT NULL, CHANGE slug slug VARCHAR(191) NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE compteur_factures DROP FOREIGN KEY fk_compteur_factures_id_project');
        $this->addSql('ALTER TABLE compteur_factures RENAME INDEX idx_compteur_factures_id_project TO IDX_739F3DFBF12E799E');
        $this->addSql('ALTER TABLE ifu CHANGE statut statut TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE greenpoint_attachment DROP FOREIGN KEY greenpoint_attachment_ibfk_1');
        $this->addSql('ALTER TABLE greenpoint_attachment RENAME INDEX id_attachment TO UNIQ_63A1A6A3DCD5596C');
        $this->addSql('ALTER TABLE project_eligibility_assessment CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_rule id_rule INT NOT NULL, CHANGE id_rule_set id_rule_set INT NOT NULL');
        $this->addSql('ALTER TABLE product CHANGE id_product id_product INT AUTO_INCREMENT NOT NULL, CHANGE id_repayment_type id_repayment_type SMALLINT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE product RENAME INDEX unq_product_label TO UNIQ_D34A04ADEA750E8');
        $this->addSql('ALTER TABLE product RENAME INDEX idx_product_id_repayment_type TO IDX_D34A04AD2288DC56');
        $this->addSql('ALTER TABLE risk_data_monitoring_call_log DROP FOREIGN KEY fk_risk_data_monitoring_call_log_company_rating_history');
        $this->addSql('ALTER TABLE risk_data_monitoring_call_log DROP FOREIGN KEY fk_risk_data_monitoring_call_log_risk_data_monitoring');
        $this->addSql('ALTER TABLE client_vigilance_status_history DROP FOREIGN KEY client_vigilance_status_history_ibfk_1');
        $this->addSql('ALTER TABLE client_vigilance_status_history DROP FOREIGN KEY client_vigilance_status_history_ibfk_2');
        $this->addSql('ALTER TABLE client_vigilance_status_history CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_atypical_operation id_atypical_operation INT DEFAULT NULL, CHANGE vigilance_status vigilance_status SMALLINT NOT NULL');
        $this->addSql('CREATE INDEX IDX_55E5315A6B3CA4B ON client_vigilance_status_history (id_user)');
        $this->addSql('ALTER TABLE project_cgv DROP FOREIGN KEY fk_project_cgv_id_project');
        $this->addSql('ALTER TABLE project_cgv CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE close_out_netting_email_extra_content DROP FOREIGN KEY fk_close_out_netting_email_extra_content_id_project');
        $this->addSql('ALTER TABLE close_out_netting_email_extra_content CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE close_out_netting_email_extra_content RENAME INDEX unq_close_out_netting_email_extra_content_id_project TO UNIQ_EE8E4CCEF12E799E');
        $this->addSql('ALTER TABLE lender_statistic_queue DROP FOREIGN KEY fk_lender_statistic_queue_id_wallet');
        $this->addSql('ALTER TABLE lender_statistic_queue CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE client_setting_type DROP INDEX idx_client_setting_type_label, ADD UNIQUE INDEX UNIQ_FC60D9CEEA750E8 (label)');
        $this->addSql('ALTER TABLE product_attribute_type CHANGE id_type id_type SMALLINT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE user_access CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE partner DROP FOREIGN KEY partner_ibfk_1');
        $this->addSql('ALTER TABLE partner CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE type type SMALLINT NOT NULL, CHANGE logo logo VARCHAR(191) DEFAULT NULL, CHANGE prospect prospect TINYINT(1) DEFAULT \'1\' NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE partner RENAME INDEX fk_partner_id_company TO IDX_312B3E169122A03F');
        $this->addSql('ALTER TABLE partner RENAME INDEX fk_partner_id_user_creation TO IDX_312B3E1694BB011');
        $this->addSql('ALTER TABLE companies_bilans DROP FOREIGN KEY fk_companies_bilans_company_tax_form_type');
        $this->addSql('ALTER TABLE companies_bilans CHANGE duree_exercice_fiscal duree_exercice_fiscal SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE nationalites CHANGE id_nationalite id_nationalite INT AUTO_INCREMENT NOT NULL, CHANGE code_pays code_pays VARCHAR(9) NOT NULL');
        $this->addSql('ALTER TABLE xerfi CHANGE naf naf VARCHAR(5) NOT NULL, CHANGE score score SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE repayment_type CHANGE id_repayment_type id_repayment_type SMALLINT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE testimonial CHANGE status status TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE clients_gestion_notifications CHANGE id_notif id_notif INT NOT NULL');
        $this->addSql('ALTER TABLE underlying_contract CHANGE id_contract id_contract INT AUTO_INCREMENT NOT NULL, CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE underlying_contract RENAME INDEX unq_underlying_contract_label TO UNIQ_B1E89106EA750E8');
        $this->addSql('ALTER TABLE lender_questionnaire CHANGE id_lender_questionnaire id_lender_questionnaire INT AUTO_INCREMENT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE blocs CHANGE name name VARCHAR(191) NOT NULL, CHANGE slug slug VARCHAR(191) NOT NULL, CHANGE status status TINYINT(1) NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE beneficial_owner_type RENAME INDEX label TO UNIQ_930DC213EA750E8');
        $this->addSql('ALTER TABLE ws_call_history CHANGE transfer_time transfer_time NUMERIC(6, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE ws_call_history RENAME INDEX id_resource TO IDX_7BB08D9AEC4A1883');
        $this->addSql('ALTER TABLE transfer DROP FOREIGN KEY fk_transfer_id_client_origin');
        $this->addSql('ALTER TABLE transfer DROP FOREIGN KEY fk_transfer_id_client_receiver');
        $this->addSql('ALTER TABLE transfer DROP FOREIGN KEY fk_transfer_id_transfer_type');
        $this->addSql('ALTER TABLE transfer CHANGE id_transfer_type id_transfer_type SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE underlying_contract_attribute DROP FOREIGN KEY fk_underlying_contract_attribute_id_contract');
        $this->addSql('ALTER TABLE underlying_contract_attribute DROP FOREIGN KEY fk_underlying_contract_attribute_id_type');
        $this->addSql('ALTER TABLE underlying_contract_attribute CHANGE id_attribute id_attribute INT AUTO_INCREMENT NOT NULL, CHANGE id_contract id_contract INT NOT NULL, CHANGE id_type id_type SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE lender_evaluation DROP FOREIGN KEY fk_lender_evaluation_id_lender');
        $this->addSql('ALTER TABLE lender_evaluation CHANGE id_lender_evaluation id_lender_evaluation INT AUTO_INCREMENT NOT NULL, CHANGE id_lender_questionnaire id_lender_questionnaire INT NOT NULL');
        $this->addSql('ALTER TABLE greenpoint_attachment_detail DROP FOREIGN KEY greenpoint_attachment_detail_ibfk_1');
        $this->addSql('ALTER TABLE greenpoint_attachment_detail CHANGE identity_civility identity_civility VARCHAR(1) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AE74DDBB21631A3 ON greenpoint_attachment_detail (id_greenpoint_attachment)');
        $this->addSql('ALTER TABLE projects_status_history DROP FOREIGN KEY fk_projects_status_history_id_project_status');
        $this->addSql('ALTER TABLE projects_status_history CHANGE id_user id_user INT NOT NULL, CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE company_client RENAME INDEX fk_company_client_id_company TO IDX_FADB60209122A03F');
        $this->addSql('ALTER TABLE company_client RENAME INDEX unq_company_client_id_client TO UNIQ_FADB6020E173B1B8');
        $this->addSql('ALTER TABLE project_attachment_type_category CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE `rank` `rank` SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE loans DROP FOREIGN KEY fk_loans_id_lender');
        $this->addSql('ALTER TABLE loans DROP FOREIGN KEY FK_loan_id_contract_type_underlying_contract_id');
        $this->addSql('ALTER TABLE loans DROP FOREIGN KEY fk_loan_id_project');
        $this->addSql('ALTER TABLE loans CHANGE id_type_contract id_type_contract INT NOT NULL, CHANGE amount amount INT NOT NULL, CHANGE rate rate NUMERIC(3, 1) NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('CREATE INDEX IDX_82C24DBCC0B7B270 ON loans (id_acceptation_legal_doc)');
        $this->addSql('ALTER TABLE loans RENAME INDEX idx_id_transfer TO IDX_82C24DBC10EF4F55');
        $this->addSql('ALTER TABLE insee_pays CHANGE CODEISO2 CODEISO2 VARCHAR(2) NOT NULL');
        $this->addSql('ALTER TABLE mail_queue CHANGE attachments attachments TEXT NOT NULL, CHANGE id_message_mailjet id_message_mailjet BIGINT DEFAULT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE mail_queue RENAME INDEX id_mail_template TO IDX_4B3EDD0CF49F0FAE');
        $this->addSql('ALTER TABLE blocs_elements CHANGE id_bloc id_bloc INT NOT NULL, CHANGE id_element id_element INT NOT NULL, CHANGE value value MEDIUMTEXT NOT NULL, CHANGE status status INT NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE project_charge DROP FOREIGN KEY fk_project_charge_id_mission');
        $this->addSql('ALTER TABLE project_charge DROP FOREIGN KEY fk_project_charge_id_project');
        $this->addSql('ALTER TABLE project_charge DROP FOREIGN KEY fk_project_charge_id_type');
        $this->addSql('ALTER TABLE project_charge DROP FOREIGN KEY fk_project_charge_id_wire_transfer_in');
        $this->addSql('ALTER TABLE project_charge CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_mission id_mission INT DEFAULT NULL, CHANGE id_type id_type SMALLINT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_charge RENAME INDEX idx_project_charge_id_wire_transfer_in TO IDX_42CF4F7E97F2CCE1');
        $this->addSql('ALTER TABLE partner_third_party DROP FOREIGN KEY fk_partner_third_party_id_company');
        $this->addSql('ALTER TABLE partner_third_party DROP FOREIGN KEY fk_partner_third_party_id_partner');
        $this->addSql('ALTER TABLE partner_third_party DROP FOREIGN KEY fk_partner_third_party_id_type');
        $this->addSql('ALTER TABLE partner_third_party CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_type id_type INT NOT NULL, CHANGE id_partner id_partner INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX unq_partner_third_party_company_partner ON partner_third_party (id_company, id_partner)');
        $this->addSql('ALTER TABLE partner_third_party RENAME INDEX idx_partner_third_party_id_type TO IDX_7D1CA86C7FE4B2B');
        $this->addSql('ALTER TABLE partner_third_party RENAME INDEX idx_partner_third_party_id_partner TO IDX_7D1CA86CEFB69766');
        $this->addSql('ALTER TABLE partner_third_party RENAME INDEX idx_partner_third_party_id_company TO IDX_7D1CA86C9122A03F');
        $this->addSql('ALTER TABLE vigilance_rule CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE vigilance_status vigilance_status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE menus CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE lender_panel_preference DROP FOREIGN KEY fk_lender_panel_preference_id_lender');
        $this->addSql('ALTER TABLE lender_panel_preference CHANGE page_name page_name VARCHAR(64) NOT NULL, CHANGE panel_name panel_name VARCHAR(64) NOT NULL, CHANGE panel_order panel_order SMALLINT NOT NULL, CHANGE hidden hidden TINYINT(1) NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE echeanciers DROP FOREIGN KEY fk_echeanciers_id_lender');
        $this->addSql('ALTER TABLE echeanciers DROP FOREIGN KEY fk_echeanciers_id_loan');
        $this->addSql('ALTER TABLE echeanciers CHANGE montant montant INT NOT NULL, CHANGE capital capital INT NOT NULL, CHANGE interets interets INT NOT NULL, CHANGE capital_rembourse capital_rembourse INT NOT NULL, CHANGE interets_rembourses interets_rembourses INT NOT NULL, CHANGE status status SMALLINT NOT NULL, CHANGE status_emprunteur status_emprunteur SMALLINT NOT NULL, CHANGE status_ra status_ra SMALLINT NOT NULL');
        $this->addSql('CREATE INDEX idx_echeanciers_status_emprunteur ON echeanciers (status_emprunteur)');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX id_loan TO IDX_12FE17D04EF31101');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX id_lender TO IDX_12FE17D08BB74F6C');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX id_project TO idx_echeanciers_id_project');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX date_echeance_reel TO idx_echeanciers_date_echeance_reel');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX date_echeance_emprunteur_reel TO idx_echeanciers_date_echeance_emprunteur_reel');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX ordre TO idx_echeanciers_ordre');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX status_status_email_remb TO idx_echeanciers_status');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX date_echeance_emprunteur TO idx_echeanciers_date_echeance_emprunteur');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX status_ra TO idx_echeanciers_status_ra');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX added TO idx_echeanciers_added');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX date_echeance TO idx_echeanciers_date_echeance');
        $this->addSql('ALTER TABLE echeanciers RENAME INDEX id_project_ordre TO idx_echeanciers_id_project_ordre');
        $this->addSql('ALTER TABLE risk_data_monitoring_assessment DROP FOREIGN KEY fk_risk_data_monitoring_assess_risk_data_monitoring_call_log');
        $this->addSql('ALTER TABLE risk_data_monitoring_assessment DROP FOREIGN KEY fk_risk_data_monitoring_assess_risk_data_monitoring_type');
        $this->addSql('ALTER TABLE risk_data_monitoring_assessment CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_risk_data_monitoring_type id_risk_data_monitoring_type INT NOT NULL');
        $this->addSql('CREATE INDEX IDX_75D59A8AC6235B3D ON risk_data_monitoring_assessment (id_project_eligibility_rule_set)');
        $this->addSql('UPDATE users SET password_edited = NOW() WHERE password_edited = \'0000-00-00 00:00:00\'');
        $this->addSql('UPDATE users SET lastlogin = NOW() WHERE lastlogin = \'0000-00-00 00:00:00\'');
        $this->addSql('ALTER TABLE users CHANGE id_user_type id_user_type INT DEFAULT NULL, CHANGE firstname firstname VARCHAR(191) NOT NULL, CHANGE name name VARCHAR(191) NOT NULL, CHANGE phone phone VARCHAR(50) NOT NULL, CHANGE mobile mobile VARCHAR(50) NOT NULL, CHANGE email email VARCHAR(191) NOT NULL, CHANGE password password VARCHAR(191) NOT NULL, CHANGE password_edited password_edited DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE status status INT NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE lastlogin lastlogin DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE users RENAME INDEX id_user_type TO IDX_1483A5E9766AA7C7');
        $this->addSql('ALTER TABLE debt_collection_mission DROP FOREIGN KEY fk_dc_mission_id_client');
        $this->addSql('ALTER TABLE debt_collection_mission DROP FOREIGN KEY fk_dc_mission_id_project');
        $this->addSql('ALTER TABLE debt_collection_mission DROP FOREIGN KEY fk_dc_mission_id_user_archiving');
        $this->addSql('ALTER TABLE debt_collection_mission DROP FOREIGN KEY fk_dc_mission_id_user_creation');
        $this->addSql('ALTER TABLE debt_collection_mission CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE type type SMALLINT NOT NULL, CHANGE capital capital NUMERIC(11, 2) NOT NULL, CHANGE interest interest NUMERIC(11, 2) NOT NULL, CHANGE commission_vat_incl commission_vat_incl NUMERIC(11, 2) NOT NULL');
        $this->addSql('ALTER TABLE project_rate_settings DROP FOREIGN KEY project_rate_settings_project_period_id_period');
        $this->addSql('ALTER TABLE project_rate_settings CHANGE status status SMALLINT NOT NULL, CHANGE rate_min rate_min NUMERIC(3, 1) NOT NULL, CHANGE rate_max rate_max NUMERIC(3, 1) NOT NULL');
        $this->addSql('ALTER TABLE sponsorship_blacklist DROP FOREIGN KEY fk_sponsorship_blacklist_id_client');
        $this->addSql('ALTER TABLE sponsorship_blacklist DROP FOREIGN KEY fk_sponsorship_blacklist_id_user');
        $this->addSql('CREATE INDEX IDX_3999A5E04FCEFE48 ON sponsorship_blacklist (id_campaign)');
        $this->addSql('ALTER TABLE pre_scoring CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE note note INT NOT NULL');
        $this->addSql('ALTER TABLE clients_gestion_mails_notif CHANGE id_notif id_notif INT NOT NULL, CHANGE date_notif date_notif DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE clients_gestion_mails_notif RENAME INDEX idx_id_wallet_balance_history TO IDX_28F81C603B3FD12B');
        $this->addSql('ALTER TABLE lenders_imposition_history DROP FOREIGN KEY fk_lenders_imposition_history_id_lender');
        $this->addSql('ALTER TABLE lenders_imposition_history CHANGE resident_etranger resident_etranger TINYINT(1) NOT NULL, CHANGE id_pays id_pays INT NOT NULL');
        $this->addSql('ALTER TABLE users_zones CHANGE id_user id_user INT NOT NULL, CHANGE id_zone id_zone INT NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE users_zones RENAME INDEX id_zone TO IDX_62BD15212BCBDC05');
        $this->addSql('ALTER TABLE partner_third_party_type CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE clients_mandats DROP FOREIGN KEY fk_clients_manda_id_client');
        $this->addSql('ALTER TABLE clients_mandats DROP FOREIGN KEY fk_clients_manda_id_projects');
        $this->addSql('ALTER TABLE clients_mandats CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE lender_evaluation_answer CHANGE id_lender_evaluation_answer id_lender_evaluation_answer INT AUTO_INCREMENT NOT NULL, CHANGE id_lender_questionnaire_question id_lender_questionnaire_question INT NOT NULL, CHANGE id_lender_evaluation id_lender_evaluation INT NOT NULL, CHANGE status status SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE tree_menu CHANGE ordre ordre INT DEFAULT 0 NOT NULL, CHANGE status status TINYINT(1) NOT NULL, CHANGE added added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE projects_pouvoir DROP FOREIGN KEY fk_projects_pouvoir_id_project');
        $this->addSql('ALTER TABLE projects_pouvoir CHANGE status status SMALLINT NOT NULL, CHANGE status_remb status_remb SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE project_eligibility_rule CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE transfer_type CHANGE id_type id_type SMALLINT AUTO_INCREMENT NOT NULL');
        $this->addSql('DROP TABLE project_repayment_task');
        $this->addSql('CREATE TABLE project_repayment_task (id INT AUTO_INCREMENT NOT NULL, id_user_validation INT DEFAULT NULL, id_wire_transfer_in INT DEFAULT NULL, id_user_suspending INT DEFAULT NULL, id_user_creation INT DEFAULT NULL, id_user_cancellation INT DEFAULT NULL, id_project INT NOT NULL, id_debt_collection_mission INT DEFAULT NULL, capital NUMERIC(12, 2) NOT NULL, interest NUMERIC(12, 2) NOT NULL, commission_unilend NUMERIC(10, 2) NOT NULL, sequence INT DEFAULT NULL, type SMALLINT NOT NULL, status SMALLINT NOT NULL, repay_at DATE NOT NULL, added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', updated DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', INDEX idx_project_repayment_task_id_project (id_project), INDEX idx_project_repayment_task_id_project_sequence (id_project, sequence), INDEX idx_project_repayment_task_id_wire_transfer_in (id_wire_transfer_in), INDEX idx_project_repayment_task_id_user_suspending (id_user_suspending), INDEX idx_project_repayment_task_id_user_validation (id_user_validation), INDEX idx_project_repayment_task_id_user_creation (id_user_creation), INDEX idx_project_repayment_task_id_user_cancellation (id_user_cancellation), INDEX idx_project_repayment_task_id_debt_collection_mission (id_debt_collection_mission), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE settings RENAME INDEX unq_settings_type TO UNIQ_E545A0C58CDE5729');
        $this->addSql('ALTER TABLE projects_status RENAME INDEX status TO UNIQ_BAF4F9E37B00651C');
        $this->addSql('ALTER TABLE company_status RENAME INDEX label_unique TO UNIQ_469F0169EA750E8');
        $this->addSql('ALTER TABLE clients_status RENAME INDEX unq_client_status_label TO UNIQ_7ED7B1FBEA750E8');
        $this->addSql('ALTER TABLE risk_data_monitoring_type RENAME INDEX unq_company_rating TO UNIQ_CEBACC61E5164257');
        $this->addSql('ALTER TABLE underlying_contract_attribute_type RENAME INDEX unq_underlying_contract_attribute_type_label TO UNIQ_4AAA718BEA750E8');
        $this->addSql('ALTER TABLE operation_sub_type RENAME INDEX unq_operation_sub_type_label TO UNIQ_4E3EB765EA750E8');
        $this->addSql('ALTER TABLE company_tax_form_type RENAME INDEX unq_company_tax_form_type_label TO UNIQ_48E47B69EA750E8');
        $this->addSql('ALTER TABLE parrainages RENAME INDEX email TO UNIQ_A01CD3A7E7927C74');
        $this->addSql('DROP INDEX index_gp_kyc_id_client ON greenpoint_kyc');
        $this->addSql('ALTER TABLE greenpoint_kyc RENAME INDEX id_client TO UNIQ_981F19F9E173B1B8');
        $this->addSql('ALTER TABLE ws_external_resource RENAME INDEX label TO UNIQ_2E87EF1EA750E8');
        $this->addSql('DROP INDEX idx_date ON detailed_daily_state_balance_history');
        $this->addSql('ALTER TABLE detailed_daily_state_balance_history RENAME INDEX date TO UNIQ_BD23DF2BAA9E377A');
        $this->addSql('ALTER TABLE project_eligibility_rule_set RENAME INDEX unq_project_eligibility_rule_set_label TO UNIQ_FA4F773EEA750E8');
        $this->addSql('ALTER TABLE partner_type RENAME INDEX label TO UNIQ_DCEA6431EA750E8');
        $this->addSql('ALTER TABLE wallet_type RENAME INDEX label_unique TO UNIQ_E14CA22CEA750E8');
        $this->addSql('ALTER TABLE project_charge_type RENAME INDEX label_unique TO UNIQ_CD2CD0DEA750E8');
        $this->addSql('ALTER TABLE project_cgv RENAME INDEX id_project TO UNIQ_B4715FE1F12E799E');
        $this->addSql('ALTER TABLE lender_statistic_queue RENAME INDEX id_wallet TO UNIQ_1A9CC0815A5F27F2');
        $this->addSql('ALTER TABLE product_attribute_type RENAME INDEX unq_attribute_type_label TO UNIQ_845F8D8DEA750E8');
        $this->addSql('ALTER TABLE partner RENAME INDEX label TO UNIQ_312B3E16EA750E8');
        $this->addSql('ALTER TABLE partner RENAME INDEX fk_partner_partner_type_type TO IDX_312B3E168CDE5729');
        $this->addSql('ALTER TABLE nationalites RENAME INDEX code_pays TO UNIQ_ADF626E1274566F');
        $this->addSql('ALTER TABLE repayment_type RENAME INDEX unq_repayment_label TO UNIQ_1FEE6150EA750E8');
        $this->addSql('ALTER TABLE project_attachment_type_category RENAME INDEX unq_project_attachment_type_category_label TO UNIQ_72F02865EA750E8');
        $this->addSql('ALTER TABLE operation_type RENAME INDEX label_unique TO UNIQ_A3AE0AB8EA750E8');
        $this->addSql('ALTER TABLE vigilance_rule RENAME INDEX label TO UNIQ_47395C73EA750E8');
        $this->addSql('ALTER TABLE users RENAME INDEX email TO UNIQ_1483A5E9E7927C74');
        $this->addSql('ALTER TABLE partner_third_party_type RENAME INDEX unq_partner_third_party_type_label TO UNIQ_8A4BD13BEA750E8');
        $this->addSql('ALTER TABLE project_eligibility_rule RENAME INDEX unq_project_eligibility_rule_label TO UNIQ_487184C4EA750E8');
        $this->addSql('SET FOREIGN_KEY_CHECKS=1');
        $this->addSql('ALTER TABLE user_agent ADD CONSTRAINT FK_C44967C5E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE risk_data_monitoring_type ADD CONSTRAINT FK_CEBACC612374BEE7 FOREIGN KEY (id_project_eligibility_rule) REFERENCES project_eligibility_rule (id)');
        $this->addSql('ALTER TABLE virements ADD CONSTRAINT FK_24968419E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE virements ADD CONSTRAINT FK_24968419F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE virements ADD CONSTRAINT FK_2496841970634B78 FOREIGN KEY (id_bank_account) REFERENCES bank_account (id)');
        $this->addSql('ALTER TABLE virements ADD CONSTRAINT FK_24968419405BE4E7 FOREIGN KEY (id_user_request) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE virements ADD CONSTRAINT FK_2496841958955E0A FOREIGN KEY (id_user_validation) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE receptions ADD CONSTRAINT FK_B08F24D79D00E13 FOREIGN KEY (rejection_iso_code) REFERENCES sepa_rejection_reason (iso_code)');
        $this->addSql('ALTER TABLE receptions ADD CONSTRAINT FK_B08F24D7E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE receptions ADD CONSTRAINT FK_B08F24D7F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE receptions ADD CONSTRAINT FK_B08F24D76B3CA4B FOREIGN KEY (id_user) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE receptions ADD CONSTRAINT FK_B08F24D7ADB6538E FOREIGN KEY (id_reception_rejected) REFERENCES receptions (id_reception)');
        $this->addSql('ALTER TABLE project_product_assessment ADD CONSTRAINT FK_D2679C3AF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE project_product_assessment ADD CONSTRAINT FK_D2679C3ADD7ADDD FOREIGN KEY (id_product) REFERENCES product (id_product)');
        $this->addSql('ALTER TABLE project_product_assessment ADD CONSTRAINT FK_D2679C3A848E3A1A FOREIGN KEY (id_product_attribute_type) REFERENCES product_attribute_type (id_type)');
        $this->addSql('ALTER TABLE project_repayment_task ADD CONSTRAINT FK_28F9D9FE58955E0A FOREIGN KEY (id_user_validation) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE project_repayment_task ADD CONSTRAINT FK_28F9D9FE97F2CCE1 FOREIGN KEY (id_wire_transfer_in) REFERENCES receptions (id_reception)');
        $this->addSql('ALTER TABLE project_repayment_task ADD CONSTRAINT FK_28F9D9FE619FE6A7 FOREIGN KEY (id_user_suspending) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE project_repayment_task ADD CONSTRAINT FK_28F9D9FE94BB011 FOREIGN KEY (id_user_creation) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE project_repayment_task ADD CONSTRAINT FK_28F9D9FE8A354919 FOREIGN KEY (id_user_cancellation) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE project_repayment_task ADD CONSTRAINT FK_28F9D9FEF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE project_repayment_task ADD CONSTRAINT FK_28F9D9FEAAA7D692 FOREIGN KEY (id_debt_collection_mission) REFERENCES debt_collection_mission (id)');
        $this->addSql('ALTER TABLE bids ADD CONSTRAINT FK_3FF09E1EF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE bids ADD CONSTRAINT FK_3FF09E1EEF7B6696 FOREIGN KEY (id_autobid) REFERENCES autobid (id_autobid)');
        $this->addSql('ALTER TABLE bids ADD CONSTRAINT FK_3FF09E1EFD80A5F3 FOREIGN KEY (id_lender_account) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D38BB74F6C FOREIGN KEY (id_lender) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE product_underlying_contract ADD CONSTRAINT FK_E8A97A94DD7ADDD FOREIGN KEY (id_product) REFERENCES product (id_product)');
        $this->addSql('ALTER TABLE product_underlying_contract ADD CONSTRAINT FK_E8A97A94B954C4CC FOREIGN KEY (id_contract) REFERENCES underlying_contract (id_contract)');
        $this->addSql('ALTER TABLE clients_status_history ADD CONSTRAINT FK_3E28AF07E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE clients_status_history ADD CONSTRAINT FK_3E28AF075D37D0F1 FOREIGN KEY (id_status) REFERENCES clients_status (id)');
        $this->addSql('ALTER TABLE clients_status_history ADD CONSTRAINT FK_3E28AF076B3CA4B FOREIGN KEY (id_user) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE echeanciers_emprunteur ADD CONSTRAINT FK_5CECCBD2F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE project_status_history_reason ADD CONSTRAINT FK_2E30362FE3A5B0D5 FOREIGN KEY (id_abandon_reason) REFERENCES project_abandon_reason (id_abandon)');
        $this->addSql('ALTER TABLE project_status_history_reason ADD CONSTRAINT FK_2E30362FC60C84FB FOREIGN KEY (id_project_status_history) REFERENCES projects_status_history (id_project_status_history)');
        $this->addSql('ALTER TABLE project_status_history_reason ADD CONSTRAINT FK_2E30362F4EE1B357 FOREIGN KEY (id_rejection_reason) REFERENCES project_rejection_reason (id_rejection)');
        $this->addSql('ALTER TABLE clients_adresses ADD CONSTRAINT FK_7F985363E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE operation_sub_type ADD CONSTRAINT FK_4E3EB7651BB9D5A2 FOREIGN KEY (id_parent) REFERENCES operation_type (id)');
        $this->addSql('ALTER TABLE clients_history_actions ADD CONSTRAINT FK_C386E5B9E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A4FCC0FB9 FOREIGN KEY (id_client_owner) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A5D37D0F1 FOREIGN KEY (id_status) REFERENCES company_status (id)');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A91C00F FOREIGN KEY (id_parent_company) REFERENCES companies (id_company)');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3AD3D3C6F1 FOREIGN KEY (id_address) REFERENCES company_address (id)');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3AAA4846F1 FOREIGN KEY (id_postal_address) REFERENCES company_address (id)');
        $this->addSql('ALTER TABLE lender_tax_exemption ADD CONSTRAINT FK_17B0DAB06B3CA4B FOREIGN KEY (id_user) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE lender_tax_exemption ADD CONSTRAINT FK_17B0DAB08BB74F6C FOREIGN KEY (id_lender) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE debt_collection_fee_detail ADD CONSTRAINT FK_3A1AA78B97F2CCE1 FOREIGN KEY (id_wire_transfer_in) REFERENCES receptions (id_reception)');
        $this->addSql('ALTER TABLE debt_collection_fee_detail ADD CONSTRAINT FK_3A1AA78BE344C28F FOREIGN KEY (id_wallet_debtor) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE debt_collection_fee_detail ADD CONSTRAINT FK_3A1AA78B20799ED6 FOREIGN KEY (id_wallet_creditor) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE debt_collection_fee_detail ADD CONSTRAINT FK_3A1AA78B4EF31101 FOREIGN KEY (id_loan) REFERENCES loans (id_loan)');
        $this->addSql('ALTER TABLE debt_collection_fee_detail ADD CONSTRAINT FK_3A1AA78BAAA7D692 FOREIGN KEY (id_debt_collection_mission) REFERENCES debt_collection_mission (id)');
        $this->addSql('ALTER TABLE client_address ADD CONSTRAINT FK_5F732BFC8DEE6016 FOREIGN KEY (id_country) REFERENCES pays (id_pays)');
        $this->addSql('ALTER TABLE client_address ADD CONSTRAINT FK_5F732BFCE173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE client_address ADD CONSTRAINT FK_5F732BFC7FE4B2B FOREIGN KEY (id_type) REFERENCES address_type (id)');
        $this->addSql('ALTER TABLE wallet_balance_history ADD CONSTRAINT FK_3BEE66BC5A5F27F2 FOREIGN KEY (id_wallet) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE wallet_balance_history ADD CONSTRAINT FK_3BEE66BC99B41A4A FOREIGN KEY (id_operation) REFERENCES operation (id)');
        $this->addSql('ALTER TABLE wallet_balance_history ADD CONSTRAINT FK_3BEE66BCD4565BA9 FOREIGN KEY (id_bid) REFERENCES bids (id_bid)');
        $this->addSql('ALTER TABLE wallet_balance_history ADD CONSTRAINT FK_3BEE66BC4EF31101 FOREIGN KEY (id_loan) REFERENCES loans (id_loan)');
        $this->addSql('ALTER TABLE wallet_balance_history ADD CONSTRAINT FK_3BEE66BCF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE wallet_balance_history ADD CONSTRAINT FK_3BEE66BCEF7B6696 FOREIGN KEY (id_autobid) REFERENCES autobid (id_autobid)');
        $this->addSql('ALTER TABLE close_out_netting_repayment ADD CONSTRAINT FK_4F44B2AB4EF31101 FOREIGN KEY (id_loan) REFERENCES loans (id_loan)');
        $this->addSql('ALTER TABLE partner_product ADD CONSTRAINT FK_14A067B0DD7ADDD FOREIGN KEY (id_product) REFERENCES product (id_product)');
        $this->addSql('ALTER TABLE partner_product ADD CONSTRAINT FK_14A067B0EFB69766 FOREIGN KEY (id_partner) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE client_address_attachment ADD CONSTRAINT FK_6B583A35621596FA FOREIGN KEY (id_client_address) REFERENCES client_address (id)');
        $this->addSql('ALTER TABLE client_address_attachment ADD CONSTRAINT FK_6B583A35DCD5596C FOREIGN KEY (id_attachment) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE partner_project_attachment ADD CONSTRAINT FK_E130D16D9DF3809E FOREIGN KEY (id_attachment_type) REFERENCES attachment_type (id)');
        $this->addSql('ALTER TABLE partner_project_attachment ADD CONSTRAINT FK_E130D16DEFB69766 FOREIGN KEY (id_partner) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE company_balance ADD CONSTRAINT FK_8CA60529BD3BD35C FOREIGN KEY (id_balance_type) REFERENCES company_balance_type (id_balance_type)');
        $this->addSql('ALTER TABLE company_balance_type ADD CONSTRAINT FK_60376CE09953EC69 FOREIGN KEY (id_company_tax_form_type) REFERENCES company_tax_form_type (id_type)');
        $this->addSql('ALTER TABLE company_status_history ADD CONSTRAINT FK_1A2286D9122A03F FOREIGN KEY (id_company) REFERENCES companies (id_company)');
        $this->addSql('ALTER TABLE company_status_history ADD CONSTRAINT FK_1A2286D5D37D0F1 FOREIGN KEY (id_status) REFERENCES company_status (id)');
        $this->addSql('ALTER TABLE company_status_history ADD CONSTRAINT FK_1A2286D6B3CA4B FOREIGN KEY (id_user) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE project_beneficial_owner_universign ADD CONSTRAINT FK_4FAA441F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE project_beneficial_owner_universign ADD CONSTRAINT FK_4FAA44162B11735 FOREIGN KEY (id_declaration) REFERENCES company_beneficial_owner_declaration (id)');
        $this->addSql('ALTER TABLE transfer_attachment ADD CONSTRAINT FK_A392E75210EF4F55 FOREIGN KEY (id_transfer) REFERENCES transfer (id_transfer)');
        $this->addSql('ALTER TABLE transfer_attachment ADD CONSTRAINT FK_A392E752DCD5596C FOREIGN KEY (id_attachment) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE bank_account ADD CONSTRAINT FK_53A23E0AE173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE bank_account ADD CONSTRAINT FK_53A23E0ADCD5596C FOREIGN KEY (id_attachment) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DA5A21FF3 FOREIGN KEY (id_welcome_offer) REFERENCES offres_bienvenues_details (id_offre_bienvenue_detail)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DE344C28F FOREIGN KEY (id_wallet_debtor) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D97F2CCE1 FOREIGN KEY (id_wire_transfer_in) REFERENCES receptions (id_reception)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DFF4BCDA2 FOREIGN KEY (id_wire_transfer_out) REFERENCES virements (id_virement)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D7FE4B2B FOREIGN KEY (id_type) REFERENCES operation_type (id)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DFB93247D FOREIGN KEY (id_sub_type) REFERENCES operation_sub_type (id)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D20799ED6 FOREIGN KEY (id_wallet_creditor) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D10EF4F55 FOREIGN KEY (id_transfer) REFERENCES transfer (id_transfer)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DF9740642 FOREIGN KEY (id_payment_schedule) REFERENCES echeanciers_emprunteur (id_echeancier_emprunteur)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D598B216D FOREIGN KEY (id_repayment_schedule) REFERENCES echeanciers (id_echeancier)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D4EF31101 FOREIGN KEY (id_loan) REFERENCES loans (id_loan)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D8635D8A0 FOREIGN KEY (id_backpayline) REFERENCES backpayline (id_backpayline)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DE30EA0D4 FOREIGN KEY (id_repayment_task_log) REFERENCES project_repayment_task_log (id)');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DD8E3C123 FOREIGN KEY (id_sponsorship) REFERENCES sponsorship (id)');
        $this->addSql('ALTER TABLE temporary_links_login ADD CONSTRAINT FK_A6F42CE8E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE greenpoint_kyc ADD CONSTRAINT FK_981F19F9E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE prelevements ADD CONSTRAINT FK_968E0A99E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE prelevements ADD CONSTRAINT FK_968E0A99F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE beneficial_owner ADD CONSTRAINT FK_F5526F1362B11735 FOREIGN KEY (id_declaration) REFERENCES company_beneficial_owner_declaration (id)');
        $this->addSql('ALTER TABLE beneficial_owner ADD CONSTRAINT FK_F5526F13E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE beneficial_owner ADD CONSTRAINT FK_F5526F137FE4B2B FOREIGN KEY (id_type) REFERENCES beneficial_owner_type (id)');
        $this->addSql('ALTER TABLE product_attribute ADD CONSTRAINT FK_94DA59767FE4B2B FOREIGN KEY (id_type) REFERENCES product_attribute_type (id_type)');
        $this->addSql('ALTER TABLE product_attribute ADD CONSTRAINT FK_94DA5976DD7ADDD FOREIGN KEY (id_product) REFERENCES product (id_product)');
        $this->addSql('ALTER TABLE product_attribute ADD CONSTRAINT FK_94DA5976CDF8B0CE FOREIGN KEY (id_rule) REFERENCES project_eligibility_rule (id)');
        $this->addSql('ALTER TABLE close_out_netting_payment ADD CONSTRAINT FK_5EB1A212F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB7FE4B2B FOREIGN KEY (id_type) REFERENCES attachment_type (id)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BBE173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE company_beneficial_owner_declaration ADD CONSTRAINT FK_D90EC3709122A03F FOREIGN KEY (id_company) REFERENCES companies (id_company)');
        $this->addSql('ALTER TABLE project_repayment_task_log ADD CONSTRAINT FK_D67EEC1AD95EC727 FOREIGN KEY (id_task) REFERENCES project_repayment_task (id)');
        $this->addSql('ALTER TABLE lender_statistic ADD CONSTRAINT FK_565FFBCE5A5F27F2 FOREIGN KEY (id_wallet) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE project_attachment ADD CONSTRAINT FK_61F9A289F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE project_attachment ADD CONSTRAINT FK_61F9A289DCD5596C FOREIGN KEY (id_attachment) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE project_repayment_detail ADD CONSTRAINT FK_A2C478EC4EF31101 FOREIGN KEY (id_loan) REFERENCES loans (id_loan)');
        $this->addSql('ALTER TABLE project_repayment_detail ADD CONSTRAINT FK_A2C478ECB0667CD7 FOREIGN KEY (id_task_log) REFERENCES project_repayment_task_log (id)');
        $this->addSql('ALTER TABLE project_repayment_detail ADD CONSTRAINT FK_A2C478ECD95EC727 FOREIGN KEY (id_task) REFERENCES project_repayment_task (id)');
        $this->addSql('ALTER TABLE project_repayment_detail ADD CONSTRAINT FK_A2C478EC598B216D FOREIGN KEY (id_repayment_schedule) REFERENCES echeanciers (id_echeancier)');
        $this->addSql('ALTER TABLE bids_logs ADD CONSTRAINT FK_C2FF50DFF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE project_contract_assessment ADD CONSTRAINT FK_D4109F69F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE project_contract_assessment ADD CONSTRAINT FK_D4109F69B954C4CC FOREIGN KEY (id_contract) REFERENCES underlying_contract (id_contract)');
        $this->addSql('ALTER TABLE project_contract_assessment ADD CONSTRAINT FK_D4109F6931D42596 FOREIGN KEY (id_contract_attribute_type) REFERENCES underlying_contract_attribute_type (id_type)');
        $this->addSql('ALTER TABLE acceptations_legal_docs ADD CONSTRAINT FK_F1D2E432E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE clients ADD CONSTRAINT FK_C82E74DF1ED241 FOREIGN KEY (id_client_status_history) REFERENCES clients_status_history (id)');
        $this->addSql('ALTER TABLE clients ADD CONSTRAINT FK_C82E74D3D3C6F1 FOREIGN KEY (id_address) REFERENCES client_address (id)');
        $this->addSql('ALTER TABLE clients ADD CONSTRAINT FK_C82E74AA4846F1 FOREIGN KEY (id_postal_address) REFERENCES client_address (id)');
        $this->addSql('ALTER TABLE clients_history ADD CONSTRAINT FK_19D1D044E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE clients_history ADD CONSTRAINT FK_19D1D04461C3E712 FOREIGN KEY (id_user_agent) REFERENCES user_agent (id)');
        $this->addSql('ALTER TABLE project_attachment_type ADD CONSTRAINT FK_4C9C36E65697F554 FOREIGN KEY (id_category) REFERENCES project_attachment_type_category (id)');
        $this->addSql('ALTER TABLE project_attachment_type ADD CONSTRAINT FK_4C9C36E67FE4B2B FOREIGN KEY (id_type) REFERENCES attachment_type (id)');
        $this->addSql('ALTER TABLE projects_notes ADD CONSTRAINT FK_949AF2B2F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE factures ADD CONSTRAINT FK_647590BF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE debt_collection_mission_payment_schedule ADD CONSTRAINT FK_344E3C47F9740642 FOREIGN KEY (id_payment_schedule) REFERENCES echeanciers_emprunteur (id_echeancier_emprunteur)');
        $this->addSql('ALTER TABLE debt_collection_mission_payment_schedule ADD CONSTRAINT FK_344E3C474EFA5B4C FOREIGN KEY (id_mission) REFERENCES debt_collection_mission (id)');
        $this->addSql('ALTER TABLE backpayline ADD CONSTRAINT FK_9E2715575A5F27F2 FOREIGN KEY (id_wallet) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE wire_transfer_out_universign ADD CONSTRAINT FK_43BD8066FF4BCDA2 FOREIGN KEY (id_wire_transfer_out) REFERENCES virements (id_virement)');
        $this->addSql('ALTER TABLE client_atypical_operation ADD CONSTRAINT FK_D9F9D95C6B3CA4B FOREIGN KEY (id_user) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE client_atypical_operation ADD CONSTRAINT FK_D9F9D95CCDF8B0CE FOREIGN KEY (id_rule) REFERENCES vigilance_rule (id)');
        $this->addSql('ALTER TABLE client_atypical_operation ADD CONSTRAINT FK_D9F9D95CE173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE company_address ADD CONSTRAINT FK_2D1C75569122A03F FOREIGN KEY (id_company) REFERENCES companies (id_company)');
        $this->addSql('ALTER TABLE company_address ADD CONSTRAINT FK_2D1C75568DEE6016 FOREIGN KEY (id_country) REFERENCES pays (id_pays)');
        $this->addSql('ALTER TABLE company_address ADD CONSTRAINT FK_2D1C75567FE4B2B FOREIGN KEY (id_type) REFERENCES address_type (id)');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921F7FE4B2B FOREIGN KEY (id_type) REFERENCES wallet_type (id)');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921FE173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE client_data_history ADD CONSTRAINT FK_F2BB84BBE173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE client_data_history ADD CONSTRAINT FK_F2BB84BB6B3CA4B FOREIGN KEY (id_user) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE autobid ADD CONSTRAINT FK_31E6CFE68BB74F6C FOREIGN KEY (id_lender) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE sponsorship ADD CONSTRAINT FK_C0F10CD44FCEFE48 FOREIGN KEY (id_campaign) REFERENCES sponsorship_campaign (id)');
        $this->addSql('ALTER TABLE sponsorship ADD CONSTRAINT FK_C0F10CD4EED730AF FOREIGN KEY (id_client_sponsor) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE sponsorship ADD CONSTRAINT FK_C0F10CD497EB5DE2 FOREIGN KEY (id_client_sponsee) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE accepted_bids ADD CONSTRAINT FK_4B80AF05D4565BA9 FOREIGN KEY (id_bid) REFERENCES bids (id_bid)');
        $this->addSql('ALTER TABLE accepted_bids ADD CONSTRAINT FK_4B80AF054EF31101 FOREIGN KEY (id_loan) REFERENCES loans (id_loan)');
        $this->addSql('ALTER TABLE project_eligibility_rule_set_member ADD CONSTRAINT FK_54D4C7D6C1038EBB FOREIGN KEY (id_rule_set) REFERENCES project_eligibility_rule_set (id)');
        $this->addSql('ALTER TABLE project_eligibility_rule_set_member ADD CONSTRAINT FK_54D4C7D6CDF8B0CE FOREIGN KEY (id_rule) REFERENCES project_eligibility_rule (id)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A49122A03F FOREIGN KEY (id_company) REFERENCES companies (id_company)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4B9B10D22 FOREIGN KEY (id_target_company) REFERENCES companies (id_company)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A45B50F2E8 FOREIGN KEY (id_analyste) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4D3D97379 FOREIGN KEY (id_commercial) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4EFB69766 FOREIGN KEY (id_partner) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A424FEBA6C FOREIGN KEY (id_company_submitter) REFERENCES companies (id_company)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4EE78DD55 FOREIGN KEY (id_client_submitter) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE compteur_factures ADD CONSTRAINT FK_739F3DFBF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE greenpoint_attachment ADD CONSTRAINT FK_63A1A6A3DCD5596C FOREIGN KEY (id_attachment) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE risk_data_monitoring_call_log ADD CONSTRAINT FK_E0C66DF2B27D4B7F FOREIGN KEY (id_risk_data_monitoring) REFERENCES risk_data_monitoring (id)');
        $this->addSql('ALTER TABLE risk_data_monitoring_call_log ADD CONSTRAINT FK_E0C66DF2EAEF1107 FOREIGN KEY (id_company_rating_history) REFERENCES company_rating_history (id_company_rating_history)');
        $this->addSql('ALTER TABLE client_vigilance_status_history ADD CONSTRAINT FK_55E5315A6B3CA4B FOREIGN KEY (id_user) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE client_vigilance_status_history ADD CONSTRAINT FK_55E5315A304100E3 FOREIGN KEY (id_atypical_operation) REFERENCES client_atypical_operation (id)');
        $this->addSql('ALTER TABLE client_vigilance_status_history ADD CONSTRAINT FK_55E5315AE173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE project_cgv ADD CONSTRAINT FK_B4715FE1F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE close_out_netting_email_extra_content ADD CONSTRAINT FK_EE8E4CCEF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE lender_statistic_queue ADD CONSTRAINT FK_1A9CC0815A5F27F2 FOREIGN KEY (id_wallet) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT FK_312B3E168CDE5729 FOREIGN KEY (type) REFERENCES partner_type (id)');
        $this->addSql('ALTER TABLE companies_bilans ADD CONSTRAINT FK_CDCF3AE39953EC69 FOREIGN KEY (id_company_tax_form_type) REFERENCES company_tax_form_type (id_type)');
        $this->addSql('ALTER TABLE company_rating ADD CONSTRAINT FK_E5164257EAEF1107 FOREIGN KEY (id_company_rating_history) REFERENCES company_rating_history (id_company_rating_history)');
        $this->addSql('ALTER TABLE company_rating_history ADD CONSTRAINT FK_EA3EA6909122A03F FOREIGN KEY (id_company) REFERENCES companies (id_company)');
        $this->addSql('ALTER TABLE transfer ADD CONSTRAINT FK_4034A3C0A03AA2E FOREIGN KEY (id_transfer_type) REFERENCES transfer_type (id_type)');
        $this->addSql('ALTER TABLE transfer ADD CONSTRAINT FK_4034A3C0FA007FDB FOREIGN KEY (id_client_receiver) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE transfer ADD CONSTRAINT FK_4034A3C0357FCCC8 FOREIGN KEY (id_client_origin) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE underlying_contract_attribute ADD CONSTRAINT FK_B121121C7FE4B2B FOREIGN KEY (id_type) REFERENCES underlying_contract_attribute_type (id_type)');
        $this->addSql('ALTER TABLE underlying_contract_attribute ADD CONSTRAINT FK_B121121CB954C4CC FOREIGN KEY (id_contract) REFERENCES underlying_contract (id_contract)');
        $this->addSql('ALTER TABLE lender_evaluation ADD CONSTRAINT FK_967451108BB74F6C FOREIGN KEY (id_lender) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE greenpoint_attachment_detail ADD CONSTRAINT FK_AE74DDBB21631A3 FOREIGN KEY (id_greenpoint_attachment) REFERENCES greenpoint_attachment (id_greenpoint_attachment)');
        $this->addSql('ALTER TABLE projects_status_history ADD CONSTRAINT FK_7B3F870451C23350 FOREIGN KEY (id_project_status) REFERENCES projects_status (id_project_status)');
        $this->addSql('ALTER TABLE loans ADD CONSTRAINT FK_82C24DBC10EF4F55 FOREIGN KEY (id_transfer) REFERENCES loan_transfer (id_loan_transfer)');
        $this->addSql('ALTER TABLE loans ADD CONSTRAINT FK_82C24DBC8BB74F6C FOREIGN KEY (id_lender) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE loans ADD CONSTRAINT FK_82C24DBCF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE loans ADD CONSTRAINT FK_82C24DBC9A58DEC0 FOREIGN KEY (id_type_contract) REFERENCES underlying_contract (id_contract)');
        $this->addSql('ALTER TABLE loans ADD CONSTRAINT FK_82C24DBCC0B7B270 FOREIGN KEY (id_acceptation_legal_doc) REFERENCES acceptations_legal_docs (id_acceptation)');
        $this->addSql('ALTER TABLE project_charge ADD CONSTRAINT FK_42CF4F7E7FE4B2B FOREIGN KEY (id_type) REFERENCES project_charge_type (id)');
        $this->addSql('ALTER TABLE project_charge ADD CONSTRAINT FK_42CF4F7EF12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE project_charge ADD CONSTRAINT FK_42CF4F7E97F2CCE1 FOREIGN KEY (id_wire_transfer_in) REFERENCES receptions (id_reception)');
        $this->addSql('ALTER TABLE project_charge ADD CONSTRAINT FK_42CF4F7E4EFA5B4C FOREIGN KEY (id_mission) REFERENCES debt_collection_mission (id)');
        $this->addSql('ALTER TABLE partner_third_party ADD CONSTRAINT FK_7D1CA86C7FE4B2B FOREIGN KEY (id_type) REFERENCES partner_third_party_type (id)');
        $this->addSql('ALTER TABLE partner_third_party ADD CONSTRAINT FK_7D1CA86CEFB69766 FOREIGN KEY (id_partner) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE partner_third_party ADD CONSTRAINT FK_7D1CA86C9122A03F FOREIGN KEY (id_company) REFERENCES companies (id_company)');
        $this->addSql('ALTER TABLE lender_panel_preference ADD CONSTRAINT FK_B0D683E98BB74F6C FOREIGN KEY (id_lender) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE echeanciers ADD CONSTRAINT FK_12FE17D04EF31101 FOREIGN KEY (id_loan) REFERENCES loans (id_loan)');
        $this->addSql('ALTER TABLE echeanciers ADD CONSTRAINT FK_12FE17D08BB74F6C FOREIGN KEY (id_lender) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE risk_data_monitoring_assessment ADD CONSTRAINT FK_75D59A8AC6235B3D FOREIGN KEY (id_project_eligibility_rule_set) REFERENCES project_eligibility_rule_set (id)');
        $this->addSql('ALTER TABLE risk_data_monitoring_assessment ADD CONSTRAINT FK_75D59A8A79F35064 FOREIGN KEY (id_risk_data_monitoring_call_log) REFERENCES risk_data_monitoring_call_log (id)');
        $this->addSql('ALTER TABLE risk_data_monitoring_assessment ADD CONSTRAINT FK_75D59A8A6CB6B829 FOREIGN KEY (id_risk_data_monitoring_type) REFERENCES risk_data_monitoring_type (id)');
        $this->addSql('ALTER TABLE debt_collection_mission ADD CONSTRAINT FK_C4CC01C2F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE debt_collection_mission ADD CONSTRAINT FK_C4CC01C24D3D2AF6 FOREIGN KEY (id_client_debt_collector) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE debt_collection_mission ADD CONSTRAINT FK_C4CC01C294BB011 FOREIGN KEY (id_user_creation) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE debt_collection_mission ADD CONSTRAINT FK_C4CC01C295C35408 FOREIGN KEY (id_user_archiving) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE project_rate_settings ADD CONSTRAINT FK_E6032762E38FAB23 FOREIGN KEY (id_period) REFERENCES project_period (id_period)');
        $this->addSql('ALTER TABLE sponsorship_blacklist ADD CONSTRAINT FK_3999A5E06B3CA4B FOREIGN KEY (id_user) REFERENCES users (id_user)');
        $this->addSql('ALTER TABLE sponsorship_blacklist ADD CONSTRAINT FK_3999A5E0E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE sponsorship_blacklist ADD CONSTRAINT FK_3999A5E04FCEFE48 FOREIGN KEY (id_campaign) REFERENCES sponsorship_campaign (id)');
        $this->addSql('ALTER TABLE clients_gestion_mails_notif ADD CONSTRAINT FK_28F81C603B3FD12B FOREIGN KEY (id_wallet_balance_history) REFERENCES wallet_balance_history (id)');
        $this->addSql('ALTER TABLE lenders_imposition_history ADD CONSTRAINT FK_EDAE67268BB74F6C FOREIGN KEY (id_lender) REFERENCES wallet (id)');
        $this->addSql('ALTER TABLE clients_mandats ADD CONSTRAINT FK_D3C21AB0E173B1B8 FOREIGN KEY (id_client) REFERENCES clients (id_client)');
        $this->addSql('ALTER TABLE clients_mandats ADD CONSTRAINT FK_D3C21AB0F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE projects_pouvoir ADD CONSTRAINT FK_93BC75D7F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
    }

    public function down(Schema $schema) : void
    {
        // no need
    }
}
