imports:
  - { resource: doctrine_listeners.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  KLS\Syndication\:
    resource: '%kernel.project_dir%/src/Syndication/*'
    exclude: '%kernel.project_dir%/src/Syndication/{Agency,Arrangement}/{Console,Entity,Migrations,Controller,Tests,Traits,Listener/Doctrine}'

  #
  # Arrangement
  #

  KLS\Syndication\Arrangement\Serializer\ContextBuilder\ProjectAddedByContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    autoconfigure: false

  #
  # Agency
  #

  KLS\Syndication\Agency\Controller\:
    resource: '%kernel.project_dir%/src/Syndication/Agency/Controller'
    tags:
      - { name: 'controller.service_arguments' }

  KLS\Syndication\Agency\DataPersister\ParticipationMemberDataPersister:
    decorates: 'api_platform.doctrine.orm.data_persister'

  KLS\Syndication\Agency\Serializer\ContextBuilder\ProjectContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    autoconfigure: false

  KLS\Syndication\Agency\Swagger\ProjectDecorator:
    decorates: 'api_platform.swagger.normalizer.api_gateway'

  KLS\Syndication\Arrangement\Service\Project\SlackNotifier\ProjectCreateNotifier:
    $formatter: '@currency_formatter_no_decimal'

  KLS\Syndication\Arrangement\Service\Project\SlackNotifier\ProjectUpdateNotifier:
    $formatter: '@currency_formatter_no_decimal'
