<?php

return array (
  'APP_SECRET' => NULL,
  'AWS_API_SECRET' => NULL,
  'DATABASE_URL' => NULL,
  'DATABASE_URL_MIGRATION' => NULL,
  'ENQUEUE_DSN' => NULL,
  'FILE_ENCRYPTION_KEK_PASSPHRASE' => NULL,
  'GOOGLE_RECAPTCHA_SECRET' => NULL,
  'JWT_PASSPHRASE' => NULL,
  'JWT_PUBLIC_KEY' => NULL,
  'JWT_SECRET_KEY' => NULL,
  'MAILJET_API_SECRET' => NULL,
);
