services:
  _defaults:
    autowire: true
    autoconfigure: true

  #
  # FEI
  #

  KLS\CreditGuaranty\FEI\Listener\Doctrine\Entity\ProgramCreatedListener:
    tags:
      - { name: doctrine.orm.entity_listener, event: prePersist, entity: KLS\CreditGuaranty\FEI\Entity\Program, method: createPredefinedChoiceOption }

  KLS\CreditGuaranty\FEI\Listener\Doctrine\ProgramDeleteListener:
    tags:
      - { name: doctrine.event_listener, event: onFlush }

  KLS\CreditGuaranty\FEI\Listener\Doctrine\ProgramEligibilityDeleteListener:
    tags:
      - { name: doctrine.event_listener, event: onFlush }

  KLS\CreditGuaranty\FEI\Listener\Doctrine\ReservationDeleteListener:
    tags:
      - { name: doctrine.event_listener, event: onFlush }
