imports:
  - { resource: doctrine_listeners.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  KLS\CreditGuaranty\:
    resource: '%kernel.project_dir%/src/CreditGuaranty/*'
    exclude: '%kernel.project_dir%/src/CreditGuaranty/{FEI}/{Console,Entity,Controller,Tests,Traits,Listener/Doctrine}'

  #
  # FEI
  #

  KLS\CreditGuaranty\FEI\Controller\:
    resource: '%kernel.project_dir%/src/CreditGuaranty/FEI/Controller'
    tags:
      - { name: 'controller.service_arguments' }

  # Serializer

  KLS\CreditGuaranty\FEI\Serializer\ContextBuilder\BorrowerContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    arguments:
      $decorated: '@.inner'
      $iriConverter: '@ApiPlatform\Core\Api\IriConverterInterface'

  KLS\CreditGuaranty\FEI\Serializer\ContextBuilder\FinancingObjectContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    arguments:
      $decorated: '@.inner'
      $iriConverter: '@ApiPlatform\Core\Api\IriConverterInterface'

  KLS\CreditGuaranty\FEI\Serializer\ContextBuilder\ProjectContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    arguments:
      $decorated: '@.inner'
      $security: '@Symfony\Component\Security\Core\Security'
      $programRepository: '@KLS\CreditGuaranty\FEI\Repository\ProgramRepository'

  KLS\CreditGuaranty\FEI\Serializer\ContextBuilder\ReservationContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    arguments:
      $decorated: '@.inner'
      $iriConverter: '@ApiPlatform\Core\Api\IriConverterInterface'
