# remove these if/when you are not fetching these directly
# from the container via $container->get()
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # move this line to services.yaml when not being fetched directly
    mailer: '@Unilend\SwiftMailer\UnilendMailer'

    # aliases so that the old service ids can still be accessed
    unilend.service.mail_queue: '@Unilend\Service\Mailer\MailQueueManager'
    unilend.service.mail_template: '@Unilend\Service\Mailer\MailTemplateManager'
    unilend.swiftmailer.message_provider: '@Unilend\SwiftMailer\TemplateMessageProvider'
